using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CQRSharp.EntityFrameworkCore;

/// <summary>
///     The EF Core mapping for <see cref="IdempotencyEntity" />. Apply it from your <c>DbContext.OnModelCreating</c>
///     through <c>modelBuilder.ApplyCqrsIdempotency(keyCollation)</c> (with <see cref="SqlServerBinaryCollation" /> on
///     SQL Server) so the idempotency table is created alongside your own entities.
/// </summary>
/// <param name="keyCollation">
///     The collation of the key column, or <c>null</c> for the database's default. The store contract compares keys
///     ordinally and case-sensitively, so on a provider whose default collation folds case - SQL Server's does - pass a
///     binary one (<see cref="SqlServerBinaryCollation" />); the EF Core idempotency store checks this at host start.
/// </param>
public sealed class IdempotencyEntityConfiguration(string? keyCollation = null) : IEntityTypeConfiguration<IdempotencyEntity>
{
    /// <summary>
    ///     A SQL Server collation that compares keys ordinally (binary, case- and accent-sensitive), as the idempotency
    ///     store contract requires.
    /// </summary>
    public const string SqlServerBinaryCollation = "Latin1_General_100_BIN2";

    /// <summary>The collation the key column is mapped with, or <c>null</c> for the database's default.</summary>
    public string? KeyCollation { get; } = keyCollation;

    /// <summary>
    ///     The longest idempotency key the relational schema accepts. 450 Unicode characters is the most a SQL Server
    ///     clustered primary key can hold (900 bytes); keeping keys within it makes them portable across every
    ///     relational backend. A caller with longer natural keys should hash them down before claiming.
    /// </summary>
    public const int KeyMaxLength = 450;

    /// <summary>
    ///     The longest payload fingerprint the relational schema accepts. The idempotency behavior passes a SHA-256
    ///     digest in 64 hexadecimal characters; the column leaves room for a store driven directly with another digest.
    /// </summary>
    public const int FingerprintMaxLength = 128;

    /// <summary>Maps <see cref="IdempotencyEntity" />: table, the Key string primary key, bounded key length, concurrency token, UTC coercion and the retention index.</summary>
    public void Configure(EntityTypeBuilder<IdempotencyEntity> builder)
    {
        builder.ToTable("CqrsIdempotencyKeys");

        // The Key is the caller-supplied idempotency key, never generated by the database.
        // KeyMaxLength bounds the relational key length so the column is index-friendly (and the primary key fits)
        // on providers (e.g. SQL Server) that cannot index unbounded text. Key comparison is the column's collation;
        // the store contract is ordinal and case-sensitive, so a case-folding provider needs KeyCollation.
        builder.HasKey(e => e.Key);
        var key = builder.Property(e => e.Key).ValueGeneratedNever().HasMaxLength(KeyMaxLength);
        if (KeyCollation is not null)
            key.UseCollation(KeyCollation);

        builder.Property(e => e.ExpiresAt).HasConversion(UtcDateTimeConverters.Instance);
        builder.Property(e => e.Fingerprint).HasMaxLength(FingerprintMaxLength);

        // Optimistic concurrency for the expired-row take-over: the same store-incremented integer token as the outbox
        // (a fresh INSERT is guarded by the unique primary key instead).
        builder.Property(e => e.RowVersion).IsConcurrencyToken();

        // Serves the retention purge, which deletes the oldest expired keys a page at a time: without it every purge scans
        // the whole table.
        builder.HasIndex(e => e.ExpiresAt);
    }
}
