// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Microsoft.CodeAnalysis;

namespace CQRSharp.Shared
{
    /// <summary>
    ///     The CQRSharp framework "well-known" type roles. Mirrors the public
    ///     <c>CQRSharp.Abstractions.Attributes.SourceGeneration.CqrsRole</c> enum <em>by member name</em> (numeric
    ///     values are irrelevant — roles are matched by name). A guard test asserts the two stay in sync.
    /// </summary>
    internal enum CqrsRole
    {
        Dispatcher,
        IRequest,
        INotification,
        ICommand,
        IQuery,
        IStreamRequest,
        IStreamRequestMarker,
        RequestBaseGeneric,
        ICommandHandler1,
        ICommandHandler2,
        IQueryHandler2,
        IQueryHandler3,
        IStreamRequestHandler2,
        IStreamRequestHandler3,
        INotificationHandler,
        IRequestValidator1,
        IRequestExceptionHandler3,
        IRequestExceptionAction2,
        IPreHandlerAttribute,
        IPostHandlerAttribute,
        PipelineExemptionAttribute,
        NotificationNameAttribute,
        RequestContextBase,
        CommandResult,
        IPipelineBehavior,
        IStreamPipelineBehavior,
        IRequestContextFactory,
        CqrsHandledRequestAttribute,
        CqrsHandledNotificationAttribute,
        ICommandWithResult,
        CommandResultGeneric,
        IResultCommandHandler2,
        IResultCommandHandler3
    }

    /// <summary>
    ///     Resolves CQRSharp framework types from a <see cref="Compilation" /> by reading the
    ///     <c>CqrsWellKnownType</c> assembly attributes that <c>CQRSharp.Core</c> declares via <c>typeof(...)</c>,
    ///     instead of matching fully-qualified name strings. Constructed once per compilation (cached) and shared,
    ///     verbatim, by the CQRSharp source generator and analyzers.
    /// </summary>
    /// <remarks>
    ///     Every generic role is stored as its <see cref="ISymbol.OriginalDefinition" /> (a <c>typeof(ICommandHandler&lt;,&gt;)</c>
    ///     round-trips from metadata as an unbound generic symbol; normalizing makes downstream
    ///     <see cref="SymbolEqualityComparer" /> checks against <c>iface.OriginalDefinition</c> match). The only
    ///     remaining hardcoded name is the attribute type itself — a 29:1 reduction, guarded by a unit test.
    /// </remarks>
    internal sealed class CqrsKnownSymbols
    {
        private const string WellKnownTypeAttributeMetadataName =
            "CQRSharp.Abstractions.Attributes.SourceGeneration.CqrsWellKnownTypeAttribute";

        // Roles whose absence — while CQRSharp.Core IS referenced — means genuine drift or a version mismatch, and
        // breaks generation/analysis. Stream roles are intentionally excluded: a netstandard2.0 consumer legitimately
        // lacks the stream types, and such a consumer cannot reference Core (net8.0+) anyway, so it never reaches here.
        private static readonly CqrsRole[] RequiredRoles =
        {
            CqrsRole.Dispatcher, CqrsRole.IRequest, CqrsRole.INotification, CqrsRole.ICommand, CqrsRole.IQuery,
            CqrsRole.RequestBaseGeneric, CqrsRole.ICommandHandler2, CqrsRole.IQueryHandler3,
            CqrsRole.INotificationHandler, CqrsRole.RequestContextBase, CqrsRole.CommandResult,
            CqrsRole.CqrsHandledRequestAttribute, CqrsRole.CqrsHandledNotificationAttribute
        };

        private static readonly ConditionalWeakTable<Compilation, CqrsKnownSymbols> Cache = new();

        private readonly Dictionary<CqrsRole, INamedTypeSymbol> _symbols = new();

        private CqrsKnownSymbols(Compilation compilation)
        {
            var attributeType = compilation.GetTypeByMetadataName(WellKnownTypeAttributeMetadataName);
            AbstractionsPresent = attributeType is not null;
            if (attributeType is null) return;

            // The attribute applications live on CQRSharp.Core's assembly metadata (and on the current assembly when
            // Core itself is being compiled). Scan the current assembly plus every referenced assembly.
            var count = CollectFrom(compilation.Assembly, attributeType);
            foreach (var reference in compilation.References)
            {
                if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assembly)
                    count += CollectFrom(assembly, attributeType);
            }

            ApplicationCount = count;
        }

        /// <summary>True when the <c>CqrsWellKnownType</c> attribute type was found, i.e. CQRSharp.Abstractions is referenced.</summary>
        public bool AbstractionsPresent { get; }

        /// <summary>The number of well-known-type attribute applications discovered. Zero usually means CQRSharp.Core is not referenced.</summary>
        public int ApplicationCount { get; }

        /// <summary>True when at least one well-known-type application was found, i.e. CQRSharp.Core is referenced.</summary>
        public bool CoreReferenced => ApplicationCount > 0;

        public static CqrsKnownSymbols For(Compilation compilation)
            => Cache.GetValue(compilation, static c => new CqrsKnownSymbols(c));

        public INamedTypeSymbol? Get(CqrsRole role) => _symbols.TryGetValue(role, out var symbol) ? symbol : null;

        /// <summary>
        ///     The required roles that could not be resolved while CQRSharp.Core IS referenced (i.e. real drift). Empty
        ///     when CQRSharp is absent or only CQRSharp.Abstractions is referenced (handled separately by the caller).
        /// </summary>
        public IReadOnlyList<string> GetMissingRequiredRoleNames()
        {
            if (!AbstractionsPresent || !CoreReferenced) return Array.Empty<string>();

            List<string>? missing = null;
            foreach (var role in RequiredRoles)
            {
                if (_symbols.ContainsKey(role)) continue;
                (missing ??= new List<string>()).Add(role.ToString());
            }

            return (IReadOnlyList<string>?)missing ?? Array.Empty<string>();
        }

        private int CollectFrom(IAssemblySymbol assembly, INamedTypeSymbol attributeType)
        {
            var count = 0;
            foreach (var attribute in assembly.GetAttributes())
            {
                if (!SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, attributeType)) continue;

                // A degraded reference closure can leave an attribute present but under-decoded (ctor args dropped).
                // Treat anything not shaped (CqrsRole, Type) as a missing role rather than crashing or silently skipping.
                if (attribute.ConstructorArguments.Length != 2) continue;

                var roleArg = attribute.ConstructorArguments[0];
                var typeArg = attribute.ConstructorArguments[1];
                if (roleArg.Kind != TypedConstantKind.Enum) continue;
                if (typeArg.Kind != TypedConstantKind.Type || typeArg.Value is not INamedTypeSymbol type) continue;

                var roleName = GetEnumMemberName(roleArg);
                if (roleName is null || !Enum.TryParse(roleName, out CqrsRole role)) continue;

                count++;
                // Always store the OriginalDefinition: an unbound typeof(ICommandHandler<,>) round-trips as the unbound
                // symbol, but every consumer compares against iface.OriginalDefinition, so normalize once here.
                _symbols[role] = type.OriginalDefinition;
            }

            return count;
        }

        private static string? GetEnumMemberName(TypedConstant enumConstant)
        {
            if (enumConstant.Type is not INamedTypeSymbol enumType) return null;
            var value = enumConstant.Value;
            if (value is null) return null;

            foreach (var member in enumType.GetMembers())
            {
                if (member is IFieldSymbol { HasConstantValue: true } field && Equals(field.ConstantValue, value))
                    return field.Name;
            }

            return null;
        }

        // Typed accessors. Names match the CqrsRole members (and the former TypeStrings constants) so call sites read
        // naturally; every generic accessor returns the stored OriginalDefinition.
        public INamedTypeSymbol? Dispatcher => Get(CqrsRole.Dispatcher);
        public INamedTypeSymbol? IRequest => Get(CqrsRole.IRequest);
        public INamedTypeSymbol? INotification => Get(CqrsRole.INotification);
        public INamedTypeSymbol? ICommand => Get(CqrsRole.ICommand);
        public INamedTypeSymbol? IQuery => Get(CqrsRole.IQuery);
        public INamedTypeSymbol? IStreamRequest => Get(CqrsRole.IStreamRequest);
        public INamedTypeSymbol? IStreamRequestMarker => Get(CqrsRole.IStreamRequestMarker);
        public INamedTypeSymbol? RequestBaseGeneric => Get(CqrsRole.RequestBaseGeneric);
        public INamedTypeSymbol? ICommandHandler1 => Get(CqrsRole.ICommandHandler1);
        public INamedTypeSymbol? ICommandHandler2 => Get(CqrsRole.ICommandHandler2);
        public INamedTypeSymbol? IQueryHandler2 => Get(CqrsRole.IQueryHandler2);
        public INamedTypeSymbol? IQueryHandler3 => Get(CqrsRole.IQueryHandler3);
        public INamedTypeSymbol? IStreamRequestHandler2 => Get(CqrsRole.IStreamRequestHandler2);
        public INamedTypeSymbol? IStreamRequestHandler3 => Get(CqrsRole.IStreamRequestHandler3);
        public INamedTypeSymbol? INotificationHandler => Get(CqrsRole.INotificationHandler);
        public INamedTypeSymbol? IRequestValidator1 => Get(CqrsRole.IRequestValidator1);
        public INamedTypeSymbol? IRequestExceptionHandler3 => Get(CqrsRole.IRequestExceptionHandler3);
        public INamedTypeSymbol? IRequestExceptionAction2 => Get(CqrsRole.IRequestExceptionAction2);
        public INamedTypeSymbol? IPreHandlerAttribute => Get(CqrsRole.IPreHandlerAttribute);
        public INamedTypeSymbol? IPostHandlerAttribute => Get(CqrsRole.IPostHandlerAttribute);
        public INamedTypeSymbol? PipelineExemptionAttribute => Get(CqrsRole.PipelineExemptionAttribute);
        public INamedTypeSymbol? NotificationNameAttribute => Get(CqrsRole.NotificationNameAttribute);
        public INamedTypeSymbol? RequestContextBase => Get(CqrsRole.RequestContextBase);
        public INamedTypeSymbol? CommandResult => Get(CqrsRole.CommandResult);
        public INamedTypeSymbol? IPipelineBehavior => Get(CqrsRole.IPipelineBehavior);
        public INamedTypeSymbol? IStreamPipelineBehavior => Get(CqrsRole.IStreamPipelineBehavior);
        public INamedTypeSymbol? IRequestContextFactory => Get(CqrsRole.IRequestContextFactory);
        public INamedTypeSymbol? CqrsHandledRequestAttribute => Get(CqrsRole.CqrsHandledRequestAttribute);
        public INamedTypeSymbol? CqrsHandledNotificationAttribute => Get(CqrsRole.CqrsHandledNotificationAttribute);
        public INamedTypeSymbol? ICommandWithResult => Get(CqrsRole.ICommandWithResult);
        public INamedTypeSymbol? CommandResultGeneric => Get(CqrsRole.CommandResultGeneric);
        public INamedTypeSymbol? IResultCommandHandler2 => Get(CqrsRole.IResultCommandHandler2);
        public INamedTypeSymbol? IResultCommandHandler3 => Get(CqrsRole.IResultCommandHandler3);
    }
}
