using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using CQRSharp.Shared;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CQRSharp.Generators.CqrsAotHintGenerator;

/// <summary>
///     A source generator that creates hints for the Native AOT compiler.
///     It scans the compilation for all request and open generic behavior/handler types
///     and generates explicit `typeof()` references for every possible generic instantiation.
///     This prevents the AOT compiler from trimming code that is only referenced dynamically
///     via dependency injection, which would otherwise cause runtime errors.
/// </summary>
[Generator]
public sealed class CqrsAotHintGenerator : IIncrementalGenerator
{
    private sealed record AotRequest(string RequestName, string ResultName);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Project concrete requests and open-generic behaviors into small equatable records in the transform, so this
        // generator caches per-changed-file instead of regenerating on every keystroke (and holds no symbols).
        var requests = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => ExtractRequest(ctx, ct))
            .Where(static r => r is not null)
            .Select(static (r, _) => r!)
            .Collect();

        var behaviors = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => ExtractOpenGenericBehavior(ctx, ct))
            .Where(static b => b is not null)
            .Select(static (b, _) => b!)
            .Collect();

        context.RegisterSourceOutput(requests.Combine(behaviors), static (spc, source) =>
        {
            var (requestModels, behaviorNames) = source;
            var sourceCode = GenerateAotHints(requestModels, behaviorNames);
            spc.AddSource("CqrsAotHints.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        });
    }

    private static AotRequest? ExtractRequest(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) is not INamedTypeSymbol type) return null;
        if (type is not { IsAbstract: false, IsGenericType: false } || !IsAccessibleFromGeneratedCode(type)) return null;

        var known = CqrsKnownSymbols.For(ctx.SemanticModel.Compilation);
        var iCommandSymbol = known.ICommand;
        var iQuerySymbol = known.IQuery;
        var commandResultSymbol = known.CommandResult;
        if (iCommandSymbol is null || iQuerySymbol is null || commandResultSymbol is null) return null;

        var isCommand = type.AllInterfaces.Contains(iCommandSymbol, SymbolEqualityComparer.Default);
        var queryInterface = type.AllInterfaces.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, iQuerySymbol));
        if (!isCommand && queryInterface is null) return null;

        var requestName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var resultName = (queryInterface?.TypeArguments[0] ?? commandResultSymbol).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return new AotRequest(requestName, resultName);
    }

    private static string? ExtractOpenGenericBehavior(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) is not INamedTypeSymbol type) return null;
        if (type is not { IsAbstract: false, IsGenericType: true } || !IsAccessibleFromGeneratedCode(type)) return null;

        var pipelineBehaviorSymbol = CqrsKnownSymbols.For(ctx.SemanticModel.Compilation).IPipelineBehavior;
        if (pipelineBehaviorSymbol is null) return null;
        if (!type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, pipelineBehaviorSymbol)))
            return null;

        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Split('<')[0];
    }

    private static bool IsAccessibleFromGeneratedCode(INamedTypeSymbol typeSymbol)
    {
        for (var current = typeSymbol; current is not null; current = current.ContainingType)
            if (current.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
                return false;
        return true;
    }

    private static string GenerateAotHints(ImmutableArray<AotRequest> requests, ImmutableArray<string> openGenericBehaviors)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This file is generated to provide hints to the AOT compiler. Do not edit manually.");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.AotHints");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class AotHintProvider");
        sb.AppendLine("    {");
        sb.AppendLine("        // Module initializer ensures these references are rooted and survive trimming.");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        internal static void Initialize()");
        sb.AppendLine("        {");

        sb.AppendLine("            // Preserving Pipeline Behavior instantiations:");
        foreach (var request in requests)
        foreach (var behaviorName in openGenericBehaviors)
            sb.AppendLine($"            _ = typeof({behaviorName}<{request.RequestName}, {request.ResultName}>);");

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
