using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CQRSharp.EntityFrameworkCore.Persistence;

/// <summary>
///     The EF Core mapping for <see cref="OutboxEntity" />. Apply it from your <c>DbContext.OnModelCreating</c>
///     (e.g. <c>modelBuilder.ApplyConfiguration(new OutboxEntityConfiguration())</c>) so the outbox table is created
///     and indexed alongside your own entities, and so the outbox can participate in your business transactions.
/// </summary>
public sealed class OutboxEntityConfiguration : IEntityTypeConfiguration<OutboxEntity>
{
    // SQLite (and some other providers) store DateTime without a Kind, so a value read back is Unspecified. The
    // store compares against TimeProvider.GetUtcNow() (a UTC DateTime), so coerce every persisted DateTime to UTC on
    // the way in and re-stamp Utc on the way out to keep all comparisons and back-off math in one consistent kind.
    private static readonly ValueConverter<DateTime, DateTime> UtcConverter = new(
        v => v.Kind == DateTimeKind.Utc ? v : v.ToUniversalTime(),
        v => DateTime.SpecifyKind(v, DateTimeKind.Utc));

    private static readonly ValueConverter<DateTime?, DateTime?> NullableUtcConverter = new(
        v => v.HasValue ? (v.Value.Kind == DateTimeKind.Utc ? v.Value : v.Value.ToUniversalTime()) : v,
        v => v.HasValue ? DateTime.SpecifyKind(v.Value, DateTimeKind.Utc) : v);

    /// <summary>Maps <see cref="OutboxEntity" />: table, key, status conversion, concurrency token, UTC coercion, and claim index.</summary>
    public void Configure(EntityTypeBuilder<OutboxEntity> builder)
    {
        builder.ToTable("CqrsOutboxMessages");

        // The Id is the caller-supplied message id, never generated by the database.
        builder.HasKey(e => e.Id);
        builder.Property(e => e.Id).ValueGeneratedNever();

        builder.Property(e => e.NotificationType).IsRequired();
        builder.Property(e => e.Payload).IsRequired();

        // Persist the status as its integer ordinal so the column is compact and provider-portable.
        builder.Property(e => e.Status).HasConversion<int>();

        builder.Property(e => e.CreatedAt).HasConversion(UtcConverter);
        builder.Property(e => e.ProcessedAt).HasConversion(NullableUtcConverter);
        builder.Property(e => e.NextRetryAt).HasConversion(NullableUtcConverter);
        builder.Property(e => e.LockedUntil).HasConversion(NullableUtcConverter);

        // Optimistic concurrency. We use a manual uint token that the store increments on every mutation rather
        // than a provider-native rowversion column, because native rowversion semantics differ across providers
        // (SQL Server: real 8-byte timestamp; SQLite/PostgreSQL: no equivalent). IsRowVersion marks it as the
        // concurrency token, but it also defaults the column to store-generated (OnAddOrUpdate); SQLite has no
        // generator for it, so we override generation to Never and write the value ourselves. A plain incremented
        // integer concurrency token works uniformly on every relational provider and is all the claim race needs.
        builder.Property(e => e.RowVersion).IsRowVersion().IsConcurrencyToken().ValueGeneratedNever();

        // The composite index serving the claim query: filter by Status, then by due-time (NextRetryAt), ordered by
        // CreatedAt for FIFO. Covering these in one index keeps the hot claim path off a table scan.
        builder.HasIndex(e => new { e.Status, e.NextRetryAt, e.CreatedAt });
    }
}
