using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    // ------------------------------------------------------------------------------------------------------
    // Emit. STJ source-gen cannot be used: Roslyn runs every generator against the user's original syntax, so a
    // [JsonSerializable] context we emit is invisible to STJ's generator, and reflection-based JsonSerializer is not
    // AOT-safe. So the serializer is hand-rolled over Utf8JsonReader/Writer, writing every shape the way STJ writes it.
    // One Serialize_/Deserialize_ pair per notification, plus WriteObj_/ReadObj_ per object type, WriteColl_/ReadColl_
    // per element type and WriteDict_/ReadDict_ per dictionary value type, deduped so a shared nested type emits once.
    // Every name is fully qualified: a consumer type in the global namespace (a Task, a Type) must not capture one.
    // ------------------------------------------------------------------------------------------------------

    private const string JsonWriter = "global::System.Text.Json.Utf8JsonWriter";
    private const string JsonReader = "global::System.Text.Json.Utf8JsonReader";
    private const string JsonTokenType = "global::System.Text.Json.JsonTokenType";
    private const string JsonException = "global::System.Text.Json.JsonException";
    private const string InvariantCulture = "global::System.Globalization.CultureInfo.InvariantCulture";
    private const string ByteBuffer = "global::System.Buffers.ArrayBufferWriter<byte>";
    private const string Generic = "global::System.Collections.Generic";

    // The generated readers assign from reads whose nullability the compiler cannot follow through the JSON; the
    // shapes themselves were checked when the models were built.
    private const string NullabilityPragma = "#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8619, CS8620, CS8625";

    private static string GenerateOutboxNotificationSerializer(IReadOnlyList<NotificationModel> stableNotifications, KnownSnapshot known, IReadOnlyCollection<string> suppressed)
    {
        var entries = stableNotifications
            .Select(n => new OutboxEmitEntry(
                n.TypeName,
                n.StableName!,
                n.OutboxRoot!,
                "Serialize_" + CreateIdentifierSuffix(n.StableName!, "N_"),
                "Deserialize_" + CreateIdentifierSuffix(n.StableName!, "N_")))
            .ToArray();

        var helpers = new OutboxHelpers();
        foreach (var entry in entries)
            helpers.Collect(entry.Root);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine(NullabilityPragma);
        EmitSuppressions(sb, suppressed);
        sb.AppendLine();
        sb.AppendLine($"namespace {known.ModuleNamespace}");
        sb.AppendLine("{");
        EmitSummary(sb, "    ", "Source-generated, AOT-safe (reflection-free) serializer for outbox notifications that carry a stable <c>[NotificationName]</c>. It writes what System.Text.Json writes for the same types, and reads what it reads.");
        sb.AppendLine("    internal sealed class GeneratedOutboxNotificationSerializer : global::CQRSharp.Persistence.INotificationSerializer");
        sb.AppendLine("    {");
        EmitSummary(sb, "        ", "Gets the <c>[NotificationName]</c> of exactly this notification type; a type without one is not durable.");
        sb.AppendLine("        public bool TryGetNotificationName(global::System.Type notificationType, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? notificationName)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(notificationType);");
        sb.AppendLine("            notificationName = GetStableName(notificationType);");
        sb.AppendLine("            return notificationName is not null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Serializes the notification to its stable JSON byte representation.");
        sb.AppendLine("        public byte[] Serialize(global::CQRSharp.INotification notification)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(notification);");
        sb.AppendLine();
        // An exact-type chain rather than a type-pattern switch: a base notification's arm would otherwise subsume a
        // derived notification's (CS8510), and a derived notification must be written by its own serializer anyway.
        sb.AppendLine("            var type = notification.GetType();");
        foreach (var entry in entries)
            sb.AppendLine($"            if (type == typeof({entry.TypeName})) return {entry.SerializeMethodName}(({entry.TypeName})notification);");
        sb.AppendLine(
            "            throw new global::System.InvalidOperationException($\"Notification type '{notification.GetType().FullName}' has no generated outbox serializer in this assembly. Mark it with [NotificationName] (in a shape the source generator supports), or register your own serializer with AddNotificationSerializer<T>(), which replaces the generated ones and must then name and serialize every durable notification.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Deserializes a payload back into its notification type, identified by stable name: null for a name this assembly does not know, a JsonException for a payload that cannot be read.");
        sb.AppendLine("        public global::CQRSharp.INotification? Deserialize(string notificationName, byte[] payload)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(notificationName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(payload);");
        sb.AppendLine();
        // No shortcut for an empty payload: for a known name it is as unreadable as any other corrupt payload, and the
        // reader's JsonException is what tells the outbox processor so (null would claim the name is unknown).
        sb.AppendLine("            return notificationName switch");
        sb.AppendLine("            {");
        foreach (var entry in entries)
            sb.AppendLine($"                {SymbolDisplay.FormatLiteral(entry.StableName, true)} => {entry.DeserializeMethodName}(payload),");

        sb.AppendLine("                _ => null");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        // An exact-type chain, like Serialize's: a derived notification has a name (and a payload shape) of its own.
        sb.AppendLine("        private static string? GetStableName(global::System.Type notificationType)");
        sb.AppendLine("        {");
        foreach (var entry in entries)
            sb.AppendLine($"            if (notificationType == typeof({entry.TypeName})) return {SymbolDisplay.FormatLiteral(entry.StableName, true)};");

        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var entry in entries)
        {
            sb.AppendLine($"        private static byte[] {entry.SerializeMethodName}({entry.TypeName} notification)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var buffer = new {ByteBuffer}();");
            sb.AppendLine($"            using (var writer = new {JsonWriter}(buffer))");
            sb.AppendLine("            {");
            sb.AppendLine($"                WriteObj_{entry.Root.HelperId}(writer, notification);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return buffer.WrittenSpan.ToArray();");
            sb.AppendLine("        }");
            sb.AppendLine();
            // Every way a payload can fail to read surfaces as a JsonException, as it does from System.Text.Json: a value
            // of the wrong token type or format, or out of range, is as corrupt as malformed JSON.
            sb.AppendLine($"        private static {entry.TypeName} {entry.DeserializeMethodName}(byte[] payload)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var reader = new {JsonReader}(payload, isFinalBlock: true, state: default);");
            sb.AppendLine("                if (!reader.Read())");
            sb.AppendLine($"                    throw new {JsonException}(\"Expected start of JSON object.\");");
            sb.AppendLine($"                return ReadObj_{entry.Root.HelperId}(ref reader);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (global::System.Exception ex) when (ex is global::System.FormatException or global::System.InvalidOperationException or global::System.OverflowException)");
            sb.AppendLine("            {");
            sb.AppendLine($"                throw new {JsonException}({SymbolDisplay.FormatLiteral($"The '{entry.StableName}' payload cannot be read: ", true)} + ex.Message, ex);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        foreach (var obj in helpers.Objects)
        {
            GenerateWriteObject(sb, obj, canonical: false);
            sb.AppendLine();
            GenerateReadObject(sb, obj);
            sb.AppendLine();
        }

        foreach (var element in helpers.CollectionElements)
        {
            GenerateWriteCollection(sb, element, canonical: false);
            sb.AppendLine();
            GenerateReadCollection(sb, element);
            sb.AppendLine();
        }

        foreach (var value in helpers.DictionaryValues)
        {
            GenerateWriteDictionary(sb, value, canonical: false);
            sb.AppendLine();
            GenerateReadDictionary(sb, value);
            sb.AppendLine();
        }

        GenerateScalarReaders(sb, helpers.ScalarKinds);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed record OutboxEmitEntry(
        string TypeName,
        string StableName,
        OutboxObjectModel Root,
        string SerializeMethodName,
        string DeserializeMethodName);

    /// <summary>Every helper one generated file needs, collected from its root object models and emitted in a stable order.</summary>
    private sealed class OutboxHelpers
    {
        private readonly Dictionary<string, OutboxObjectModel> _objects = new(StringComparer.Ordinal);
        private readonly Dictionary<string, OutboxValueModel> _collectionElements = new(StringComparer.Ordinal);
        private readonly Dictionary<string, OutboxValueModel> _setElements = new(StringComparer.Ordinal);
        private readonly Dictionary<string, OutboxValueModel> _dictionaryValues = new(StringComparer.Ordinal);

        public IEnumerable<OutboxObjectModel> Objects => _objects.Values.OrderBy(o => o.HelperId, StringComparer.Ordinal);
        public IEnumerable<OutboxValueModel> CollectionElements => _collectionElements.Values.OrderBy(CollectionHelperId, StringComparer.Ordinal);
        public IEnumerable<OutboxValueModel> SetElements => _setElements.Values.OrderBy(CollectionHelperId, StringComparer.Ordinal);
        public IEnumerable<OutboxValueModel> DictionaryValues => _dictionaryValues.Values.OrderBy(DictionaryHelperId, StringComparer.Ordinal);
        public HashSet<OutboxScalarKind> ScalarKinds { get; } = new();

        public void Collect(OutboxObjectModel obj)
        {
            if (_objects.ContainsKey(obj.HelperId)) return;
            _objects.Add(obj.HelperId, obj);
            foreach (var member in obj.Members)
                Collect(member.Value);
        }

        private void Collect(OutboxValueModel value)
        {
            switch (value.Kind)
            {
                case OutboxValueKind.Scalar:
                    ScalarKinds.Add(value.ScalarKind);
                    break;
                case OutboxValueKind.Object:
                    Collect(value.ObjectModel!);
                    break;
                case OutboxValueKind.Collection:
                    _collectionElements[CollectionHelperId(value.Element!)] = value.Element!;
                    if (value.CollectionShape == OutboxCollectionShape.Set)
                        _setElements[CollectionHelperId(value.Element!)] = value.Element!;
                    Collect(value.Element!);
                    break;
                case OutboxValueKind.Dictionary:
                    _dictionaryValues[DictionaryHelperId(value.Element!)] = value.Element!;
                    Collect(value.Element!);
                    break;
            }
        }
    }

    private static string CollectionHelperId(OutboxValueModel element) =>
        CreateIdentifierSuffix(Signature(element), "C_");

    private static string DictionaryHelperId(OutboxValueModel value) =>
        CreateIdentifierSuffix(Signature(value), "D_");

    // What a value's helpers are shared by: its type as written, including whether each reference in it may be null. A
    // List<string?> and a List<string> (or an oblivious one) read a JSON null differently, so they get different helpers.
    private static string Signature(OutboxValueModel value)
    {
        var signature = value.IsNullableReferenceType ? value.LocalTypeName + "?" : value.LocalTypeName;
        return value.Element is { } element ? $"{signature}<{Signature(element)}>" : signature;
    }

    // A canonical writer (the request fingerprinter's) writes equal values identically: a dictionary's entries in
    // ordinal key order and a set's elements in the order of their rendered bytes, whatever order they were added in.
    private static void GenerateWriteObject(StringBuilder sb, OutboxObjectModel obj, bool canonical)
    {
        sb.AppendLine($"        private static void WriteObj_{obj.HelperId}({JsonWriter} writer, {obj.TypeName} value)");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.WriteStartObject();");
        foreach (var member in obj.Members)
        {
            sb.AppendLine($"            writer.WritePropertyName({SymbolDisplay.FormatLiteral(member.JsonName, true)});");
            AppendWriteValue(sb, "            ", member.Value, $"value.{EscapeIdentifier(member.PropertyName)}", canonical);
        }

        sb.AppendLine("            writer.WriteEndObject();");
        sb.AppendLine("        }");
    }

    /// <summary>
    ///     A reader that builds the object the way System.Text.Json does: a member the payload lacks keeps what the type's
    ///     own construction gives it (its initializer, or the default of the constructor parameter it is passed to), so a
    ///     message stored before a member was added reads back as the new code expects; a missing <c>required</c> member
    ///     is a <c>JsonException</c>. The object is built once when the payload is complete; a template instance is built
    ///     only to read the defaults of the members it lacks.
    /// </summary>
    private static void GenerateReadObject(StringBuilder sb, OutboxObjectModel obj)
    {
        var initialized = obj.Members.Where(m => m.CanInitialize && (!m.IsConstructorParameter || m.IsRequired)).ToArray();

        sb.AppendLine($"        private static {obj.TypeName} ReadObj_{obj.HelperId}(ref {JsonReader} reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (reader.TokenType != {JsonTokenType}.StartObject)");
        sb.AppendLine($"                throw new {JsonException}({SymbolDisplay.FormatLiteral($"Expected a JSON object for '{obj.TypeName}'.", true)});");
        sb.AppendLine();
        foreach (var member in obj.Members)
            sb.AppendLine($"            {member.Value.LocalTypeName} {member.LocalName} = {member.DefaultValueExpression ?? DefaultExpression(member.Value)};");
        foreach (var member in initialized)
            sb.AppendLine($"            bool {PresenceFlag(member)} = false;");

        sb.AppendLine();
        sb.AppendLine("            while (reader.Read())");
        sb.AppendLine("            {");
        sb.AppendLine($"                if (reader.TokenType == {JsonTokenType}.EndObject) break;");
        sb.AppendLine();
        sb.AppendLine("                var propName = reader.GetString();");
        sb.AppendLine("                if (!reader.Read()) break;");
        sb.AppendLine();
        sb.AppendLine("                switch (propName)");
        sb.AppendLine("                {");
        foreach (var member in obj.Members)
        {
            sb.AppendLine($"                    case {SymbolDisplay.FormatLiteral(member.JsonName, true)}:");
            if (!string.Equals(member.JsonName, member.PropertyName, StringComparison.Ordinal))
                sb.AppendLine($"                    case {SymbolDisplay.FormatLiteral(member.PropertyName, true)}:");

            sb.AppendLine($"                        {member.LocalName} = {ReadValueExpression(member.Value)};");
            if (initialized.Contains(member))
                sb.AppendLine($"                        {PresenceFlag(member)} = true;");
            sb.AppendLine("                        break;");
        }

        sb.AppendLine("                    default:");
        sb.AppendLine("                        reader.Skip();");
        sb.AppendLine("                        break;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();

        var required = initialized.Where(m => m.IsRequired).ToArray();
        foreach (var member in required)
            sb.AppendLine(
                $"            if (!{PresenceFlag(member)}) throw new {JsonException}(" +
                $"{SymbolDisplay.FormatLiteral($"The payload of '{obj.TypeName}' lacks its required member '{member.JsonName}'.", true)});");

        // A required member goes in the initializer even when the constructor already takes it: the compiler demands
        // it there (CS9035) unless the constructor is marked [SetsRequiredMembers], and setting it twice is harmless.
        var requiredAssignments = required.Select(Assignment).ToArray();
        var optional = initialized.Where(m => !m.IsRequired).ToArray();
        if (optional.Length > 0)
        {
            sb.AppendLine($"            if ({string.Join(" || ", optional.Select(m => "!" + PresenceFlag(m)))})");
            sb.AppendLine("            {");
            sb.AppendLine($"                var __template = {Construction(obj.ConstructorExpression, requiredAssignments)};");
            foreach (var member in optional)
            {
                // A non-nullable string reads back as "" rather than null, absent or not.
                var fallback = member.Value is { Kind: OutboxValueKind.Scalar, ScalarKind: OutboxScalarKind.String, IsNullableReferenceType: false }
                    ? " ?? string.Empty"
                    : string.Empty;
                sb.AppendLine($"                if (!{PresenceFlag(member)}) {member.LocalName} = __template.{EscapeIdentifier(member.PropertyName)}{fallback};");
            }

            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine($"            return {Construction(obj.ConstructorExpression, initialized.Select(Assignment).ToArray())};");
        sb.AppendLine("        }");

        static string Assignment(OutboxMemberModel member) => $"{EscapeIdentifier(member.PropertyName)} = {member.LocalName}";

        static string Construction(string constructor, string[] assignments)
            => assignments.Length == 0 ? constructor : $"{constructor} {{ {string.Join(", ", assignments)} }}";
    }

    private static string PresenceFlag(OutboxMemberModel member) => "__present" + member.LocalName;

    private static void GenerateWriteCollection(StringBuilder sb, OutboxValueModel element, bool canonical)
    {
        var id = CollectionHelperId(element);
        sb.AppendLine($"        private static void WriteColl_{id}({JsonWriter} writer, {Generic}.IEnumerable<{element.LocalTypeName}> value)");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.WriteStartArray();");
        sb.AppendLine("            foreach (var item in value)");
        sb.AppendLine("            {");
        AppendWriteValue(sb, "                ", element, "item", canonical);
        sb.AppendLine("            }");
        sb.AppendLine("            writer.WriteEndArray();");
        sb.AppendLine("        }");
    }

    // A set has no order of its own; each element is rendered alone and the elements are written in the order of their
    // bytes, so two equal sets write the same JSON however they were built.
    private static void GenerateWriteCanonicalSet(StringBuilder sb, OutboxValueModel element)
    {
        var id = CollectionHelperId(element);
        sb.AppendLine($"        private static void WriteSet_{id}({JsonWriter} writer, {Generic}.IEnumerable<{element.LocalTypeName}> value)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var items = new {Generic}.List<byte[]>();");
        sb.AppendLine("            foreach (var item in value)");
        sb.AppendLine($"                items.Add(Render_{id}(item));");
        sb.AppendLine("            items.Sort(static (x, y) => global::System.MemoryExtensions.SequenceCompareTo(new global::System.ReadOnlySpan<byte>(x), new global::System.ReadOnlySpan<byte>(y)));");
        sb.AppendLine("            writer.WriteStartArray();");
        sb.AppendLine("            foreach (var item in items)");
        sb.AppendLine("                writer.WriteRawValue(item, skipInputValidation: true);");
        sb.AppendLine("            writer.WriteEndArray();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        private static byte[] Render_{id}({element.LocalTypeName} item)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var buffer = new {ByteBuffer}();");
        sb.AppendLine($"            using (var writer = new {JsonWriter}(buffer))");
        sb.AppendLine("            {");
        AppendWriteValue(sb, "                ", element, "item", canonical: true);
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return buffer.WrittenSpan.ToArray();");
        sb.AppendLine("        }");
    }

    private static void GenerateReadCollection(StringBuilder sb, OutboxValueModel element)
    {
        var id = CollectionHelperId(element);
        sb.AppendLine($"        private static {Generic}.List<{element.LocalTypeName}> ReadColl_{id}(ref {JsonReader} reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (reader.TokenType != {JsonTokenType}.StartArray)");
        sb.AppendLine($"                throw new {JsonException}(\"Expected a JSON array.\");");
        sb.AppendLine();
        sb.AppendLine($"            var items = new {Generic}.List<{element.LocalTypeName}>();");
        sb.AppendLine("            while (reader.Read())");
        sb.AppendLine("            {");
        sb.AppendLine($"                if (reader.TokenType == {JsonTokenType}.EndArray) break;");
        sb.AppendLine($"                {element.LocalTypeName} item = {ReadValueExpression(element)};");
        sb.AppendLine("                items.Add(item);");
        sb.AppendLine("            }");
        sb.AppendLine("            return items;");
        sb.AppendLine("        }");
    }

    // A dictionary with string keys is a JSON object whose property names are the keys, as System.Text.Json writes it.
    private static void GenerateWriteDictionary(StringBuilder sb, OutboxValueModel value, bool canonical)
    {
        var id = DictionaryHelperId(value);
        var pair = $"{Generic}.KeyValuePair<string, {value.LocalTypeName}>";
        sb.AppendLine($"        private static void WriteDict_{id}({JsonWriter} writer, {Generic}.IEnumerable<{pair}> value)");
        sb.AppendLine("        {");
        var source = "value";
        if (canonical)
        {
            sb.AppendLine($"            var pairs = new {Generic}.List<{pair}>(value);");
            sb.AppendLine("            pairs.Sort(static (x, y) => string.CompareOrdinal(x.Key, y.Key));");
            source = "pairs";
        }

        sb.AppendLine("            writer.WriteStartObject();");
        sb.AppendLine($"            foreach (var pair in {source})");
        sb.AppendLine("            {");
        sb.AppendLine("                writer.WritePropertyName(pair.Key);");
        AppendWriteValue(sb, "                ", value, "pair.Value", canonical);
        sb.AppendLine("            }");
        sb.AppendLine("            writer.WriteEndObject();");
        sb.AppendLine("        }");
    }

    // A key read twice keeps its last value, as System.Text.Json's dictionary reader does.
    private static void GenerateReadDictionary(StringBuilder sb, OutboxValueModel value)
    {
        var id = DictionaryHelperId(value);
        var dictionary = $"{Generic}.Dictionary<string, {value.LocalTypeName}>";
        sb.AppendLine($"        private static {dictionary} ReadDict_{id}(ref {JsonReader} reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (reader.TokenType != {JsonTokenType}.StartObject)");
        sb.AppendLine($"                throw new {JsonException}(\"Expected a JSON object.\");");
        sb.AppendLine();
        sb.AppendLine($"            var items = new {dictionary}();");
        sb.AppendLine("            while (reader.Read())");
        sb.AppendLine("            {");
        sb.AppendLine($"                if (reader.TokenType == {JsonTokenType}.EndObject) break;");
        sb.AppendLine("                var key = reader.GetString()!;");
        sb.AppendLine("                if (!reader.Read()) break;");
        sb.AppendLine($"                {value.LocalTypeName} item = {ReadValueExpression(value)};");
        sb.AppendLine("                items[key] = item;");
        sb.AppendLine("            }");
        sb.AppendLine("            return items;");
        sb.AppendLine("        }");
    }

    // The scalars System.Text.Json reads from a string with a format of its own. A malformed one fails with a
    // FormatException, which Deserialize reports as the payload's JsonException.
    private static void GenerateScalarReaders(StringBuilder sb, HashSet<OutboxScalarKind> kinds)
    {
        if (kinds.Contains(OutboxScalarKind.Char))
        {
            sb.AppendLine($"        private static char ReadChar(ref {JsonReader} reader)");
            sb.AppendLine("        {");
            sb.AppendLine("            var text = reader.GetString();");
            sb.AppendLine($"            if (text is null || text.Length != 1) throw new {JsonException}(\"Expected a string of exactly one character.\");");
            sb.AppendLine("            return text[0];");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        if (kinds.Contains(OutboxScalarKind.TimeSpan))
        {
            sb.AppendLine($"        private static global::System.TimeSpan ReadTimeSpan(ref {JsonReader} reader)");
            sb.AppendLine($"            => global::System.TimeSpan.ParseExact(reader.GetString() ?? string.Empty, \"c\", {InvariantCulture});");
            sb.AppendLine();
        }

        if (kinds.Contains(OutboxScalarKind.DateOnly))
        {
            sb.AppendLine($"        private static global::System.DateOnly ReadDateOnly(ref {JsonReader} reader)");
            sb.AppendLine($"            => global::System.DateOnly.ParseExact(reader.GetString() ?? string.Empty, \"O\", {InvariantCulture});");
            sb.AppendLine();
        }

        if (kinds.Contains(OutboxScalarKind.TimeOnly))
        {
            // System.Text.Json writes a TimeOnly as its time of day in the TimeSpan "c" format.
            sb.AppendLine($"        private static global::System.TimeOnly ReadTimeOnly(ref {JsonReader} reader)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var time = global::System.TimeSpan.ParseExact(reader.GetString() ?? string.Empty, \"c\", {InvariantCulture});");
            sb.AppendLine("            if (time < global::System.TimeSpan.Zero || time.Ticks >= global::System.TimeSpan.TicksPerDay)");
            sb.AppendLine($"                throw new {JsonException}(\"Expected a time of day.\");");
            sb.AppendLine("            return global::System.TimeOnly.FromTimeSpan(time);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        if (kinds.Contains(OutboxScalarKind.Uri))
        {
            sb.AppendLine($"        private static global::System.Uri ReadUri(ref {JsonReader} reader)");
            sb.AppendLine("            => global::System.Uri.TryCreate(reader.GetString(), global::System.UriKind.RelativeOrAbsolute, out var uri)");
            sb.AppendLine("                ? uri");
            sb.AppendLine($"                : throw new {JsonException}(\"Expected a URI.\");");
            sb.AppendLine();
        }
    }

    private static void AppendWriteValue(StringBuilder sb, string indent, OutboxValueModel value, string valueExpr, bool canonical)
    {
        if (value.IsNullableValueType)
        {
            sb.AppendLine($"{indent}if (({valueExpr}).HasValue)");
            sb.AppendLine($"{indent}{{");
            AppendWriteNonNullValue(sb, indent + "    ", value, $"({valueExpr}).Value", canonical);
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}else");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    writer.WriteNullValue();");
            sb.AppendLine($"{indent}}}");
            return;
        }

        AppendWriteNonNullValue(sb, indent, value, valueExpr, canonical);
    }

    private static void AppendWriteNonNullValue(StringBuilder sb, string indent, OutboxValueModel value, string valueExpr, bool canonical)
    {
        switch (value.Kind)
        {
            case OutboxValueKind.Scalar:
                sb.AppendLine($"{indent}{ScalarWriteStatement(value.ScalarKind, valueExpr)}");
                return;
            case OutboxValueKind.Enum:
                sb.AppendLine($"{indent}writer.WriteNumberValue(({value.EnumUnderlyingTypeName}){valueExpr});");
                return;
            case OutboxValueKind.Object:
                if (value.IsReferenceType)
                {
                    sb.AppendLine($"{indent}if ({valueExpr} is null) writer.WriteNullValue();");
                    sb.AppendLine($"{indent}else WriteObj_{value.ObjectModel!.HelperId}(writer, {valueExpr});");
                }
                else
                {
                    sb.AppendLine($"{indent}WriteObj_{value.ObjectModel!.HelperId}(writer, {valueExpr});");
                }

                return;
            case OutboxValueKind.Collection:
                var writeCollection = canonical && value.CollectionShape == OutboxCollectionShape.Set ? "WriteSet_" : "WriteColl_";
                sb.AppendLine($"{indent}if ({valueExpr} is null) writer.WriteNullValue();");
                sb.AppendLine($"{indent}else {writeCollection}{CollectionHelperId(value.Element!)}(writer, {valueExpr});");
                return;
            case OutboxValueKind.Dictionary:
                sb.AppendLine($"{indent}if ({valueExpr} is null) writer.WriteNullValue();");
                sb.AppendLine($"{indent}else WriteDict_{DictionaryHelperId(value.Element!)}(writer, {valueExpr});");
                return;
        }
    }

    // Each written as System.Text.Json writes it: dates and times as ISO 8601, a TimeSpan (and a TimeOnly's time of
    // day) in the "c" format, a char as a one-character string, a Uri as its original string.
    private static string ScalarWriteStatement(OutboxScalarKind kind, string valueExpr) =>
        kind switch
        {
            OutboxScalarKind.String => $"writer.WriteStringValue({valueExpr});",
            OutboxScalarKind.Guid => $"writer.WriteStringValue({valueExpr});",
            OutboxScalarKind.DateTime => $"writer.WriteStringValue({valueExpr});",
            OutboxScalarKind.DateTimeOffset => $"writer.WriteStringValue({valueExpr});",
            OutboxScalarKind.TimeSpan => $"writer.WriteStringValue({valueExpr}.ToString(\"c\", {InvariantCulture}));",
            OutboxScalarKind.DateOnly => $"writer.WriteStringValue({valueExpr}.ToString(\"O\", {InvariantCulture}));",
            OutboxScalarKind.TimeOnly => $"writer.WriteStringValue({valueExpr}.ToTimeSpan().ToString(\"c\", {InvariantCulture}));",
            OutboxScalarKind.Char => $"writer.WriteStringValue({valueExpr}.ToString());",
            OutboxScalarKind.Uri => $"writer.WriteStringValue({valueExpr}?.OriginalString);",
            OutboxScalarKind.Boolean => $"writer.WriteBooleanValue({valueExpr});",
            _ => $"writer.WriteNumberValue({valueExpr});"
        };

    private static string DefaultExpression(OutboxValueModel value)
    {
        if (value.Kind == OutboxValueKind.Scalar && value.ScalarKind == OutboxScalarKind.String)
            return value.IsNullableReferenceType ? "null" : "string.Empty";

        return $"default({value.LocalTypeName})";
    }

    private static string ReadValueExpression(OutboxValueModel value)
    {
        var read = NonNullReadExpression(value);
        return $"reader.TokenType == {JsonTokenType}.Null ? {DefaultExpression(value)} : {read}";
    }

    private static string NonNullReadExpression(OutboxValueModel value)
    {
        switch (value.Kind)
        {
            case OutboxValueKind.Scalar:
                return value.ScalarKind == OutboxScalarKind.String
                    ? value.IsNullableReferenceType ? "reader.GetString()" : "(reader.GetString() ?? string.Empty)"
                    : ScalarReadExpression(value.ScalarKind);
            case OutboxValueKind.Enum:
                return $"({value.NonNullableTypeName})reader.{EnumReaderMethod(value.EnumUnderlyingTypeName)}()";
            case OutboxValueKind.Object:
                return $"ReadObj_{value.ObjectModel!.HelperId}(ref reader)";
            case OutboxValueKind.Collection:
                var read = $"ReadColl_{CollectionHelperId(value.Element!)}(ref reader)";
                return value.CollectionShape switch
                {
                    OutboxCollectionShape.Array => read + ".ToArray()",
                    OutboxCollectionShape.Set => $"new {Generic}.HashSet<{value.Element!.LocalTypeName}>({read})",
                    _ => read
                };
            case OutboxValueKind.Dictionary:
                return $"ReadDict_{DictionaryHelperId(value.Element!)}(ref reader)";
            default:
                return "default";
        }
    }

    private static string ScalarReadExpression(OutboxScalarKind kind) =>
        kind switch
        {
            OutboxScalarKind.Guid => "reader.GetGuid()",
            OutboxScalarKind.DateTime => "reader.GetDateTime()",
            OutboxScalarKind.DateTimeOffset => "reader.GetDateTimeOffset()",
            OutboxScalarKind.TimeSpan => "ReadTimeSpan(ref reader)",
            OutboxScalarKind.DateOnly => "ReadDateOnly(ref reader)",
            OutboxScalarKind.TimeOnly => "ReadTimeOnly(ref reader)",
            OutboxScalarKind.Char => "ReadChar(ref reader)",
            OutboxScalarKind.Uri => "ReadUri(ref reader)",
            OutboxScalarKind.Boolean => "reader.GetBoolean()",
            OutboxScalarKind.Byte => "reader.GetByte()",
            OutboxScalarKind.SByte => "reader.GetSByte()",
            OutboxScalarKind.Int16 => "reader.GetInt16()",
            OutboxScalarKind.UInt16 => "reader.GetUInt16()",
            OutboxScalarKind.Int32 => "reader.GetInt32()",
            OutboxScalarKind.UInt32 => "reader.GetUInt32()",
            OutboxScalarKind.Int64 => "reader.GetInt64()",
            OutboxScalarKind.UInt64 => "reader.GetUInt64()",
            OutboxScalarKind.Single => "reader.GetSingle()",
            OutboxScalarKind.Double => "reader.GetDouble()",
            OutboxScalarKind.Decimal => "reader.GetDecimal()",
            _ => throw new ArgumentOutOfRangeException(nameof(kind), kind, "A scalar kind without a reader.")
        };

    // The underlying type arrives rendered with FullyQualifiedFormat, which prints special types as C# keywords
    // ("long", not "global::System.Int64"). Matching only the metadata names sent every enum to GetInt32, which throws
    // on a long/uint/ulong value outside the int range — leaving that outbox message undeliverable.
    private static string EnumReaderMethod(string? enumUnderlyingTypeName) =>
        enumUnderlyingTypeName switch
        {
            "byte" or "global::System.Byte" => "GetByte",
            "sbyte" or "global::System.SByte" => "GetSByte",
            "short" or "global::System.Int16" => "GetInt16",
            "ushort" or "global::System.UInt16" => "GetUInt16",
            "int" or "global::System.Int32" => "GetInt32",
            "uint" or "global::System.UInt32" => "GetUInt32",
            "long" or "global::System.Int64" => "GetInt64",
            "ulong" or "global::System.UInt64" => "GetUInt64",
            _ => "GetInt32"
        };
}
