using System;
using System.Linq;
using System.Text;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    // Emitted in every CQRSharp-referencing assembly, as INTERNAL entry points. Because they are internal, two
    // assemblies that both emit them never collide — a referenced assembly's internal AddCqrsGenerated is invisible
    // to the referencing one, so each assembly uses its own. That removes the need to designate a "composition root":
    // AddCqrsGenerated wires this assembly's module plus every referenced assembly's module, and you call it from
    // wherever you set up DI (which is always inside the calling assembly, so internal visibility suffices).
    private static string GenerateBootstrap(KnownSnapshot known, bool hasLocalModule)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        // The host's behaviors closed over the referenced assemblies' requests are the only consumer types named here.
        var closedSuppressions = known.ReferencedClosedBehaviors.SelectMany(b => b.SuppressedWarnings)
            .Distinct(StringComparer.Ordinal).OrderBy(id => id, StringComparer.Ordinal).ToArray();
        EmitSuppressions(sb, closedSuppressions);

        // With a referenced assembly's internal bootstrap visible here (InternalsVisibleTo), a second one in namespace
        // CQRSharp makes the plain AddCqrsGenerated() call ambiguous (CS0121) - which is the right outcome when this
        // assembly has a module of its own that the other assembly's bootstrap would silently skip. An assembly with
        // no module of its own and exactly one such bootstrap in view leaves the plain call to that bootstrap, which
        // registers the same reference graph. Either way, this assembly's own entry point is also emitted under its
        // module namespace, where nothing can collide with it (CQRGEN015 points there), and the CQRSharp copy forwards
        // to it.
        if (known.VisibleForeignBootstraps == 0)
        {
            EmitBootstrap(sb, known, hasLocalModule, "CQRSharp");
            return sb.ToString();
        }

        EmitBootstrap(sb, known, hasLocalModule, known.ModuleNamespace);
        if (hasLocalModule || known.VisibleForeignBootstraps != 1 || !known.ForeignBootstrapCoversGraph)
            EmitForwardingBootstrap(sb, known);

        return sb.ToString();
    }

    private static void EmitBootstrap(StringBuilder sb, KnownSnapshot known, bool hasLocalModule, string ns)
    {
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        EmitBootstrapTypeHeader(sb);

        // The value-type-result requests the referenced assemblies handle, closed over the behaviors this assembly can
        // see (a library closes only its own view), and the ones it cannot close: used under Native AOT.
        if (known.ReferencedClosedBehaviors.Count > 0 || known.ReferencedClosedBehaviorGaps.Count > 0)
        {
            EmitClosedBehaviorCatalogs(sb, "        ", known.ReferencedClosedBehaviors, known.ReferencedClosedBehaviorGaps, "__referencedClosedBehaviors", "__referencedClosedBehaviorGaps");
            sb.AppendLine();
        }

        // With CQRSharp.Pipelines referenced, the parameterless entry point is the builder with nothing configured, so it
        // carries the builder's defaults (the validation and exception-handling behaviors): the entry point most
        // applications call must not leave their validators silently inert. Without it there is no behavior to add.
        EmitSummary(sb, "        ", known.HasPipelinesBuilder
            ? "Registers CQRSharp and the source-generated handlers and dispatchers of this assembly and every referenced CQRSharp assembly, with the builder's defaults: the validation and exception-handling behaviors. The same as the overload that takes an <c>ICqrsBuilder</c> configuration, called with an empty one; use that overload to configure anything else."
            : "Registers CQRSharp and the source-generated handlers and dispatchers of this assembly and every referenced CQRSharp assembly. No pipeline behavior is added: they come with CQRSharp.Pipelines, which this assembly does not reference.");
        EmitServicesParam(sb);
        sb.AppendLine($"        internal static {ServiceCollection} AddCqrsGenerated(this {ServiceCollection} services)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(services);");
        sb.AppendLine();
        sb.AppendLine(known.HasPipelinesBuilder
            ? "            global::CQRSharp.Pipelines.CqrsBuilderBootstrap.Build(services, _ => { });"
            : "            global::CQRSharp.DependencyInjectionExtensions.AddCqrs(services);");
        sb.AppendLine("            RegisterModules(services);");
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");

        // Only where the consumer references CQRSharp.Pipelines, which defines ICqrsBuilder. Core does not reference
        // Pipelines, but the consumer assembly this is emitted into references both, so the generated code can bridge them.
        if (known.HasPipelinesBuilder)
        {
            sb.AppendLine();
            EmitBuilderSummary(sb);
            sb.AppendLine($"        internal static {ServiceCollection} AddCqrsGenerated(this {ServiceCollection} services, global::System.Action<global::CQRSharp.Pipelines.ICqrsBuilder> configure)");
            sb.AppendLine("        {");
            sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(services);");
            sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(configure);");
            sb.AppendLine();
            // The generated registrations go last: their dispatcher registrations replace whatever came before them.
            sb.AppendLine("            global::CQRSharp.Pipelines.CqrsBuilderBootstrap.Build(services, configure);");
            sb.AppendLine("            RegisterModules(services);");
            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
        }

        sb.AppendLine();
        EmitRegisterModules(sb, known, hasLocalModule);
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    // The copy in namespace CQRSharp beside a visible foreign bootstrap: the same entry points, forwarding to this
    // assembly's module-namespace copy, so the registrations exist once.
    private static void EmitForwardingBootstrap(StringBuilder sb, KnownSnapshot known)
    {
        var target = $"global::{known.ModuleNamespace}.CqrsGeneratedBootstrap";

        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp");
        sb.AppendLine("{");
        EmitBootstrapTypeHeader(sb);

        EmitSummary(sb, "        ", $"Registers CQRSharp and the source-generated handlers and dispatchers; the same as <c>{known.ModuleNamespace}.CqrsGeneratedBootstrap.AddCqrsGenerated(services)</c>.");
        EmitServicesParam(sb);
        sb.AppendLine($"        internal static {ServiceCollection} AddCqrsGenerated(this {ServiceCollection} services)");
        sb.AppendLine($"            => {target}.AddCqrsGenerated(services);");

        if (known.HasPipelinesBuilder)
        {
            sb.AppendLine();
            EmitBuilderSummary(sb);
            sb.AppendLine($"        internal static {ServiceCollection} AddCqrsGenerated(this {ServiceCollection} services, global::System.Action<global::CQRSharp.Pipelines.ICqrsBuilder> configure)");
            sb.AppendLine($"            => {target}.AddCqrsGenerated(services, configure);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitBootstrapTypeHeader(StringBuilder sb)
    {
        EmitSummary(sb, "    ", "One-call source-generated bootstrap that registers CQRSharp and its generated handlers and dispatchers together.");
        sb.AppendLine("    internal static class CqrsGeneratedBootstrap");
        sb.AppendLine("    {");
    }

    private static void EmitBuilderSummary(StringBuilder sb)
    {
        EmitSummary(sb, "        ", "Registers CQRSharp and the source-generated handlers and dispatchers, configuring options, stores and pipeline behaviors through the fluent <c>ICqrsBuilder</c>.");
        EmitServicesParam(sb);
        sb.AppendLine("        /// <param name=\"configure\">The builder configuration; the order of its verbs does not matter.</param>");
    }

    private static void EmitServicesParam(StringBuilder sb)
    {
        sb.AppendLine("        /// <param name=\"services\">The service collection to register CQRSharp into.</param>");
        sb.AppendLine("        /// <returns>The same service collection, to allow chaining.</returns>");
    }

    // Private and not an extension, so the only way in is through AddCqrsGenerated, which registers the core services
    // these registrations assume.
    private static void EmitRegisterModules(StringBuilder sb, KnownSnapshot known, bool hasLocalModule)
    {
        sb.AppendLine($"        private static void RegisterModules({ServiceCollection} services)");
        sb.AppendLine("        {");
        // The composition is last-module-wins, so this assembly's module registers after the referenced ones: a
        // request both a referenced library and the host handle is served by the host.
        foreach (var registrar in known.ReferencedModuleRegistrars)
            sb.AppendLine($"            {registrar}.Register(services);");
        if (hasLocalModule)
            sb.AppendLine($"            global::{known.ModuleNamespace}.CqrsModuleRegistrar.Register(services);");
        if (known.ReferencedClosedBehaviors.Count > 0)
            sb.AppendLine($"            {AddExtensions}.AddSingleton(services, new global::CQRSharp.Core.Pipelines.ClosedBehaviorCatalog(__referencedClosedBehaviors));");
        if (known.ReferencedClosedBehaviorGaps.Count > 0)
            sb.AppendLine($"            {AddExtensions}.AddSingleton(services, new global::CQRSharp.Core.Pipelines.ClosedBehaviorGapCatalog(__referencedClosedBehaviorGaps));");
        sb.AppendLine("            global::CQRSharp.Core.Modules.CqrsModuleComposition.AddCqrsModuleComposition(services);");
        sb.AppendLine("        }");
    }
}
