using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    /// <summary>
    ///     Emits one assembly-level marker attribute per handled request and per handled notification, so the CQRSharp
    ///     analyzers can discover handlers across referenced assemblies (not just the current compilation).
    /// </summary>
    private static string GenerateAssemblyMarkers(ImmutableArray<CandidateModel> candidates, KnownSnapshot known, bool hasModule, IReadOnlyCollection<string> suppressed)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        EmitSuppressions(sb, suppressed);
        sb.AppendLine();

        // The module marker: lets a composition root in a referencing assembly discover and wire this assembly's
        // generated module at compile time. Emitted whenever this assembly contributes a module.
        if (hasModule)
            sb.AppendLine(
                $"[assembly: global::CQRSharp.Core.SourceGeneration.CqrsGeneratedModule(typeof(global::{known.ModuleNamespace}.CqrsModuleRegistrar))]");

        var handledRequests = candidates
            .SelectMany(c => c.Handlers)
            .Select(h => h.Request.RequestTypeName)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(t => t, StringComparer.Ordinal);

        foreach (var request in handledRequests)
            sb.AppendLine($"[assembly: global::CQRSharp.Core.SourceGeneration.CqrsHandledRequest(typeof({request}))]");

        var handledNotifications = candidates
            .SelectMany(c => c.HandledNotifications)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(t => t, StringComparer.Ordinal);

        foreach (var notification in handledNotifications)
            sb.AppendLine($"[assembly: global::CQRSharp.Core.SourceGeneration.CqrsHandledNotification(typeof({notification}))]");

        // One marker per context type that has a discovered IRequestContextFactory, so CQRA011 can see factories
        // declared in referenced assemblies (the current compilation's factories are found by scanning its own source).
        var registeredContextFactories = candidates
            .SelectMany(c => c.ContextFactories)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(t => t, StringComparer.Ordinal);

        foreach (var contextType in registeredContextFactories)
            sb.AppendLine($"[assembly: global::CQRSharp.Core.SourceGeneration.CqrsRegisteredContextFactory(typeof({contextType}))]");

        return sb.ToString();
    }
}
