using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    private const string ServiceCollection = "global::Microsoft.Extensions.DependencyInjection.IServiceCollection";
    private const string ServiceDescriptor = "global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor";
    private const string TryAddExtensions = "global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions";
    private const string AddExtensions = "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions";

    // The per-assembly module: this compilation's registration data as an ICqrsModule, plus a CqrsModuleRegistrar that
    // registers it and the assembly's handler services. Emitted into a per-assembly namespace so two assemblies in one
    // reference graph never collide; the composition root merges every module (its own and each referenced assembly's).
    // Only the registrar is public: other assemblies' bootstraps call it. The module class is internal, so it is no part
    // of the assembly's public API.
    private static string GenerateModule(
        ImmutableArray<CandidateModel> candidates,
        KnownSnapshot known,
        IReadOnlyList<NotificationModel> stableNotifications,
        bool hasFingerprinter,
        IReadOnlyCollection<string> suppressed)
    {
        var handlerBindingsByRequest = HandlerBindingsByRequest(candidates);
        var routable = GetRoutableRequests(candidates);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        EmitSuppressions(sb, suppressed);
        sb.AppendLine();
        sb.AppendLine($"namespace {known.ModuleNamespace}");
        sb.AppendLine("{");

        EmitSummary(sb, "    ", "This assembly's source-generated CQRSharp module: the requests, handlers, context types, exception hooks and notifications discovered in it, as the tables a composition root merges.");
        sb.AppendLine("    internal sealed class CqrsModule : global::CQRSharp.Core.Modules.ICqrsModule");
        sb.AppendLine("    {");
        EmitRequestMetadata(sb, handlerBindingsByRequest);
        EmitHandlerInvokers(sb, handlerBindingsByRequest);
        EmitContextSources(sb, candidates, handlerBindingsByRequest);
        EmitRoutes(sb, routable);
        EmitExceptionHooks(sb, candidates);
        EmitNotificationRoutes(sb, candidates);
        EmitNotificationSubscriptions(sb, candidates);
        EmitPartitionKeySelectors(sb, stableNotifications);
        if (stableNotifications.Count > 0)
            sb.AppendLine("        private static readonly GeneratedOutboxNotificationSerializer __outboxSerializer = new GeneratedOutboxNotificationSerializer();");
        sb.AppendLine();

        EmitMember(sb, $"global::System.Collections.Generic.IReadOnlyDictionary<{TypeName}, {RequestMetadataName}>", "RequestMetadata", "__requestMetadata");
        EmitMember(sb, $"global::System.Collections.Generic.IReadOnlyDictionary<{TypeName}, global::System.Delegate>", "HandlerInvokers", "__handlerInvokers");
        EmitMember(sb, $"global::System.Collections.Generic.IReadOnlyDictionary<{TypeName}, global::CQRSharp.Core.Registries.RequestContextSource>", "ContextSources", "__contextSources");
        EmitMember(sb, $"global::System.Collections.Generic.IReadOnlyDictionary<{TypeName}, global::CQRSharp.Core.Pipelines.RequestRoute>", "RequestRoutes", "__requestRoutes");
        EmitMember(sb, $"global::System.Collections.Generic.IReadOnlyDictionary<{TypeName}, global::CQRSharp.Core.Pipelines.StreamRoute>", "StreamRoutes", "__streamRoutes");
        EmitMember(sb, "global::System.Collections.Generic.IReadOnlyList<global::CQRSharp.Core.Exceptions.RequestExceptionHook>", "ExceptionHooks", "__exceptionHooks");
        EmitMember(sb, $"global::System.Collections.Generic.IReadOnlyDictionary<{TypeName}, global::CQRSharp.Core.Notifications.NotificationRoute>", "NotificationRoutes", "__notificationRoutes");
        EmitMember(sb, "global::System.Collections.Generic.IReadOnlyList<global::CQRSharp.Core.Notifications.NotificationSubscription>", "NotificationSubscriptions", "__notificationSubscriptions");
        EmitMember(sb, $"global::System.Collections.Generic.IReadOnlyDictionary<{TypeName}, global::System.Func<global::CQRSharp.INotification, string?>>", "PartitionKeySelectors", "__partitionKeySelectors");
        EmitMember(sb, "global::CQRSharp.Persistence.INotificationSerializer?", "OutboxSerializer", stableNotifications.Count > 0 ? "__outboxSerializer" : "null");
        EmitMember(sb, "global::CQRSharp.Core.Idempotency.IRequestFingerprinter?", "RequestFingerprinter", hasFingerprinter ? "GeneratedRequestFingerprinter.Instance" : "null");
        sb.AppendLine("    }");
        sb.AppendLine();

        EmitRegistrar(sb, candidates, routable);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitMember(StringBuilder sb, string type, string name, string value)
    {
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine($"        public {type} {name} => {value};");
    }

    private static void EmitRegistrar(StringBuilder sb, ImmutableArray<CandidateModel> candidates, List<RequestModel> routable)
    {
        EmitSummary(sb, "    ", "Registers this assembly's <see cref=\"CqrsModule\" /> (its handler services plus the module itself) so a composition root can compose it. Named by the assembly-level <c>[CqrsGeneratedModule]</c> marker; called by generated bootstrap code only.");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static class CqrsModuleRegistrar");
        sb.AppendLine("    {");
        var closedBehaviors = routable.SelectMany(r => r.ClosedBehaviors)
            .Concat(candidates.SelectMany(c => c.NotificationClosedBehaviors))
            .Distinct()
            .ToArray();
        var closedBehaviorGaps = routable.SelectMany(r => r.ClosedBehaviorGaps)
            .Concat(candidates.SelectMany(c => c.NotificationClosedBehaviorGaps))
            .Distinct()
            .ToArray();
        if (closedBehaviors.Length > 0 || closedBehaviorGaps.Length > 0)
        {
            sb.AppendLine("        // The behaviors of each request whose result (or streamed item) is a value type and of each value-type");
            sb.AppendLine("        // notification, closed here because the container cannot close an open-generic registration over a value");
            sb.AppendLine("        // type without dynamic code (Native AOT), and the ones that apply but that this code cannot close: the gaps a");
            sb.AppendLine("        // registration of such a behavior is checked against, so it is refused rather than silently left out.");
            EmitClosedBehaviorCatalogs(sb, "        ", closedBehaviors, closedBehaviorGaps, "__closedBehaviors", "__closedBehaviorGaps");
            sb.AppendLine();
        }

        EmitSummary(sb, "        ", "Registers this assembly's handler services and its module contribution. Idempotent: a second call on the same collection (a library's own AddCqrsGenerated plus its host's) is a no-op, so handlers are never registered - and notifications never handled - twice.");
        sb.AppendLine("        /// <param name=\"services\">The service collection to register into.</param>");
        sb.AppendLine($"        public static void Register({ServiceCollection} services)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (services is null) throw new global::System.ArgumentNullException(nameof(services));");
        sb.AppendLine();
        sb.AppendLine("            // The module descriptor is added last, so its presence means this registrar already ran.");
        sb.AppendLine("            foreach (var descriptor in services)");
        sb.AppendLine("                if (descriptor.ServiceType == typeof(global::CQRSharp.Core.Modules.ICqrsModule) && descriptor.ImplementationType == typeof(CqrsModule))");
        sb.AppendLine("                    return;");
        EmitHandlerServices(sb, candidates);
        sb.AppendLine();
        if (closedBehaviors.Length > 0)
            sb.AppendLine($"            {AddExtensions}.AddSingleton(services, new global::CQRSharp.Core.Pipelines.ClosedBehaviorCatalog(__closedBehaviors));");
        if (closedBehaviorGaps.Length > 0)
            sb.AppendLine($"            {AddExtensions}.AddSingleton(services, new global::CQRSharp.Core.Pipelines.ClosedBehaviorGapCatalog(__closedBehaviorGaps));");
        sb.AppendLine($"            {TryAddExtensions}.TryAddEnumerable(services, {ServiceDescriptor}.Singleton<global::CQRSharp.Core.Modules.ICqrsModule, CqrsModule>());");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    /// <summary>
    ///     Emits the closed-behavior factories and the gaps as static arrays, each only when it has an entry (an unread
    ///     private field would warn). The diagnostics naming an [Obsolete] or [Experimental] behavior raises are suppressed
    ///     for the whole file (<see cref="EmitSuppressions" />); a factory that closes a <c>notnull</c> type parameter over a
    ///     nullable value type suppresses CS8714 for itself alone. Shared by the module registrar and the bootstrap, which
    ///     closes the host's behaviors over the referenced assemblies' requests.
    /// </summary>
    private static void EmitClosedBehaviorCatalogs(
        StringBuilder sb,
        string indent,
        IReadOnlyCollection<ClosedBehaviorModel> closedBehaviors,
        IReadOnlyCollection<ClosedBehaviorGapModel> gaps,
        string factoriesField,
        string gapsField)
    {
        if (closedBehaviors.Count > 0)
        {
            sb.AppendLine($"{indent}private static readonly global::CQRSharp.Core.Pipelines.ClosedBehaviorFactory[] {factoriesField} =");
            sb.AppendLine($"{indent}{{");
            foreach (var closed in closedBehaviors)
            {
                // The container ignores notnull, so the behavior applies to the nullable value type at runtime too; only the
                // compiler's nullability check on the closing needs silencing.
                if (closed.RelaxesNotNull) sb.AppendLine("#pragma warning disable CS8714");
                sb.AppendLine(
                    $"{indent}    new global::CQRSharp.Core.Pipelines.ClosedBehaviorFactory(typeof({closed.OpenTypeName}), typeof({closed.ServiceTypeName}), " +
                    $"static sp => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<{closed.ClosedTypeName}>(sp)),");
                if (closed.RelaxesNotNull) sb.AppendLine("#pragma warning restore CS8714");
            }

            sb.AppendLine($"{indent}}};");
        }

        if (gaps.Count > 0)
        {
            if (closedBehaviors.Count > 0) sb.AppendLine();
            sb.AppendLine($"{indent}private static readonly global::CQRSharp.Core.Pipelines.ClosedBehaviorGap[] {gapsField} =");
            sb.AppendLine($"{indent}{{");
            foreach (var gap in gaps)
            {
                var behavior = $"{Literal(gap.BehaviorRuntimeName)}, {Literal(gap.BehaviorAssemblyName)}, {Literal(gap.Reason)}";
                sb.AppendLine(gap.ServiceTypeName is not null
                    ? $"{indent}    new global::CQRSharp.Core.Pipelines.ClosedBehaviorGap(typeof({gap.ServiceTypeName}), {behavior}),"
                    : $"{indent}    new global::CQRSharp.Core.Pipelines.ClosedBehaviorGap(typeof({gap.ServiceDefinitionName}), {Literal(gap.TargetRuntimeName)}, {Literal(gap.TargetAssemblyName)}, {behavior}),");
            }

            sb.AppendLine($"{indent}}};");
        }

        static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
    }

    private static void EmitHandlerServices(StringBuilder sb, ImmutableArray<CandidateModel> candidates)
    {
        sb.AppendLine();
        sb.AppendLine("            // Every handler is registered by its concrete type. Request handlers are dispatched by that type (their");
        sb.AppendLine("            // metadata names it), and so are notification handlers (their subscriptions resolve it), which is why a");
        sb.AppendLine("            // notification handler gets no INotificationHandler<T> registration: the container's INotificationHandler<T>");
        sb.AppendLine("            // registrations are the application's own. Validators, exception hooks and closed pipeline behaviors are");
        sb.AppendLine("            // registered under their interface with the discovered-services key, which keeps them out of the");
        sb.AppendLine("            // application's own registrations: where they are consumed the two are merged, and one the application");
        sb.AppendLine("            // registers itself runs once, as its own. Request handlers get one forwarder per interface. TryAdd: a");
        sb.AppendLine("            // lifetime the consumer chose for a handler stands, and an interface registration it made first is not duplicated.");

        // A request context factory is registered under the factory interface it implements, so a declared factory is a
        // registered one (as the docs and CQRA011 say). Core places it: an application's own registration wins, and a
        // later module's discovered factory (the composition root's) replaces an earlier module's.
        foreach (var candidate in candidates.Where(c => c.RegistersContextFactories))
        foreach (var contextType in candidate.ContextFactories)
            sb.AppendLine($"            global::CQRSharp.Core.Registries.DiscoveredContextFactories.Register<{contextType}, {candidate.TypeName}>(services);");

        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var candidate in candidates)
        {
            if (candidate.HandlerForwarderInterfaces.Count == 0 && candidate.DiscoveredServiceInterfaces.Count == 0 &&
                candidate.HandledNotifications.Count == 0) continue;
            if (!seen.Add(candidate.TypeName)) continue;

            sb.AppendLine($"            {TryAddExtensions}.TryAddTransient(services, typeof({candidate.TypeName}));");

            foreach (var iface in candidate.HandlerForwarderInterfaces)
                sb.AppendLine(
                    $"            {TryAddExtensions}.TryAddEnumerable(services, {ServiceDescriptor}.Transient<{iface}, {candidate.TypeName}>(" +
                    $"static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{candidate.TypeName}>(sp)));");

            foreach (var iface in candidate.DiscoveredServiceInterfaces)
                sb.AppendLine(
                    $"            {TryAddExtensions}.TryAddEnumerable(services, {ServiceDescriptor}.KeyedTransient<{iface}, {candidate.TypeName}>(" +
                    $"global::CQRSharp.Core.Modules.DiscoveredServices.Key, " +
                    $"static (sp, _) => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{candidate.TypeName}>(sp)));");
        }
    }

    /// <summary>
    ///     What every generated file that names consumer types suppresses: the compiler's obsolete warnings, and the ids
    ///     naming the consumer types, and the behaviors closed over them, raises ([Obsolete] DiagnosticIds, [Experimental]).
    ///     Once for the whole file: a disable/restore pair around each use would restore what the file already disabled.
    /// </summary>
    private static string[] GeneratedFileSuppressions(ImmutableArray<CandidateModel> candidates)
        => GeneratedCodeSuppressions.CompilerObsoleteIds
            .Concat(candidates.SelectMany(c => c.SuppressedWarnings))
            .Concat(candidates.SelectMany(c => c.NotificationClosedBehaviors).SelectMany(b => b.SuppressedWarnings))
            .Concat(candidates.Where(c => c.Request is not null).SelectMany(c => c.Request!.ClosedBehaviors).SelectMany(b => b.SuppressedWarnings))
            .Concat(candidates.SelectMany(c => c.Handlers).SelectMany(h => h.Request.ClosedBehaviors).SelectMany(b => b.SuppressedWarnings))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(id => id, StringComparer.Ordinal)
            .ToArray();

    private static void EmitSuppressions(StringBuilder sb, IReadOnlyCollection<string> ids)
    {
        if (ids.Count > 0) sb.AppendLine("#pragma warning disable " + string.Join(", ", ids));
    }
}
