using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    // The payload fingerprint of an idempotent request: its properties rendered to JSON with the outbox serializer's
    // write helpers (so a Guid, a date, a nested object or a collection render the same way everywhere), then hashed
    // with SHA-256. Canonical, so equal payloads hash alike: dictionary entries in key order, set elements in a fixed
    // order. Write-only: nothing here ever deserializes.
    private static string GenerateRequestFingerprinter(IReadOnlyList<FingerprintModel> fingerprints, KnownSnapshot known, IReadOnlyCollection<string> suppressed)
    {
        var helpers = new OutboxHelpers();
        foreach (var fingerprint in fingerprints)
            helpers.Collect(fingerprint.Root!);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine(NullabilityPragma);
        EmitSuppressions(sb, suppressed);
        sb.AppendLine();
        sb.AppendLine($"namespace {known.ModuleNamespace}");
        sb.AppendLine("{");
        EmitSummary(sb, "    ", "Source-generated, AOT-safe payload fingerprints for this assembly's idempotent requests: a SHA-256 over the request's properties rendered as JSON.");
        sb.AppendLine("    internal sealed class GeneratedRequestFingerprinter : global::CQRSharp.Core.Idempotency.IRequestFingerprinter");
        sb.AppendLine("    {");
        sb.AppendLine("        internal static readonly GeneratedRequestFingerprinter Instance = new();");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Computes the fingerprint of a request whose exact type this assembly declares.");
        sb.AppendLine("        public bool TryFingerprint(global::CQRSharp.IRequest request, out string fingerprint)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine("            var type = request.GetType();");
        foreach (var fingerprint in fingerprints)
        {
            var typeLiteral = SymbolDisplay.FormatLiteral(fingerprint.TypeName.Replace("global::", string.Empty), quote: true);
            sb.AppendLine(
                $"            if (type == typeof({fingerprint.TypeName})) {{ fingerprint = Hash({typeLiteral}, ({fingerprint.TypeName})request, " +
                $"static (writer, value) => WriteObj_{fingerprint.Root!.HelperId}(writer, value)); return true; }}");
        }

        sb.AppendLine("            fingerprint = string.Empty;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // The request's type name is part of the hash: two request types of the same shape (CancelOrder and ShipOrder,");
        sb.AppendLine("        // both an order id) sent under one key must read as a payload mismatch, not as a replay of each other.");
        sb.AppendLine($"        private static string Hash<T>(string requestType, T value, global::System.Action<{JsonWriter}, T> write)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var buffer = new {ByteBuffer}();");
        sb.AppendLine($"            using (var writer = new {JsonWriter}(buffer))");
        sb.AppendLine("            {");
        sb.AppendLine("                writer.WriteStartObject();");
        sb.AppendLine("                writer.WriteString(\"$type\", requestType);");
        sb.AppendLine("                writer.WritePropertyName(\"$payload\");");
        sb.AppendLine("                write(writer, value);");
        sb.AppendLine("                writer.WriteEndObject();");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return global::System.Convert.ToHexString(global::System.Security.Cryptography.SHA256.HashData(buffer.WrittenSpan));");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var obj in helpers.Objects)
        {
            GenerateWriteObject(sb, obj, canonical: true);
            sb.AppendLine();
        }

        foreach (var element in helpers.CollectionElements)
        {
            GenerateWriteCollection(sb, element, canonical: true);
            sb.AppendLine();
        }

        foreach (var element in helpers.SetElements)
        {
            GenerateWriteCanonicalSet(sb, element);
            sb.AppendLine();
        }

        foreach (var value in helpers.DictionaryValues)
        {
            GenerateWriteDictionary(sb, value, canonical: true);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
