using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CQRSharp.EntityFrameworkCore.Persistence;

/// <summary>
///     The EF Core mapping for <see cref="IdempotencyEntity" />. Apply it from your <c>DbContext.OnModelCreating</c>
///     (e.g. <c>modelBuilder.ApplyConfiguration(new IdempotencyEntityConfiguration())</c>) so the idempotency table is
///     created alongside your own entities.
/// </summary>
public sealed class IdempotencyEntityConfiguration : IEntityTypeConfiguration<IdempotencyEntity>
{
    // Bounds the relational key-column length. Keeping keys within this length is what makes them portable across
    // relational backends, and keeps the column index-friendly (and the primary key within size limits) on providers
    // (e.g. SQL Server) that cannot index unbounded text columns. A caller with longer keys should hash them down
    // before claiming rather than rely on a backend that happens to tolerate them.
    private const int KeyMaxLength = 512;

    // SQLite (and some other providers) store DateTime without a Kind, so a value read back is Unspecified. The store
    // compares ExpiresAt against TimeProvider.GetUtcNow() (a UTC DateTime), so coerce the persisted value to UTC on the
    // way in and re-stamp Utc on the way out to keep every comparison in one consistent kind.
    private static readonly ValueConverter<DateTime, DateTime> UtcConverter = new(
        v => v.Kind == DateTimeKind.Utc ? v : v.ToUniversalTime(),
        v => DateTime.SpecifyKind(v, DateTimeKind.Utc));

    /// <summary>Maps <see cref="IdempotencyEntity" />: table, the Key string primary key, bounded key length, concurrency token, and UTC coercion.</summary>
    public void Configure(EntityTypeBuilder<IdempotencyEntity> builder)
    {
        builder.ToTable("CqrsIdempotencyKeys");

        // The Key is the caller-supplied idempotency key, never generated by the database.
        // KeyMaxLength bounds the relational key length so the column is index-friendly (and the primary key fits)
        // on providers (e.g. SQL Server) that cannot index unbounded text. Note that key comparison is the column's
        // collation, NOT the store's: a case-INSENSITIVE database collation (such as SQL Server's default) folds case
        // here, so two keys differing only by case collide and the case-variant is wrongly rejected as a duplicate.
        // The store contract is ordinal/case-sensitive; a consumer who needs that exact semantics on a case-folding
        // provider should apply a binary/case-sensitive collation to this column (not pinned here, as a provider-
        // specific collation would not be portable to other backends).
        builder.HasKey(e => e.Key);
        builder.Property(e => e.Key).ValueGeneratedNever().HasMaxLength(KeyMaxLength);

        builder.Property(e => e.ExpiresAt).HasConversion(UtcConverter);

        // Optimistic concurrency for the expired-row take-over. We use the same manual uint token the store
        // increments itself rather than a provider-native rowversion column, because native rowversion semantics
        // differ across providers (SQL Server: real 8-byte timestamp; SQLite/PostgreSQL: no equivalent). IsRowVersion
        // marks it as the concurrency token, but it also defaults the column to store-generated (OnAddOrUpdate);
        // SQLite has no generator for it, so we override generation to Never and write the value ourselves. A plain
        // incremented integer concurrency token works uniformly on every relational provider, which is all the
        // take-over race needs (a fresh INSERT is guarded by the unique primary key instead).
        builder.Property(e => e.RowVersion).IsRowVersion().IsConcurrencyToken().ValueGeneratedNever();
    }
}
