using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    private static readonly DiagnosticDescriptor MissingRequestHandlerDiagnostic = new(
        "CQRGEN003",
        "No handler found for request",
        "No handler found for request '{0}'. Add exactly one handler or suppress this warning if the handler is in another assembly.",
        "CQRSharp.Generators",
        DiagnosticSeverity.Warning,
        true);

    private static readonly DiagnosticDescriptor MultipleRequestHandlersDiagnostic = new(
        "CQRGEN004",
        "Multiple handlers found for request",
        "Multiple handlers found for request '{0}': {1}. CQRSharp requires exactly one handler per request.",
        "CQRSharp.Generators",
        DiagnosticSeverity.Error,
        true);

    // Whether this compilation has anything to register — i.e. whether a per-assembly module should be emitted.
    private static bool HasModuleContent(ImmutableArray<CandidateModel> candidates)
    {
        foreach (var candidate in candidates)
            if (candidate.Handlers.Count > 0 ||
                candidate.Request is not null ||
                candidate.Notification is not null ||
                candidate.HandledNotifications.Count > 0 ||
                candidate.ContextFactories.Count > 0 ||
                candidate.ExceptionHooks.Count > 0)
                return true;

        return false;
    }

    // The per-assembly module: this compilation's compile-time registration data (the four registry maps + the typed
    // dispatch surface) wrapped as an ICqrsModule, plus a CqrsModuleRegistrar that registers it additively. Emitted
    // into a per-assembly namespace so two assemblies in one reference graph never collide; a composition root merges
    // every module (its own and each referenced assembly's) into the single framework services.
    private static string GenerateModule(
        ImmutableArray<CandidateModel> candidates,
        KnownSnapshot known,
        IReadOnlyList<NotificationModel> stableNotifications,
        SourceProductionContext context,
        GeneratorConfig config)
    {
        var handlerBindingsByRequest = candidates
            .SelectMany(c => c.Handlers)
            .GroupBy(h => h.RequestTypeName, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.ToList(), StringComparer.Ordinal);

        var requestTypes = candidates
            .Where(c => c.Request is { Kind: RequestKind.Command or RequestKind.Query })
            .Select(c => c.Request!.RequestTypeName)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();
        var streamTypes = candidates
            .Where(c => c.Request is { Kind: RequestKind.Stream })
            .Select(c => c.Request!.RequestTypeName)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();
        var notificationTypes = candidates
            .Where(c => c.Notification is not null)
            .Select(c => c.Notification!.TypeName)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();
        var handledNotificationTypes = candidates
            .SelectMany(c => c.HandledNotifications)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();
        var stableTypes = stableNotifications.Select(n => n.TypeName).ToArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Notifications;");
        sb.AppendLine("using CQRSharp.Abstractions.Models.Requests;");
        sb.AppendLine("using CQRSharp.Core.Caching.Requests;");
        sb.AppendLine("using CQRSharp.Core.Caching.Handlers;");
        sb.AppendLine("using CQRSharp.Core.Caching.Contexts;");
        sb.AppendLine("using CQRSharp.Core.Diagnostics;");
        sb.AppendLine("using CQRSharp.Core.Factories;");
        sb.AppendLine("using CQRSharp.Core.Modules;");
        sb.AppendLine("using CQRSharp.Core.Notifications;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine();
        sb.AppendLine($"namespace {known.ModuleNamespace}");
        sb.AppendLine("{");

        EmitSummary(sb, "    ", "This assembly's source-generated CQRSharp module: its compile-time-discovered handlers, request bindings, context factories, exception hooks, and AOT-safe dispatch surface, exposed for a composition root to merge.");
        sb.AppendLine("    public sealed class CqrsModule : global::CQRSharp.Core.Modules.ICqrsModule");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly ConcurrentDictionary<Type, global::CQRSharp.Abstractions.Models.Requests.RequestMetadata> __requestMetadata = __BuildRequestMetadata();");
        sb.AppendLine("        private static readonly ConcurrentDictionary<Type, HandlerInvokerDelegate> __handlerInvokers = __BuildHandlerInvokers();");
        sb.AppendLine("        private static readonly Dictionary<Type, Delegate> __typedHandlerInvokers = __BuildTypedHandlerInvokers();");
        sb.AppendLine("        private static readonly ConcurrentDictionary<Type, Func<IServiceProvider, object?>> __contextFactories = __BuildContextFactories();");
        sb.AppendLine("        private static readonly ConcurrentDictionary<Type, global::CQRSharp.Core.Exceptions.RequestExceptionHookInvoker> __exceptionHooks = __BuildExceptionHooks();");
        EmitTypeArray(sb, "__requestTypes", requestTypes);
        EmitTypeArray(sb, "__streamRequestTypes", streamTypes);
        EmitTypeArray(sb, "__notificationTypes", notificationTypes);
        EmitTypeArray(sb, "__handledNotificationTypes", handledNotificationTypes);
        EmitTypeArray(sb, "__stableNotificationTypes", stableTypes);
        sb.AppendLine();
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyDictionary<Type, global::CQRSharp.Abstractions.Models.Requests.RequestMetadata> RequestMetadata => __requestMetadata;");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyDictionary<Type, HandlerInvokerDelegate> HandlerInvokers => __handlerInvokers;");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyDictionary<Type, Delegate> TypedHandlerInvokers => __typedHandlerInvokers;");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyDictionary<Type, RequestRoute> RequestRoutes => GeneratedRequestDispatcher.Routes;");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyDictionary<Type, UntypedRequestRoute> UntypedRequestRoutes => GeneratedRequestDispatcher.UntypedRoutes;");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyDictionary<Type, Func<IServiceProvider, object?>> ContextFactories => __contextFactories;");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyDictionary<Type, global::CQRSharp.Core.Exceptions.RequestExceptionHookInvoker> ExceptionHooks => __exceptionHooks;");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyList<Type> RequestTypes => __requestTypes;");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyList<Type> StreamRequestTypes => __streamRequestTypes;");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyList<Type> NotificationTypes => __notificationTypes;");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyList<Type> HandledNotificationTypes => __handledNotificationTypes;");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IReadOnlyList<Type> StableNotificationTypes => __stableNotificationTypes;");
        sb.AppendLine();
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IRequestDispatcher CreateRequestDispatcher(IPipelineExecutor pipelineExecutor) => new GeneratedRequestDispatcher(pipelineExecutor);");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IStreamRequestDispatcher CreateStreamDispatcher(IPipelineExecutor pipelineExecutor) => new GeneratedStreamRequestDispatcher(pipelineExecutor);");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public IDirectNotificationDispatcher CreateNotificationDispatcher(IServiceProvider services) => new GeneratedDirectNotificationDispatcher(services);");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public ICqrsDiagnostics CreateDiagnostics(IServiceProvider services, IRequestRegistry requestRegistry, IContextFactoryRegistry contextFactoryRegistry, ICqrsNotificationRegistry notificationRegistry) => new GeneratedCqrsDiagnostics(services, requestRegistry, contextFactoryRegistry, notificationRegistry);");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine(stableNotifications.Count > 0
            ? "        public INotificationSerializer? OutboxSerializer => new GeneratedOutboxNotificationSerializer();"
            : "        public INotificationSerializer? OutboxSerializer => null;");
        sb.AppendLine();

        sb.AppendLine("        private static ConcurrentDictionary<Type, global::CQRSharp.Abstractions.Models.Requests.RequestMetadata> __BuildRequestMetadata()");
        sb.AppendLine("        {");
        GenerateRequestRegistry(sb, candidates, known, handlerBindingsByRequest, context, config);
        sb.AppendLine("            return requestMetadataMappings;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static ConcurrentDictionary<Type, HandlerInvokerDelegate> __BuildHandlerInvokers()");
        sb.AppendLine("        {");
        GenerateHandlerRegistry(sb, handlerBindingsByRequest);
        sb.AppendLine("            return handlerInvokerMappings;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static Dictionary<Type, Delegate> __BuildTypedHandlerInvokers()");
        sb.AppendLine("        {");
        GenerateTypedHandlerRegistry(sb, handlerBindingsByRequest, known);
        sb.AppendLine("            return typedInvokerMappings;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static ConcurrentDictionary<Type, Func<IServiceProvider, object?>> __BuildContextFactories()");
        sb.AppendLine("        {");
        GenerateContextFactoryRegistry(sb, candidates, known);
        sb.AppendLine("            return factoryMappings;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static ConcurrentDictionary<Type, global::CQRSharp.Core.Exceptions.RequestExceptionHookInvoker> __BuildExceptionHooks()");
        sb.AppendLine("        {");
        GenerateRequestExceptionHookRegistry(sb, candidates);
        sb.AppendLine("            return exceptionHookMappings;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        EmitSummary(sb, "    ", "Registers this assembly's <see cref=\"CqrsModule\" /> (its handler services plus the module itself) so a composition root can compose it. Named by the assembly-level <c>[CqrsGeneratedModule]</c> marker.");
        sb.AppendLine("    public static class CqrsModuleRegistrar");
        sb.AppendLine("    {");
        EmitSummary(sb, "        ", "Registers this assembly's handler services and its module contribution. Idempotent: a second call on the same collection (a library's own AddCqrsGenerated plus its host's) is a no-op, so handlers are never registered — and notifications never handled — twice.");
        sb.AppendLine("        public static void Register(IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (services is null) throw new ArgumentNullException(nameof(services));");
        sb.AppendLine();
        sb.AppendLine("            // The module descriptor is added last, so its presence means this registrar already ran.");
        sb.AppendLine("            foreach (var descriptor in services)");
        sb.AppendLine("                if (descriptor.ServiceType == typeof(global::CQRSharp.Core.Modules.ICqrsModule) && descriptor.ImplementationType == typeof(CqrsModule))");
        sb.AppendLine("                    return;");
        GenerateHandlerServices(sb, candidates);
        sb.AppendLine();
        sb.AppendLine("            services.TryAddEnumerable(ServiceDescriptor.Singleton<global::CQRSharp.Core.Modules.ICqrsModule, CqrsModule>());");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitTypeArray(StringBuilder sb, string fieldName, string[] typeNames)
    {
        if (typeNames.Length == 0)
        {
            sb.AppendLine($"        private static readonly Type[] {fieldName} = System.Array.Empty<Type>();");
            return;
        }

        sb.AppendLine($"        private static readonly Type[] {fieldName} = new Type[]");
        sb.AppendLine("        {");
        foreach (var typeName in typeNames)
            sb.AppendLine($"            typeof({typeName}),");
        sb.AppendLine("        };");
    }

    private static HandlerImplModel SelectDeterministicBinding(List<HandlerImplModel> bindings)
    {
        return bindings
            .OrderBy(b => b.ImplTypeName, StringComparer.Ordinal)
            .ThenBy(b => b.InterfaceNameOrdinal, StringComparer.Ordinal)
            .First();
    }

    private static void GenerateHandlerServices(StringBuilder sb, ImmutableArray<CandidateModel> candidates)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Handler Services by Interface Implementation.");
        sb.AppendLine("            // The concrete handler is what dispatch resolves (via the request registry); the interface");
        sb.AppendLine("            // forwarders below are kept so consumers can also resolve a handler by its interface directly.");

        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var candidate in candidates)
        {
            if (candidate.HandlerForwarderInterfaces.Count == 0) continue;
            if (!seen.Add(candidate.TypeName)) continue;

            sb.AppendLine($"            services.AddTransient(typeof({candidate.TypeName}));");

            foreach (var iface in candidate.HandlerForwarderInterfaces)
                sb.AppendLine($"            services.AddTransient(typeof({iface}), sp => sp.GetRequiredService<{candidate.TypeName}>());");
        }
    }
}
