using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    private static string GenerateDiagnostics(ImmutableArray<CandidateModel> candidates, KnownSnapshot known)
    {
        var requests = candidates
            .Where(c => c.Request is not null)
            .Select(c => c.Request!)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using CQRSharp.Abstractions.Attributes.Pipelines;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Context;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Markers.Command;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Markers.Query;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Markers.Request;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Markers.Stream;");
        sb.AppendLine("using CQRSharp.Abstractions.Models.Commands;");
        sb.AppendLine("using CQRSharp.Abstractions.Models.Requests;");
        sb.AppendLine("using CQRSharp.Core.Caching.Contexts;");
        sb.AppendLine("using CQRSharp.Core.Caching.Requests;");
        sb.AppendLine("using CQRSharp.Core.Diagnostics;");
        sb.AppendLine("using CQRSharp.Core.Factories;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine();
        sb.AppendLine($"namespace {known.ModuleNamespace}");
        sb.AppendLine("{");
        EmitSummary(sb, "    ", "Source-generated, AOT-safe <c>ICqrsDiagnostics</c> that describes this assembly's request bindings and overall configuration.");
        sb.AppendLine("    public sealed class GeneratedCqrsDiagnostics(");
        sb.AppendLine("        IServiceProvider services,");
        sb.AppendLine("        IRequestRegistry requestRegistry,");
        sb.AppendLine("        IContextFactoryRegistry contextFactoryRegistry,");
        sb.AppendLine("        ICqrsNotificationRegistry notificationRegistry) : ICqrsDiagnostics");
        sb.AppendLine("    {");
        sb.AppendLine("        private const int DefaultBehaviorPriority = int.MaxValue / 2;");
        sb.AppendLine("        private readonly IServiceProvider _services = services;");
        sb.AppendLine("        private readonly IRequestRegistry _requestRegistry = requestRegistry;");
        sb.AppendLine("        private readonly IContextFactoryRegistry _contextFactoryRegistry = contextFactoryRegistry;");
        sb.AppendLine("        private readonly ICqrsNotificationRegistry _notificationRegistry = notificationRegistry;");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Inspects the resolved CQRSharp configuration and returns any binding issues that were detected.");
        sb.AppendLine("        public IReadOnlyList<CqrsBindingIssue> DescribeConfiguration()");
        sb.AppendLine("        {");
        sb.AppendLine("            var outbox = _services.GetService<IOptions<CQRSharp.Core.Options.OutboxOptions>>()?.Value ?? new();");
        sb.AppendLine("            var dispatcher = _services.GetService<IOptions<CQRSharp.Core.Options.DispatcherOptions>>()?.Value ?? new();");
        sb.AppendLine("            return CQRSharp.Core.Diagnostics.CqrsConfigurationInspector.Inspect(");
        sb.AppendLine("                _services, outbox, dispatcher, DescribeAllRequests(), _notificationRegistry);");
        sb.AppendLine("        }");
        sb.AppendLine();

        EmitSummary(sb, "        ", "Attempts to describe the binding (handler, context, and pipeline) for the given request type.");
        sb.AppendLine("        public bool TryDescribeRequest(Type requestType, out CqrsRequestBinding binding)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(requestType);");
        sb.AppendLine();
        sb.AppendLine("            binding = default!;");
        sb.AppendLine();
        sb.AppendLine("            // NOTE: These bindings are source-generated and AOT-safe.");

        foreach (var request in requests)
        {
            var requestName = request.RequestTypeNameNullable;
            sb.AppendLine($"            if (requestType == typeof({requestName}))");
            sb.AppendLine("            {");
            if (request.Kind == RequestKind.Stream)
                sb.AppendLine($"                binding = DescribeStream<{requestName}, {request.ResultOrItemNullable}>();");
            else if (request.Kind == RequestKind.Query)
                sb.AppendLine($"                binding = Describe<{requestName}, {request.ResultOrItemNullable}>();");
            else
                sb.AppendLine(
                    $"                binding = Describe<{requestName}, global::CQRSharp.Abstractions.Models.Commands.CommandResult>();");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();

        EmitSummary(sb, "        ", "Describes the binding for the given request type, throwing if it is not registered.");
        sb.AppendLine("        public CqrsRequestBinding DescribeRequest(Type requestType)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (TryDescribeRequest(requestType, out var binding))");
        sb.AppendLine("                return binding;");
        sb.AppendLine();
        sb.AppendLine(
            "            throw new InvalidOperationException($\"Unknown request type '{requestType.FullName}'. Ensure it is included in the source-generated registry.\");");
        sb.AppendLine("        }");
        sb.AppendLine();

        EmitSummary(sb, "        ", "Describes the bindings for every source-generated request type.");
        sb.AppendLine("        public IReadOnlyList<CqrsRequestBinding> DescribeAllRequests()");
        sb.AppendLine("        {");
        sb.AppendLine("            var list = new List<CqrsRequestBinding>();");

        foreach (var request in requests)
        {
            var requestName = request.RequestTypeNameNullable;
            if (request.Kind == RequestKind.Stream)
                sb.AppendLine($"            list.Add(DescribeStream<{requestName}, {request.ResultOrItemNullable}>());");
            else if (request.Kind == RequestKind.Query)
                sb.AppendLine($"            list.Add(Describe<{requestName}, {request.ResultOrItemNullable}>());");
            else
                sb.AppendLine(
                    $"            list.Add(Describe<{requestName}, global::CQRSharp.Abstractions.Models.Commands.CommandResult>());");
        }

        sb.AppendLine("            return list;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private CqrsRequestBinding Describe<TRequest, TResult>()");
        sb.AppendLine("            where TRequest : IRequest<TResult>");
        sb.AppendLine("        {");
        sb.AppendLine("            var issues = new List<CqrsBindingIssue>();");
        sb.AppendLine();
        sb.AppendLine("            RequestMetadata? metadata = null;");
        sb.AppendLine("            if (!_requestRegistry.TryGetRequestMetadata(typeof(TRequest), out metadata) || metadata is null)");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                issues.Add(new CqrsBindingIssue(CqrsBindingIssueSeverity.Error, \"CQRDIAG001\", $\"No request metadata registered for '{typeof(TRequest).FullName}'.\"));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var handlerType = metadata?.HandlerType;");
        sb.AppendLine("            if (handlerType is null)");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                issues.Add(new CqrsBindingIssue(CqrsBindingIssueSeverity.Error, \"CQRDIAG002\", $\"No handler type registered for '{typeof(TRequest).FullName}'.\"));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var contextType = metadata?.ContextType ?? typeof(RequestContextBase);");
        sb.AppendLine();
        sb.AppendLine("            var contextFactoryFaulted = false;");
        sb.AppendLine("            IInternalRequestContextFactory? contextFactory = null;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                contextFactory = _contextFactoryRegistry.TryGetFactory(contextType, _services) as IInternalRequestContextFactory;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                contextFactoryFaulted = true;");
        sb.AppendLine(
            "                issues.Add(new CqrsBindingIssue(CqrsBindingIssueSeverity.Error, \"CQRDIAG003\", $\"Failed to resolve context factory for context type '{contextType.FullName}': {ex.Message}\"));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (contextFactory is null && !contextFactoryFaulted)");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                issues.Add(new CqrsBindingIssue(CqrsBindingIssueSeverity.Error, \"CQRDIAG003\", $\"No context factory registered for context type '{contextType.FullName}'.\"));");
        sb.AppendLine("            }");
        sb.AppendLine();

        sb.AppendLine("            var pipelineExemptions = metadata?.PipelineExemptions.Select(x => x.ExemptedPipeline).ToArray() ?? Array.Empty<Type>();");

        sb.AppendLine("            var preHandlers = metadata?.PreHandlers ?? Array.Empty<IPreHandlerAttribute>();");
        sb.AppendLine("            var preBindings = preHandlers.Length == 0 ? Array.Empty<CqrsInterceptorBinding>() : preHandlers");
        sb.AppendLine("                .OrderBy(x => x.PreHandlerExecutionPriority)");
        sb.AppendLine("                .ThenBy(x => x.GetType().FullName, StringComparer.Ordinal)");
        sb.AppendLine("                .Select(x => new CqrsInterceptorBinding(x.GetType(), x.PreHandlerExecutionPriority))");
        sb.AppendLine("                .ToArray();");
        sb.AppendLine();
        sb.AppendLine("            var postHandlers = metadata?.PostHandlers ?? Array.Empty<IPostHandlerAttribute>();");
        sb.AppendLine("            var postBindings = postHandlers.Length == 0 ? Array.Empty<CqrsInterceptorBinding>() : postHandlers");
        sb.AppendLine("                .OrderBy(x => x.PostHandlerExecutionPriority)");
        sb.AppendLine("                .ThenBy(x => x.GetType().FullName, StringComparer.Ordinal)");
        sb.AppendLine("                .Select(x => new CqrsInterceptorBinding(x.GetType(), x.PostHandlerExecutionPriority))");
        sb.AppendLine("                .ToArray();");
        sb.AppendLine();

        sb.AppendLine("            IPipelineBehavior<TRequest, TResult>[] behaviors;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var resolved = _services.GetServices<IPipelineBehavior<TRequest, TResult>>();");
        sb.AppendLine("                behaviors = resolved as IPipelineBehavior<TRequest, TResult>[] ?? resolved.ToArray();");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                issues.Add(new CqrsBindingIssue(CqrsBindingIssueSeverity.Error, \"CQRDIAG004\", $\"Failed to resolve pipeline behaviors for '{typeof(TRequest).FullName}': {ex.Message}\"));");
        sb.AppendLine("                behaviors = Array.Empty<IPipelineBehavior<TRequest, TResult>>();");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var pipeline = new List<CqrsPipelineBehaviorBinding>(behaviors.Length);");
        sb.AppendLine("            var exemptedPipeline = new List<CqrsPipelineBehaviorBinding>();");
        sb.AppendLine();
        sb.AppendLine("            for (var i = 0; i < behaviors.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                var behavior = behaviors[i];");
        sb.AppendLine("                var type = behavior.GetType();");
        sb.AppendLine(
            "                var priority = behavior is IPrioritizedPipelineBehavior p ? p.PipelineExecutionPriority : DefaultBehaviorPriority;");
        sb.AppendLine("                var isExempted = IsExempted(type, pipelineExemptions);");
        sb.AppendLine("                var binding = new CqrsPipelineBehaviorBinding(type, priority, isExempted);");
        sb.AppendLine("                if (isExempted) exemptedPipeline.Add(binding); else pipeline.Add(binding);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            pipeline.Sort(PipelineBindingComparer.Instance);");
        sb.AppendLine("            exemptedPipeline.Sort(PipelineBindingComparer.Instance);");
        sb.AppendLine();
        sb.AppendLine("            return new CqrsRequestBinding(");
        sb.AppendLine("                typeof(TRequest),");
        sb.AppendLine("                typeof(TResult),");
        sb.AppendLine("                handlerType,");
        sb.AppendLine("                contextType,");
        sb.AppendLine("                pipelineExemptions,");
        sb.AppendLine("                preBindings,");
        sb.AppendLine("                postBindings,");
        sb.AppendLine("                pipeline,");
        sb.AppendLine("                exemptedPipeline,");
        sb.AppendLine("                issues);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private CqrsRequestBinding DescribeStream<TRequest, TItem>()");
        sb.AppendLine("            where TRequest : IStreamRequest<TItem>");
        sb.AppendLine("        {");
        sb.AppendLine("            var issues = new List<CqrsBindingIssue>();");
        sb.AppendLine();
        sb.AppendLine("            RequestMetadata? metadata = null;");
        sb.AppendLine("            if (!_requestRegistry.TryGetRequestMetadata(typeof(TRequest), out metadata) || metadata is null)");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                issues.Add(new CqrsBindingIssue(CqrsBindingIssueSeverity.Error, \"CQRDIAG001\", $\"No request metadata registered for '{typeof(TRequest).FullName}'.\"));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var handlerType = metadata?.HandlerType;");
        sb.AppendLine("            if (handlerType is null)");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                issues.Add(new CqrsBindingIssue(CqrsBindingIssueSeverity.Error, \"CQRDIAG002\", $\"No handler type registered for '{typeof(TRequest).FullName}'.\"));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var contextType = metadata?.ContextType ?? typeof(RequestContextBase);");
        sb.AppendLine();
        sb.AppendLine("            var contextFactoryFaulted = false;");
        sb.AppendLine("            IInternalRequestContextFactory? contextFactory = null;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                contextFactory = _contextFactoryRegistry.TryGetFactory(contextType, _services) as IInternalRequestContextFactory;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                contextFactoryFaulted = true;");
        sb.AppendLine(
            "                issues.Add(new CqrsBindingIssue(CqrsBindingIssueSeverity.Error, \"CQRDIAG003\", $\"Failed to resolve context factory for context type '{contextType.FullName}': {ex.Message}\"));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (contextFactory is null && !contextFactoryFaulted)");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                issues.Add(new CqrsBindingIssue(CqrsBindingIssueSeverity.Error, \"CQRDIAG003\", $\"No context factory registered for context type '{contextType.FullName}'.\"));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var pipelineExemptions = metadata?.PipelineExemptions.Select(x => x.ExemptedPipeline).ToArray() ?? Array.Empty<Type>();");
        sb.AppendLine();
        sb.AppendLine("            var preHandlers = metadata?.PreHandlers ?? Array.Empty<IPreHandlerAttribute>();");
        sb.AppendLine("            var preBindings = preHandlers.Length == 0 ? Array.Empty<CqrsInterceptorBinding>() : preHandlers");
        sb.AppendLine("                .OrderBy(x => x.PreHandlerExecutionPriority)");
        sb.AppendLine("                .ThenBy(x => x.GetType().FullName, StringComparer.Ordinal)");
        sb.AppendLine("                .Select(x => new CqrsInterceptorBinding(x.GetType(), x.PreHandlerExecutionPriority))");
        sb.AppendLine("                .ToArray();");
        sb.AppendLine();
        sb.AppendLine("            var postHandlers = metadata?.PostHandlers ?? Array.Empty<IPostHandlerAttribute>();");
        sb.AppendLine("            var postBindings = postHandlers.Length == 0 ? Array.Empty<CqrsInterceptorBinding>() : postHandlers");
        sb.AppendLine("                .OrderBy(x => x.PostHandlerExecutionPriority)");
        sb.AppendLine("                .ThenBy(x => x.GetType().FullName, StringComparer.Ordinal)");
        sb.AppendLine("                .Select(x => new CqrsInterceptorBinding(x.GetType(), x.PostHandlerExecutionPriority))");
        sb.AppendLine("                .ToArray();");
        sb.AppendLine();
        sb.AppendLine("            IStreamPipelineBehavior<TRequest, TItem>[] behaviors;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var resolved = _services.GetServices<IStreamPipelineBehavior<TRequest, TItem>>();");
        sb.AppendLine("                behaviors = resolved as IStreamPipelineBehavior<TRequest, TItem>[] ?? resolved.ToArray();");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                issues.Add(new CqrsBindingIssue(CqrsBindingIssueSeverity.Error, \"CQRDIAG004\", $\"Failed to resolve stream pipeline behaviors for '{typeof(TRequest).FullName}': {ex.Message}\"));");
        sb.AppendLine("                behaviors = Array.Empty<IStreamPipelineBehavior<TRequest, TItem>>();");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var pipeline = new List<CqrsPipelineBehaviorBinding>(behaviors.Length);");
        sb.AppendLine("            var exemptedPipeline = new List<CqrsPipelineBehaviorBinding>();");
        sb.AppendLine();
        sb.AppendLine("            for (var i = 0; i < behaviors.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                var behavior = behaviors[i];");
        sb.AppendLine("                var type = behavior.GetType();");
        sb.AppendLine("                var priority = behavior is IPrioritizedPipelineBehavior p ? p.PipelineExecutionPriority : DefaultBehaviorPriority;");
        sb.AppendLine("                var isExempted = IsExempted(type, pipelineExemptions);");
        sb.AppendLine("                var binding = new CqrsPipelineBehaviorBinding(type, priority, isExempted);");
        sb.AppendLine("                if (isExempted) exemptedPipeline.Add(binding); else pipeline.Add(binding);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            pipeline.Sort(PipelineBindingComparer.Instance);");
        sb.AppendLine("            exemptedPipeline.Sort(PipelineBindingComparer.Instance);");
        sb.AppendLine();
        sb.AppendLine("            return new CqrsRequestBinding(");
        sb.AppendLine("                typeof(TRequest),");
        sb.AppendLine("                typeof(IAsyncEnumerable<TItem>),");
        sb.AppendLine("                handlerType,");
        sb.AppendLine("                contextType,");
        sb.AppendLine("                pipelineExemptions,");
        sb.AppendLine("                preBindings,");
        sb.AppendLine("                postBindings,");
        sb.AppendLine("                pipeline,");
        sb.AppendLine("                exemptedPipeline,");
        sb.AppendLine("                issues);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static bool IsExempted(Type behaviorType, IReadOnlyList<Type> exemptions)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (exemptions.Count == 0) return false;");
        sb.AppendLine();
        sb.AppendLine("            var isBehaviorGeneric = behaviorType.IsGenericType;");
        sb.AppendLine("            var behaviorDef = isBehaviorGeneric ? behaviorType.GetGenericTypeDefinition() : null;");
        sb.AppendLine();
        sb.AppendLine("            for (var i = 0; i < exemptions.Count; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                var exempted = exemptions[i];");
        sb.AppendLine("                if (exempted == behaviorType) return true;");
        sb.AppendLine();
        sb.AppendLine("                if (exempted.IsGenericTypeDefinition && isBehaviorGeneric && behaviorDef == exempted)");
        sb.AppendLine("                    return true;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private sealed class PipelineBindingComparer : IComparer<CqrsPipelineBehaviorBinding>");
        sb.AppendLine("        {");
        sb.AppendLine("            public static PipelineBindingComparer Instance { get; } = new();");
        sb.AppendLine("            private PipelineBindingComparer() { }");
        sb.AppendLine();
        sb.AppendLine("            public int Compare(CqrsPipelineBehaviorBinding? x, CqrsPipelineBehaviorBinding? y)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (ReferenceEquals(x, y)) return 0;");
        sb.AppendLine("                if (x is null) return -1;");
        sb.AppendLine("                if (y is null) return 1;");
        sb.AppendLine();
        sb.AppendLine("                var byPriority = x.Priority.CompareTo(y.Priority);");
        sb.AppendLine("                if (byPriority != 0) return byPriority;");
        sb.AppendLine();
        sb.AppendLine("                return string.CompareOrdinal(x.BehaviorType.FullName, y.BehaviorType.FullName);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
