using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    private static string GenerateNotificationDispatcher(ImmutableArray<CandidateModel> candidates, KnownSnapshot known)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Notifications;");
        sb.AppendLine("using CQRSharp.Core.Notifications;");
        sb.AppendLine();
        sb.AppendLine($"namespace {known.ModuleNamespace}");
        sb.AppendLine("{");
        EmitSummary(sb, "    ", "Source-generated, AOT-safe notification dispatcher that publishes this assembly's notifications to their handlers without reflection.");
        sb.AppendLine("    public sealed class GeneratedDirectNotificationDispatcher(IServiceProvider services) : DirectNotificationDispatcher(services)");
        sb.AppendLine("    {");
        EmitSummary(sb, "        ", "Publishes the notification to every handler registered for its concrete type.");
        sb.AppendLine("        public override Task Publish(INotification notification, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(notification);");

        var notificationTypes = candidates
            .SelectMany(c => c.HandledNotifications)
            .Distinct(System.StringComparer.Ordinal)
            .OrderBy(t => t, System.StringComparer.Ordinal)
            .ToArray();

        // Not a switch expression: a handler for a base type or interface (an audit INotificationHandler<INotification>)
        // would put an arm that subsumes every later one — CS8510 in the consumer's build. Exact runtime type first, so
        // a derived notification reaches its own handlers; assignable matches are the fallback.
        sb.AppendLine("            var type = notification.GetType();");
        foreach (var typeName in notificationTypes)
            sb.AppendLine($"            if (type == typeof({typeName})) return Publish(({typeName})notification, cancellationToken);");
        foreach (var typeName in notificationTypes)
            sb.AppendLine($"            if (notification is {typeName}) return Publish(({typeName})notification, cancellationToken);");

        sb.AppendLine("            return Task.CompletedTask;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
