using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    // Both dispatchers route through a static table keyed by the request's exact runtime type rather than a type-pattern
    // switch. A switch tests its arms in order — linear in the number of request types — and refuses to compile when one
    // concrete request derives from another (the base arm subsumes the derived one, CS8510). A table is one hash lookup
    // and has neither problem. Every entry is a static lambda closed over concrete types, so it stays AOT-safe.

    private static string GenerateDispatcher(ImmutableArray<CandidateModel> candidates, KnownSnapshot known)
    {
        var requests = candidates
            .Where(c => c.Request is { Kind: RequestKind.Command or RequestKind.Query })
            .Select(c => c.Request!)
            .GroupBy(r => r.RequestTypeNameNullable, StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(r => r.RequestTypeNameNullable, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using CQRSharp;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine("using CQRSharp.Pipelines;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine();
        sb.AppendLine($"namespace {known.ModuleNamespace}");
        sb.AppendLine("{");
        EmitSummary(sb, "    ", "Source-generated, AOT-safe dispatcher that routes this assembly's requests to their handler pipeline without reflection.");
        sb.AppendLine("    public sealed class GeneratedRequestDispatcher(IPipelineExecutor pipelineExecutor) : IRequestDispatcher");
        sb.AppendLine("    {");
        EmitSummary(sb, "        ", "This assembly's routes by exact request type; each closes the executor over the request's concrete request and result types.");
        sb.AppendLine("        internal static readonly Dictionary<Type, RequestRoute> Routes = new Dictionary<Type, RequestRoute>");
        sb.AppendLine("        {");
        foreach (var request in requests)
            sb.AppendLine($"            [typeof({request.RequestTypeNameNullable})] = static (executor, request, ct) => {ExecutorCall(request)},");
        sb.AppendLine("        };");
        sb.AppendLine();
        EmitSummary(sb, "        ", "The boxed-result routes behind the untyped Send(object) path.");
        sb.AppendLine("        internal static readonly Dictionary<Type, UntypedRequestRoute> UntypedRoutes = new Dictionary<Type, UntypedRequestRoute>");
        sb.AppendLine("        {");
        foreach (var request in requests)
            sb.AppendLine($"            [typeof({request.RequestTypeNameNullable})] = static async (executor, request, ct) => await {ExecutorCall(request)}.ConfigureAwait(false),");
        sb.AppendLine("        };");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Dispatches the request to its source-generated handler pipeline and returns the typed response.");
        sb.AppendLine("        public Task<TResponse> ExecuteAsync<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine("            return Routes.TryGetValue(request.GetType(), out var route)");
        sb.AppendLine("                ? (Task<TResponse>)route(pipelineExecutor, request, cancellationToken)");
        sb.AppendLine("                : throw NoRoute(request);");
        sb.AppendLine("        }");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Dispatches the request to its source-generated handler pipeline and returns the response as an object.");
        sb.AppendLine("        public Task<object?> ExecuteAsync(IRequest request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine("            return UntypedRoutes.TryGetValue(request.GetType(), out var route)");
        sb.AppendLine("                ? route(pipelineExecutor, request, cancellationToken)");
        sb.AppendLine("                : throw NoRoute(request);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static InvalidOperationException NoRoute(IRequest request)");
        sb.AppendLine("            => new InvalidOperationException($\"No handler or pipeline found for request type '{request.GetType().FullName}'. Ensure it's public or internal and has a corresponding handler.\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();

        static string ExecutorCall(RequestModel request)
            => request.Kind == RequestKind.Query
                ? $"executor.ExecuteQueryAsync<{request.RequestTypeNameNullable}, {request.ResultOrItemNullable}>(({request.RequestTypeNameNullable})request, ct)"
                : $"executor.ExecuteCommandAsync<{request.RequestTypeNameNullable}>(({request.RequestTypeNameNullable})request, ct)";
    }

    private static string GenerateStreamDispatcher(ImmutableArray<CandidateModel> candidates, KnownSnapshot known)
    {
        var requests = candidates
            .Where(c => c.Request is { Kind: RequestKind.Stream })
            .Select(c => c.Request!)
            .GroupBy(r => r.RequestTypeNameNullable, StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(r => r.RequestTypeNameNullable, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        // WithCancellation/ConfigureAwait on IAsyncEnumerable live here; never rely on the consumer's implicit usings.
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CQRSharp;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine("using CQRSharp.Pipelines;");
        sb.AppendLine();
        sb.AppendLine($"namespace {known.ModuleNamespace}");
        sb.AppendLine("{");
        EmitSummary(sb, "    ", "Source-generated, AOT-safe dispatcher that routes this assembly's streaming requests to their handler pipeline without reflection.");
        sb.AppendLine("    public sealed class GeneratedStreamRequestDispatcher(IPipelineExecutor pipelineExecutor) : IStreamRequestDispatcher");
        sb.AppendLine("    {");
        // The typed route returns IAsyncEnumerable<TItem> as object (the dispatcher casts it back); the untyped one boxes items.
        sb.AppendLine("        private static readonly Dictionary<Type, Func<IPipelineExecutor, IStreamRequest, CancellationToken, object>> Routes = new Dictionary<Type, Func<IPipelineExecutor, IStreamRequest, CancellationToken, object>>");
        sb.AppendLine("        {");
        foreach (var request in requests)
            sb.AppendLine($"            [typeof({request.RequestTypeNameNullable})] = static (executor, request, ct) => {StreamCall(request)},");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        private static readonly Dictionary<Type, Func<IPipelineExecutor, IStreamRequest, CancellationToken, IAsyncEnumerable<object?>>> UntypedRoutes = new Dictionary<Type, Func<IPipelineExecutor, IStreamRequest, CancellationToken, IAsyncEnumerable<object?>>>");
        sb.AppendLine("        {");
        foreach (var request in requests)
            sb.AppendLine($"            [typeof({request.RequestTypeNameNullable})] = static (executor, request, ct) => Box({StreamCall(request)}, ct),");
        sb.AppendLine("        };");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Dispatches the streaming request to its source-generated handler pipeline and returns the produced asynchronous stream.");
        sb.AppendLine(
            "        public IAsyncEnumerable<TItem> ExecuteAsync<TItem>(IStreamRequest<TItem> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine("            return Routes.TryGetValue(request.GetType(), out var route)");
        sb.AppendLine("                ? (IAsyncEnumerable<TItem>)route(pipelineExecutor, request, cancellationToken)");
        sb.AppendLine("                : throw NoRoute(request);");
        sb.AppendLine("        }");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Dispatches the streaming request to its source-generated handler pipeline and returns the produced items as objects.");
        sb.AppendLine("        public IAsyncEnumerable<object?> ExecuteAsync(IStreamRequest request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine("            return UntypedRoutes.TryGetValue(request.GetType(), out var route)");
        sb.AppendLine("                ? route(pipelineExecutor, request, cancellationToken)");
        sb.AppendLine("                : throw NoRoute(request);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static InvalidOperationException NoRoute(IStreamRequest request)");
        sb.AppendLine("            => new InvalidOperationException($\"No stream handler or pipeline found for request type '{request.GetType().FullName}'. Ensure it's public or internal and has a corresponding handler.\");");
        sb.AppendLine();
        sb.AppendLine(
            "        private static async IAsyncEnumerable<object?> Box<T>(IAsyncEnumerable<T> source, [EnumeratorCancellation] CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            await foreach (var item in source.WithCancellation(cancellationToken).ConfigureAwait(false))");
        sb.AppendLine("                yield return item;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();

        static string StreamCall(RequestModel request)
            => $"executor.ExecuteStreamAsync<{request.RequestTypeNameNullable}, {request.ResultOrItemNullable}>(({request.RequestTypeNameNullable})request, ct)";
    }
}
