using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    private static string GenerateDispatcher(ImmutableArray<CandidateModel> candidates, KnownSnapshot known)
    {
        var requests = candidates
            .Where(c => c.Request is { Kind: RequestKind.Command or RequestKind.Query })
            .Select(c => c.Request!)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS9113 // pipelineExecutor is unread when this assembly declares no command/query requests.");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Markers.Request;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine();
        sb.AppendLine($"namespace {known.ModuleNamespace}");
        sb.AppendLine("{");
        EmitSummary(sb, "    ", "Source-generated, AOT-safe dispatcher that routes this assembly's requests to their handler pipeline without reflection.");
        sb.AppendLine("    public sealed class GeneratedRequestDispatcher(IPipelineExecutor pipelineExecutor) : IRequestDispatcher");
        sb.AppendLine("    {");
        EmitSummary(sb, "        ", "Dispatches the request to its source-generated handler pipeline and returns the typed response.");
        sb.AppendLine("        public Task<TResponse> ExecuteAsync<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            return request switch");
        sb.AppendLine("            {");

        foreach (var request in requests)
        {
            var requestName = request.RequestTypeNameNullable;
            if (request.Kind == RequestKind.Query)
                sb.AppendLine(
                    $"                {requestName} q => (Task<TResponse>)(object)pipelineExecutor.ExecuteQueryAsync<{requestName}, {request.ResultOrItemNullable}>(q, cancellationToken),");
            else
                sb.AppendLine($"                {requestName} c => (Task<TResponse>)(object)pipelineExecutor.ExecuteCommandAsync(c, cancellationToken),");
        }

        sb.AppendLine(
            "                _ => throw new System.InvalidOperationException($\"No handler or pipeline found for request type '{request.GetType().FullName}'. Ensure it's public or internal and has a corresponding handler.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Dispatches the request to its source-generated handler pipeline and returns the response as an object.");
        sb.AppendLine("        public async Task<object?> ExecuteAsync(IRequest request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            return request switch");
        sb.AppendLine("            {");

        foreach (var request in requests)
        {
            var requestName = request.RequestTypeNameNullable;
            if (request.Kind == RequestKind.Query)
                sb.AppendLine(
                    $"                {requestName} q => await pipelineExecutor.ExecuteQueryAsync<{requestName}, {request.ResultOrItemNullable}>(q, cancellationToken),");
            else
                sb.AppendLine($"                {requestName} c => await pipelineExecutor.ExecuteCommandAsync(c, cancellationToken),");
        }

        sb.AppendLine(
            "                _ => throw new System.InvalidOperationException($\"No handler or pipeline found for request type '{request.GetType().FullName}'. Ensure it's public or internal and has a corresponding handler.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateStreamDispatcher(ImmutableArray<CandidateModel> candidates, KnownSnapshot known)
    {
        var requests = candidates
            .Where(c => c.Request is { Kind: RequestKind.Stream })
            .Select(c => c.Request!)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS9113 // pipelineExecutor is unread when this assembly declares no stream requests.");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        // WithCancellation/ConfigureAwait on IAsyncEnumerable live here; never rely on the consumer's implicit usings.
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Markers.Stream;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine();
        sb.AppendLine($"namespace {known.ModuleNamespace}");
        sb.AppendLine("{");
        EmitSummary(sb, "    ", "Source-generated, AOT-safe dispatcher that routes this assembly's streaming requests to their handler pipeline without reflection.");
        sb.AppendLine("    public sealed class GeneratedStreamRequestDispatcher(IPipelineExecutor pipelineExecutor) : IStreamRequestDispatcher");
        sb.AppendLine("    {");
        EmitSummary(sb, "        ", "Dispatches the streaming request to its source-generated handler pipeline and returns the produced asynchronous stream.");
        sb.AppendLine(
            "        public IAsyncEnumerable<TItem> ExecuteAsync<TItem>(IStreamRequest<TItem> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine("            return request switch");
        sb.AppendLine("            {");

        foreach (var request in requests)
            sb.AppendLine(
                $"                {request.RequestTypeNameNullable} r => (global::System.Collections.Generic.IAsyncEnumerable<TItem>)(object)pipelineExecutor.ExecuteStreamAsync<{request.RequestTypeNameNullable}, {request.ResultOrItemNullable}>(r, cancellationToken),");

        sb.AppendLine(
            "                _ => throw new InvalidOperationException($\"No stream handler or pipeline found for request type '{request.GetType().FullName}'. Ensure it's public or internal and has a corresponding handler.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Dispatches the streaming request to its source-generated handler pipeline and returns the produced items as objects.");
        sb.AppendLine("        public IAsyncEnumerable<object?> ExecuteAsync(IStreamRequest request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine("            return request switch");
        sb.AppendLine("            {");

        foreach (var request in requests)
            sb.AppendLine(
                $"                {request.RequestTypeNameNullable} r => Box(pipelineExecutor.ExecuteStreamAsync<{request.RequestTypeNameNullable}, {request.ResultOrItemNullable}>(r, cancellationToken), cancellationToken),");

        sb.AppendLine(
            "                _ => throw new InvalidOperationException($\"No stream handler or pipeline found for request type '{request.GetType().FullName}'. Ensure it's public or internal and has a corresponding handler.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine(
            "        private static async IAsyncEnumerable<object?> Box<T>(IAsyncEnumerable<T> source, [EnumeratorCancellation] CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            await foreach (var item in source.WithCancellation(cancellationToken).ConfigureAwait(false))");
        sb.AppendLine("                yield return item;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
