namespace CQRSharp.Abstractions.Data.Interfaces.Notifications;

/// <summary>
///     Defines a contract for serializing and deserializing notifications.
///     This is used by the outbox pattern to persist notifications in an AOT-compatible way.
///     An implementation is typically source-generated by CQRSharp.Generators.
/// </summary>
public interface INotificationSerializer
{
    /// <summary>
    ///     Serializes a notification object into a string representation.
    /// </summary>
    /// <param name="notification">The notification to serialize.</param>
    /// <returns>A string payload representing the notification.</returns>
    /// <exception cref="NotSupportedException">Thrown when the notification type is not supported by the serializer.</exception>
    string Serialize(INotification notification);

    /// <summary>
    ///     Deserializes a string payload back into a notification object.
    /// </summary>
    /// <param name="notificationType">The full type name of the notification to create.</param>
    /// <param name="payload">The string payload to deserialize.</param>
    /// <returns>An instance of the deserialized notification.</returns>
    /// <exception cref="NotSupportedException">Thrown when the notification type is not supported by the serializer.</exception>
    INotification Deserialize(string notificationType, string payload);
}