<Project Sdk="Microsoft.NET.Sdk">

    <!-- Build Configuration -->
    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <LangVersion>default</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EnableAotAnalyzer>true</EnableAotAnalyzer>
    </PropertyGroup>

    <!-- NuGet Package Metadata -->
    <PropertyGroup>
        <Title>A lightweight, extensible, and attribute-driven Command Query Responsibility Segregation (CQRS) framework for .NET applications.</Title>
        <Authors>$(AssemblyName)</Authors>
        <Company>BisocM</Company>
        <PackageProjectUrl>cqrsharp.bisocm.org</PackageProjectUrl>
        <PackageIcon>CQRSharp_Icon.png</PackageIcon>
        <RepositoryUrl>https://github.com/BisocM/CQRSharp</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>CQRS</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <Version>2.2.2</Version>
        <Description>A lightweight, extensible, and attribute-driven Command Query Responsibility Segregation (CQRS) framework for .NET applications.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageReleaseNotes>
            🚀 Release Notes for 2.2.1

            🔧 Roslyn Generators
            Inclusion of Roslyn compile-time generators - goodbye reflection!

            The library has now been fully updated to leverage compile-time generators over reflection in all its running processes. This will not only allow the library to be fully compatible with native AoT, but also improve its performance in high-throughput applications.

            Now, instead of dynamically generating pipelines, they are generated at compile time, outputting a map of all pipelines with relevant method calls into a predetermined registry - `PipelineRegsitry`. Similarly, the `HandlerRegistry` that previously mapped commands to handler methods at runtime is now generated at compile time.

            Keeping all data cached in registries does increase the application's trace, but it greatly contributes to reducing the overhead caused by reflection.

            📂 Breaking Changes?
            No major breaking changes—this version remains backward compatible while introducing a more modular and optimized architecture.

            ⏭️ What’s Next?
            - The generators are still quite new and may require further refinements.
            - Additional performance and memory efficiency improvements related to BackgroundTaskQueue in asynchronous applications.
        </PackageReleaseNotes>
    </PropertyGroup>

    <!-- Package Assets -->
    <ItemGroup>
        <None Include="..\CQRSharp_Icon.png">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\LICENSE">
          <Pack>true</Pack>
          <PackagePath>\</PackagePath>
          <Link>LICENSE</Link>
        </None>
        <None Include="..\README.md">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>
    
    <!-- Package Dependencies -->
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.2" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.2" />
    </ItemGroup>

    <ItemGroup>
        <None Include="build\CQRSharp.DependencyCheck.targets" Pack="true" PackagePath="build\" />
    </ItemGroup>

    <!-- Project References -->
    <ItemGroup>
        <ProjectReference Include="..\CQRSharp.Shared\CQRSharp.Shared.csproj" />
    </ItemGroup>

</Project>