<Project Sdk="Microsoft.NET.Sdk">

    <!-- Build Configuration -->
    <PropertyGroup>
        <TargetFrameworks>net10.0;net8.0;net9.0</TargetFrameworks>
        <LangVersion>default</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EnableAotAnalyzer>true</EnableAotAnalyzer>
        <RunAOTCompilation>true</RunAOTCompilation>

        <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageOutputPath>..\NuGetPackages</PackageOutputPath>
    </PropertyGroup>

    <!-- NuGet Package Metadata -->
    <PropertyGroup>
        <Title>A lightweight, extensible, and attribute-driven Command Query Responsibility Segregation (CQRS) framework for .NET applications.</Title>
        <Authors>$(AssemblyName)</Authors>
        <Company>BisocM</Company>
        <PackageProjectUrl>cqrsharp.bisocm.org</PackageProjectUrl>
        <PackageIcon>CQRSharp_Icon.png</PackageIcon>
        <RepositoryUrl>https://github.com/BisocM/CQRSharp</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>CQRS;Native AoT</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <Version>2.2.6</Version>
        <Description>A lightweight, extensible, and attribute-driven Command Query Responsibility Segregation (CQRS) framework for .NET applications, with complete Native AoT support.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageReleaseNotes>
            🚀 Release Notes for 2.2.6

            🔧 Changes

            📂 Breaking Changes?
        </PackageReleaseNotes>
    </PropertyGroup>

    <!-- Package Assets -->
    <ItemGroup>
        <None Include="..\CQRSharp_Icon.png">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\LICENSE">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
            <Link>LICENSE</Link>
        </None>
        <None Include="..\README.md">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <!-- Package Dependencies -->
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.2"/>
    </ItemGroup>

    <!-- Project References -->
    <ItemGroup>
        <ProjectReference Include="..\CQRSharp.Shared\CQRSharp.Shared.csproj"/>
    </ItemGroup>

    <Target Name="CleanPackages" BeforeTargets="Pack">
        <!-- Delete all .nupkg files in the PackageOutputPath directory -->
        <Delete Files="$(PackageOutputPath)\*.nupkg" ContinueOnError="true"/>
    </Target>
</Project>