using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Abstractions.SourceGeneration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace CQRSharp.Generators.Types;

public sealed partial class CqrsSourceGenerator
{
    private sealed class StableNotificationInfo
    {
        public StableNotificationInfo(string stableName, string typeName)
        {
            StableName = stableName;
            TypeName = typeName;
        }

        public string StableName { get; }
        public string TypeName { get; }
    }

    private static StableNotificationInfo[] CollectStableNotifications(
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> candidateClasses,
        SourceProductionContext context)
    {
        var notificationSymbol = compilation.GetTypeByMetadataName(TypeStrings.INotification);
        var notificationNameAttributeSymbol = compilation.GetTypeByMetadataName(TypeStrings.NotificationNameAttribute);

        if (notificationSymbol is null || notificationNameAttributeSymbol is null)
            return Array.Empty<StableNotificationInfo>();

        var stableNotificationsWithPotentialDuplicates = candidateClasses
            .Where(c => c is { IsAbstract: false, IsGenericType: false } &&
                        IsAccessibleFromGeneratedCode(c) &&
                        c.AllInterfaces.Contains(notificationSymbol, SymbolEqualityComparer.Default))
            .Select(c =>
            {
                var attr = c.GetAttributes()
                    .FirstOrDefault(a =>
                        a.AttributeClass is not null &&
                        SymbolEqualityComparer.Default.Equals(a.AttributeClass, notificationNameAttributeSymbol));
                if (attr is null) return null;

                var arg = attr.ConstructorArguments.FirstOrDefault();
                var stableName = arg.Value as string;
                if (string.IsNullOrWhiteSpace(stableName)) return null;

                var typeName = c.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return new StableNotificationInfo(stableName!, typeName);
            })
            .Where(x => x is not null)
            .Cast<StableNotificationInfo>()
            .ToArray();

        foreach (var group in stableNotificationsWithPotentialDuplicates
                     .GroupBy(n => n.StableName, StringComparer.Ordinal)
                     .Where(g => g.Count() > 1))
        {
            var types = string.Join(", ", group.Select(n => n.TypeName));
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "CQRGEN002",
                    "Duplicate NotificationName",
                    "Duplicate [NotificationName] '{0}' found on: {1}. Stable names must be unique for outbox serialization.",
                    "CQRSharp.Generators",
                    DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                Location.None,
                group.Key,
                types));
        }

        var stableNotifications = stableNotificationsWithPotentialDuplicates
            .GroupBy(n => n.StableName, StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(n => n.StableName, StringComparer.Ordinal)
            .ThenBy(n => n.TypeName, StringComparer.Ordinal)
            .ToArray();

        return stableNotifications;
    }

    private static string GenerateOutboxNotificationSerializer(StableNotificationInfo[] stableNotifications)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine("using CQRSharp.Abstractions.Data.Interfaces.Notifications;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Serialization.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal sealed class GeneratedOutboxNotificationSerializer : INotificationSerializer, IStableNotificationNameProvider");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        private static readonly JsonSerializerOptions SerializerOptions = new(JsonSerializerDefaults.Web) { TypeInfoResolver = new DefaultJsonTypeInfoResolver() };");
        sb.AppendLine();
        sb.AppendLine("        public byte[] Serialize(INotification notification)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(notification);");
        sb.AppendLine();
        sb.AppendLine("            return notification switch");
        sb.AppendLine("            {");
        foreach (var notification in stableNotifications)
            sb.AppendLine(
                $"                {notification.TypeName} n => JsonSerializer.SerializeToUtf8Bytes(n, SerializerOptions),");
        sb.AppendLine(
            "                _ => throw new InvalidOperationException($\"Notification type '{notification.GetType().FullName}' is not registered for outbox serialization. Add [NotificationName] or register a custom INotificationSerializer.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public INotification? Deserialize(string notificationName, byte[] payload)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.IsNullOrWhiteSpace(notificationName)) return null;");
        sb.AppendLine("            if (payload is null || payload.Length == 0) return null;");
        sb.AppendLine();
        sb.AppendLine("            return notificationName switch");
        sb.AppendLine("            {");
        foreach (var notification in stableNotifications)
        {
            var nameLiteral = SymbolDisplay.FormatLiteral(notification.StableName, quote: true);
            sb.AppendLine(
                $"                {nameLiteral} => JsonSerializer.Deserialize<{notification.TypeName}>(payload, SerializerOptions),");
        }

        sb.AppendLine("                _ => null");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public string GetNotificationName(Type notificationType)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(notificationType);");
        sb.AppendLine("            return GetStableName(notificationType) ?? notificationType.FullName ?? notificationType.Name;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public bool TryGetStableName(Type notificationType, out string stableName)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(notificationType);");
        sb.AppendLine("            stableName = GetStableName(notificationType) ?? string.Empty;");
        sb.AppendLine("            return stableName.Length > 0;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static string? GetStableName(Type notificationType)");
        sb.AppendLine("        {");
        foreach (var notification in stableNotifications)
        {
            var nameLiteral = SymbolDisplay.FormatLiteral(notification.StableName, quote: true);
            sb.AppendLine($"            if (notificationType == typeof({notification.TypeName})) return {nameLiteral};");
        }
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
