using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Abstractions.SourceGeneration;
using Microsoft.CodeAnalysis;

namespace CQRSharp.Generators.Types;

public sealed partial class CqrsSourceGenerator
{
    private static string GenerateNotificationDispatcher(Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CQRSharp.Abstractions.Data.Interfaces.Notifications;");
        sb.AppendLine("using CQRSharp.Core.Notifications;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Notifications.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class GeneratedDirectNotificationDispatcher(IServiceScopeFactory scopeFactory) : IDirectNotificationDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine("        public Task Publish(INotification notification, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(notification);");
        sb.AppendLine("            return notification switch");
        sb.AppendLine("            {");

        var notificationHandlerDef = compilation.GetTypeByMetadataName(TypeStrings.INotificationHandler)?.OriginalDefinition;
        if (notificationHandlerDef is not null)
        {
            var notificationTypes = candidateClasses
                .Where(c => c is { IsAbstract: false, IsGenericType: false })
                .SelectMany(GetInterfacesAndBaseInterfaces)
                .Where(i => i is { IsGenericType: true, TypeArguments.Length: 1 } &&
                            SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, notificationHandlerDef))
                .Select(i => i.TypeArguments[0])
                .Where(t => t is not null)
                .Select(t => t!)
                .Distinct(SymbolEqualityComparer.Default)
                .Cast<ITypeSymbol>()
                .OrderBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .ToArray();

            foreach (var type in notificationTypes)
            {
                var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"                {typeName} n => Publish(n, cancellationToken),");
            }
        }

        sb.AppendLine("                _ => Task.CompletedTask");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public async Task Publish<TNotification>(TNotification notification, CancellationToken cancellationToken = default) where TNotification : INotification");
        sb.AppendLine("        {");
        sb.AppendLine("            using var scope = scopeFactory.CreateScope();");
        sb.AppendLine("            var handlers = scope.ServiceProvider.GetServices<INotificationHandler<TNotification>>();");
        sb.AppendLine("            List<Task>? tasks = null;");
        sb.AppendLine("            foreach (var handler in handlers)");
        sb.AppendLine("            {");
        sb.AppendLine("                tasks ??= new List<Task>();");
        sb.AppendLine("                tasks.Add(handler.Handle(notification, cancellationToken));");
        sb.AppendLine("            }");
        sb.AppendLine("            if (tasks is null) return;");
        sb.AppendLine("            await Task.WhenAll(tasks).ConfigureAwait(false);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
