using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Abstractions.SourceGeneration;
using Microsoft.CodeAnalysis;

namespace CQRSharp.Generators.Types;

public sealed partial class CqrsSourceGenerator
{
    private static string GenerateRegistrations(Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using CQRSharp.Abstractions.Data.Interfaces.Notifications;");
        sb.AppendLine("using CQRSharp.Abstractions.Data.Models.Requests;");
        sb.AppendLine("using CQRSharp.Core.Caching.Requests;");
        sb.AppendLine("using CQRSharp.Core.Caching.Handlers;");
        sb.AppendLine("using CQRSharp.Core.Caching.Pipelines;");
        sb.AppendLine("using CQRSharp.Core.Caching.Contexts;");
        sb.AppendLine("using CQRSharp.Core.Factories;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Extensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static class CqrsGeneratedRegistrations");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddGenerated(this IServiceCollection services)");
        sb.AppendLine("        {");

        GenerateHandlerServices(sb, compilation, candidateClasses);
        GenerateRequestRegistry(sb, compilation, candidateClasses);
        GenerateHandlerRegistry(sb, compilation, candidateClasses);
        GenerateContextFactoryRegistry(sb, compilation, candidateClasses);

        sb.AppendLine();
        sb.AppendLine("            // Registering the generated dispatchers.");
        sb.AppendLine(
            "            services.AddSingleton<global::CQRSharp.Core.Notifications.IDirectNotificationDispatcher, global::CQRSharp.Core.Notifications.Generated.GeneratedDirectNotificationDispatcher>();");
        sb.AppendLine(
            "            services.AddSingleton<global::CQRSharp.Core.Pipelines.IRequestDispatcher, global::CQRSharp.Core.Requests.Generated.GeneratedRequestDispatcher>();");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateHandlerServices(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Handler Services by Interface Implementation");

        var allKnownHandlers = GetAllKnownHandlerSymbols(compilation)
            .Select(s => s!.OriginalDefinition)
            .ToArray();

        if (!allKnownHandlers.Any()) return;

        var handlerImplementations = candidateClasses
            .Where(c => c is { IsAbstract: false, IsGenericType: false } &&
                        GetInterfacesAndBaseInterfaces(c).Any(iface => iface.IsGenericType && allKnownHandlers.Contains(iface.OriginalDefinition, SymbolEqualityComparer.Default)))
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>(); // THIS IS THE FIX: Cast back to the specific symbol type.

        foreach (var implementationSymbol in handlerImplementations)
        {
            var implementationTypeName = implementationSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            services.AddTransient(typeof({implementationTypeName}));");

            var implementedInterfaces = GetInterfacesAndBaseInterfaces(implementationSymbol)
                .Where(iface => iface.IsGenericType && allKnownHandlers.Contains(iface.OriginalDefinition, SymbolEqualityComparer.Default));

            foreach (var iface in implementedInterfaces)
            {
                var interfaceTypeName = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            services.AddTransient(typeof({interfaceTypeName}), sp => sp.GetRequiredService<{implementationTypeName}>());");
            }
        }
    }

    private static void GenerateRequestRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Request Registry");
        sb.AppendLine("            var requestMetadataMappings = new ConcurrentDictionary<Type, RequestMetadata>();");

        var commandHandlerDef = compilation.GetTypeByMetadataName(TypeStrings.ICommandHandler2)?.OriginalDefinition;
        var queryHandlerDef = compilation.GetTypeByMetadataName(TypeStrings.IQueryHandler3)?.OriginalDefinition;
        var preHandlerInterfaceSymbol = compilation.GetTypeByMetadataName(TypeStrings.IPreHandlerAttribute);
        var postHandlerInterfaceSymbol = compilation.GetTypeByMetadataName(TypeStrings.IPostHandlerAttribute);
        var pipelineExemptionAttributeSymbol = compilation.GetTypeByMetadataName(TypeStrings.PipelineExemptionAttribute);

        if (commandHandlerDef is null || queryHandlerDef is null || preHandlerInterfaceSymbol is null || postHandlerInterfaceSymbol is null ||
            pipelineExemptionAttributeSymbol is null) return;

        var handlerInterfaces = candidateClasses
            .SelectMany(GetInterfacesAndBaseInterfaces)
            .Where(i => i.IsGenericType && (SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, commandHandlerDef) ||
                                            SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, queryHandlerDef)))
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>();

        foreach (var handlerInterface in handlerInterfaces)
        {
            var requestTypeSymbol = handlerInterface.TypeArguments[0];
            var handlerImplementation =
                candidateClasses.FirstOrDefault(c => !c.IsAbstract && GetInterfacesAndBaseInterfaces(c).Contains(handlerInterface, SymbolEqualityComparer.Default));

            if (handlerImplementation is null) continue;

            var handlerImplementationName = handlerImplementation.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var requestTypeName = requestTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var preHandlersCode = GenerateAttributeArrayCode(requestTypeSymbol, preHandlerInterfaceSymbol, $"global::{TypeStrings.IPreHandlerAttribute}");
            var postHandlersCode = GenerateAttributeArrayCode(requestTypeSymbol, postHandlerInterfaceSymbol, $"global::{TypeStrings.IPostHandlerAttribute}");
            var pipelineExemptionsCode = GenerateAttributeArrayCode(requestTypeSymbol, pipelineExemptionAttributeSymbol, $"global::{TypeStrings.PipelineExemptionAttribute}");
            var sensitivePropertiesCode = GenerateSensitivePropertiesCode(requestTypeSymbol);

            var isQuery = SymbolEqualityComparer.Default.Equals(handlerInterface.OriginalDefinition, queryHandlerDef);
            var resultTypeCode = isQuery ? $"typeof({handlerInterface.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})" : "null";

            var contextTypeSymbol = GetRequestContextType(requestTypeSymbol, compilation) ?? compilation.GetTypeByMetadataName(TypeStrings.RequestContextBase);
            var contextTypeName = contextTypeSymbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "object";

            sb.AppendLine(
                $"            requestMetadataMappings.TryAdd(typeof({requestTypeName}), new RequestMetadata(typeof({requestTypeName}), typeof({handlerImplementationName}), {preHandlersCode}, {postHandlersCode}, {pipelineExemptionsCode}, {sensitivePropertiesCode}, {resultTypeCode}, typeof({contextTypeName})));");
        }

        sb.AppendLine("            services.AddSingleton<IRequestRegistry>(new RequestRegistry(requestMetadataMappings));");
    }

    private static void GenerateHandlerRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Handler Registry");
        sb.AppendLine("            var handlerInvokerMappings = new ConcurrentDictionary<Type, HandlerInvokerDelegate>();");

        var commandHandlerDef = compilation.GetTypeByMetadataName(TypeStrings.ICommandHandler2)?.OriginalDefinition;
        var queryHandlerDef = compilation.GetTypeByMetadataName(TypeStrings.IQueryHandler3)?.OriginalDefinition;

        if (commandHandlerDef is null || queryHandlerDef is null) return;

        var handlerInterfaces = candidateClasses
            .SelectMany(GetInterfacesAndBaseInterfaces)
            .Where(i => i.IsGenericType && (SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, commandHandlerDef) ||
                                            SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, queryHandlerDef)))
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>();

        foreach (var iface in handlerInterfaces)
        {
            var requestType = iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var handlerInterface = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var invokerLambda = $"async (handler, request, ct) => (object)await (({handlerInterface})handler).Handle(({requestType})request, ct).ConfigureAwait(false)";
            sb.AppendLine($"            handlerInvokerMappings.TryAdd(typeof({requestType}), {invokerLambda});");
        }

        sb.AppendLine("            services.AddSingleton<IHandlerRegistry>(new HandlerRegistry(handlerInvokerMappings));");
    }

    private static void GenerateContextFactoryRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Context Factory Registry");
        sb.AppendLine("            var factoryMappings = new ConcurrentDictionary<Type, Func<System.IServiceProvider, object>>();");

        var factoryInterfaceSymbol = compilation.GetTypeByMetadataName(TypeStrings.IRequestContextFactory);
        if (factoryInterfaceSymbol is null) return;

        var contextTypes = candidateClasses
            .Where(c => c is { DeclaredAccessibility: Accessibility.Public, IsAbstract: false })
            .SelectMany(c => GetInterfacesAndBaseInterfaces(c).Where(i => i.OriginalDefinition.Equals(factoryInterfaceSymbol.OriginalDefinition, SymbolEqualityComparer.Default)))
            .Select(i => i.TypeArguments.FirstOrDefault())
            .Where(t => t is not null)
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<ITypeSymbol>();

        foreach (var tContext in contextTypes)
        {
            var contextTypeName = tContext.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            factoryMappings.TryAdd(typeof({contextTypeName}), sp => sp.GetRequiredService<IRequestContextFactory<{contextTypeName}>>());");
        }

        sb.AppendLine("            services.AddSingleton<IContextFactoryRegistry>(new ContextFactoryRegistry(factoryMappings));");
    }

    private static string GenerateDispatcher(Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using CQRSharp.Abstractions.Data.Interfaces.Markers.Request;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine("using CQRSharp.Core.Requests;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Requests.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class GeneratedRequestDispatcher(IPipelineExecutor pipelineExecutor) : IRequestDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine("        public Task<TResponse> ExecuteAsync<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            return request switch");
        sb.AppendLine("            {");

        var commandSymbol = compilation.GetTypeByMetadataName(TypeStrings.ICommand);
        var querySymbol = compilation.GetTypeByMetadataName(TypeStrings.IQuery);

        if (commandSymbol is not null && querySymbol is not null)
        {
            var requestSymbols = candidateClasses
                .Where(c => c is { IsAbstract: false, IsGenericType: false } &&
                            c.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, commandSymbol) ||
                                                     (i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, querySymbol))))
                .ToList();

            foreach (var request in requestSymbols)
            {
                var requestName = request.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var queryInterface = request.AllInterfaces.FirstOrDefault(i => i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, querySymbol));

                if (queryInterface is not null) // It's a query
                {
                    var resultName = queryInterface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    sb.AppendLine(
                        $"                {requestName} q => (Task<TResponse>)(object)pipelineExecutor.ExecuteQueryAsync<{requestName}, {resultName}>(q, cancellationToken),");
                }
                else // It's a command
                {
                    sb.AppendLine($"                {requestName} c => (Task<TResponse>)(object)pipelineExecutor.ExecuteCommandAsync(c, cancellationToken),");
                }
            }
        }

        sb.AppendLine(
            "                _ => throw new System.InvalidOperationException($\"No handler or pipeline found for request type '{request.GetType().FullName}'. Ensure it's public and has a corresponding handler.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
