using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    private static readonly DiagnosticDescriptor OutboxNotificationNotAotJsonSerializableDiagnostic = new(
        "CQRGEN005",
        "Outbox notification is not AOT-JSON serializable",
        "Notification '{0}' cannot be source-generated for AOT-safe outbox JSON: {1}. Either change the notification shape or register a custom INotificationSerializer.",
        "CQRSharp.Generators",
        DiagnosticSeverity.Error,
        true);

    // ------------------------------------------------------------------------------------------------------
    // Emit. STJ source-gen cannot be used: Roslyn runs every generator against the user's original syntax, so a
    // [JsonSerializable] context we emit is invisible to STJ's generator, and reflection-based JsonSerializer is not
    // AOT-safe. So the serializer is hand-rolled over Utf8JsonReader/Writer. One Serialize_/Deserialize_ pair per
    // notification, plus WriteObj_/ReadObj_ per object type and WriteColl_/ReadColl_ per element type, deduped so a
    // shared nested type emits exactly once.
    // ------------------------------------------------------------------------------------------------------

    private static string GenerateOutboxNotificationSerializer(IReadOnlyList<NotificationModel> stableNotifications)
    {
        var entries = stableNotifications
            .Select(n => new OutboxEmitEntry(
                n.TypeName,
                n.StableName!,
                n.OutboxRoot!,
                "Serialize_" + CreateIdentifierSuffix(n.StableName!, "N_"),
                "Deserialize_" + CreateIdentifierSuffix(n.StableName!, "N_")))
            .ToArray();

        var objectModels = new Dictionary<string, OutboxObjectModel>(StringComparer.Ordinal);
        var collectionElements = new Dictionary<string, OutboxValueModel>(StringComparer.Ordinal);
        foreach (var entry in entries)
            CollectHelpers(entry.Root, objectModels, collectionElements);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8619, CS8625");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Notifications;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Serialization.Generated");
        sb.AppendLine("{");
        EmitSummary(sb, "    ", "Source-generated, AOT-safe (reflection-free) serializer for outbox notifications that carry a stable <c>[NotificationName]</c>.");
        sb.AppendLine("    internal sealed class GeneratedOutboxNotificationSerializer : INotificationSerializer, IStableNotificationNameProvider");
        sb.AppendLine("    {");
        EmitSummary(sb, "        ", "Serializes the notification to its stable JSON byte representation.");
        sb.AppendLine("        public byte[] Serialize(INotification notification)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(notification);");
        sb.AppendLine();
        sb.AppendLine("            return notification switch");
        sb.AppendLine("            {");
        foreach (var entry in entries)
            sb.AppendLine($"                {entry.TypeName} n => {entry.SerializeMethodName}(n),");
        sb.AppendLine(
            "                _ => throw new InvalidOperationException($\"Notification type '{notification.GetType().FullName}' is not registered for outbox serialization. Add [NotificationName] or register a custom INotificationSerializer.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Deserializes a payload back into its notification type, identified by stable name; returns null when the name is unknown.");
        sb.AppendLine("        public INotification? Deserialize(string notificationName, byte[] payload)");
        sb.AppendLine("        {");
        sb.AppendLine("            // A null result means the notification name is unknown. A corrupt payload for a KNOWN");
        sb.AppendLine("            // name throws (e.g. JsonException), so callers can distinguish 'unknown type' from");
        sb.AppendLine("            // 'corrupt payload' rather than having both collapse to null.");
        sb.AppendLine("            if (string.IsNullOrWhiteSpace(notificationName)) return null;");
        sb.AppendLine("            if (payload is null || payload.Length == 0) return null;");
        sb.AppendLine();
        sb.AppendLine("            return notificationName switch");
        sb.AppendLine("            {");
        foreach (var entry in entries)
        {
            var nameLiteral = SymbolDisplay.FormatLiteral(entry.StableName, true);
            sb.AppendLine($"                {nameLiteral} => {entry.DeserializeMethodName}(payload),");
        }

        sb.AppendLine("                _ => null");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Gets the stable name for the notification type, falling back to its full type name.");
        sb.AppendLine("        public string GetNotificationName(Type notificationType)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(notificationType);");
        sb.AppendLine("            return GetStableName(notificationType) ?? notificationType.FullName ?? notificationType.Name;");
        sb.AppendLine("        }");
        sb.AppendLine();
        EmitSummary(sb, "        ", "Attempts to get the stable <c>[NotificationName]</c> for the notification type.");
        sb.AppendLine("        public bool TryGetStableName(Type notificationType, out string stableName)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(notificationType);");
        sb.AppendLine("            stableName = GetStableName(notificationType) ?? string.Empty;");
        sb.AppendLine("            return stableName.Length > 0;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static string? GetStableName(Type notificationType)");
        sb.AppendLine("        {");
        foreach (var entry in entries)
        {
            var nameLiteral = SymbolDisplay.FormatLiteral(entry.StableName, true);
            sb.AppendLine($"            if (notificationType == typeof({entry.TypeName})) return {nameLiteral};");
        }

        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var entry in entries)
        {
            sb.AppendLine($"        private static byte[] {entry.SerializeMethodName}({entry.TypeName} notification)");
            sb.AppendLine("        {");
            sb.AppendLine("            var buffer = new ArrayBufferWriter<byte>();");
            sb.AppendLine("            using (var writer = new Utf8JsonWriter(buffer))");
            sb.AppendLine("            {");
            sb.AppendLine($"                WriteObj_{entry.Root.HelperId}(writer, notification);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            var result = new byte[buffer.WrittenCount];");
            sb.AppendLine("            buffer.WrittenSpan.CopyTo(result);");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private static {entry.TypeName} {entry.DeserializeMethodName}(byte[] payload)");
            sb.AppendLine("        {");
            sb.AppendLine("            var reader = new Utf8JsonReader(payload, isFinalBlock: true, state: default);");
            sb.AppendLine("            if (!reader.Read() || reader.TokenType != JsonTokenType.StartObject)");
            sb.AppendLine("                throw new JsonException(\"Expected start of JSON object.\");");
            sb.AppendLine($"            return ReadObj_{entry.Root.HelperId}(ref reader);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        foreach (var obj in objectModels.Values.OrderBy(o => o.HelperId, StringComparer.Ordinal))
        {
            GenerateWriteObject(sb, obj);
            sb.AppendLine();
            GenerateReadObject(sb, obj);
            sb.AppendLine();
        }

        foreach (var element in collectionElements.Values.OrderBy(CollectionHelperId, StringComparer.Ordinal))
        {
            GenerateWriteCollection(sb, element);
            sb.AppendLine();
            GenerateReadCollection(sb, element);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed record OutboxEmitEntry(
        string TypeName,
        string StableName,
        OutboxObjectModel Root,
        string SerializeMethodName,
        string DeserializeMethodName);

    private static void CollectHelpers(
        OutboxObjectModel obj,
        Dictionary<string, OutboxObjectModel> objectModels,
        Dictionary<string, OutboxValueModel> collectionElements)
    {
        if (objectModels.ContainsKey(obj.HelperId)) return;
        objectModels.Add(obj.HelperId, obj);
        foreach (var member in obj.Members)
            CollectFromValue(member.Value, objectModels, collectionElements);
    }

    private static void CollectFromValue(
        OutboxValueModel value,
        Dictionary<string, OutboxObjectModel> objectModels,
        Dictionary<string, OutboxValueModel> collectionElements)
    {
        switch (value.Kind)
        {
            case OutboxValueKind.Object:
                CollectHelpers(value.ObjectModel!, objectModels, collectionElements);
                break;
            case OutboxValueKind.Collection:
                collectionElements[CollectionHelperId(value.Element!)] = value.Element!;
                CollectFromValue(value.Element!, objectModels, collectionElements);
                break;
        }
    }

    private static string CollectionHelperId(OutboxValueModel element) =>
        CreateIdentifierSuffix(element.LocalTypeName, "C_");

    private static void GenerateWriteObject(StringBuilder sb, OutboxObjectModel obj)
    {
        sb.AppendLine($"        private static void WriteObj_{obj.HelperId}(Utf8JsonWriter writer, {obj.TypeName} value)");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.WriteStartObject();");
        foreach (var member in obj.Members)
        {
            var jsonNameLiteral = SymbolDisplay.FormatLiteral(member.JsonName, true);
            sb.AppendLine($"            writer.WritePropertyName({jsonNameLiteral});");
            AppendWriteValue(sb, "            ", member.Value, $"value.{member.PropertyName}");
        }

        sb.AppendLine("            writer.WriteEndObject();");
        sb.AppendLine("        }");
    }

    private static void GenerateReadObject(StringBuilder sb, OutboxObjectModel obj)
    {
        sb.AppendLine($"        private static {obj.TypeName} ReadObj_{obj.HelperId}(ref Utf8JsonReader reader)");
        sb.AppendLine("        {");
        foreach (var member in obj.Members)
            sb.AppendLine($"            {member.Value.LocalTypeName} {member.LocalName} = {DefaultExpression(member.Value)};");

        sb.AppendLine();
        sb.AppendLine("            while (reader.Read())");
        sb.AppendLine("            {");
        sb.AppendLine("                if (reader.TokenType == JsonTokenType.EndObject) break;");
        sb.AppendLine("                if (reader.TokenType != JsonTokenType.PropertyName) { reader.Skip(); continue; }");
        sb.AppendLine();
        sb.AppendLine("                var propName = reader.GetString();");
        sb.AppendLine("                if (!reader.Read()) break;");
        sb.AppendLine();
        sb.AppendLine("                switch (propName)");
        sb.AppendLine("                {");
        foreach (var member in obj.Members)
        {
            var jsonNameLiteral = SymbolDisplay.FormatLiteral(member.JsonName, true);
            var propertyNameLiteral = SymbolDisplay.FormatLiteral(member.PropertyName, true);

            sb.AppendLine($"                    case {jsonNameLiteral}:");
            if (!string.Equals(member.JsonName, member.PropertyName, StringComparison.Ordinal))
                sb.AppendLine($"                    case {propertyNameLiteral}:");

            sb.AppendLine($"                        {member.LocalName} = {ReadValueExpression(member.Value)};");
            sb.AppendLine("                        break;");
        }

        sb.AppendLine("                    default:");
        sb.AppendLine("                        reader.Skip();");
        sb.AppendLine("                        break;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();

        var initAssignments = obj.Members
            .Where(m => m.CanInitialize && !m.IsConstructorParameter)
            .Select(m => $"{m.PropertyName} = {m.LocalName}")
            .ToArray();

        if (initAssignments.Length == 0)
        {
            sb.AppendLine($"            return {obj.ConstructorExpression};");
        }
        else
        {
            sb.AppendLine($"            return {obj.ConstructorExpression}");
            sb.AppendLine("            {");
            for (var i = 0; i < initAssignments.Length; i++)
            {
                var comma = i == initAssignments.Length - 1 ? string.Empty : ",";
                sb.AppendLine($"                {initAssignments[i]}{comma}");
            }

            sb.AppendLine("            };");
        }

        sb.AppendLine("        }");
    }

    private static void GenerateWriteCollection(StringBuilder sb, OutboxValueModel element)
    {
        var id = CollectionHelperId(element);
        sb.AppendLine($"        private static void WriteColl_{id}(Utf8JsonWriter writer, System.Collections.Generic.IEnumerable<{element.LocalTypeName}> value)");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.WriteStartArray();");
        sb.AppendLine("            foreach (var item in value)");
        sb.AppendLine("            {");
        AppendWriteValue(sb, "                ", element, "item");
        sb.AppendLine("            }");
        sb.AppendLine("            writer.WriteEndArray();");
        sb.AppendLine("        }");
    }

    private static void GenerateReadCollection(StringBuilder sb, OutboxValueModel element)
    {
        var id = CollectionHelperId(element);
        sb.AppendLine($"        private static System.Collections.Generic.List<{element.LocalTypeName}> ReadColl_{id}(ref Utf8JsonReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var items = new System.Collections.Generic.List<{element.LocalTypeName}>();");
        sb.AppendLine("            while (reader.Read())");
        sb.AppendLine("            {");
        sb.AppendLine("                if (reader.TokenType == JsonTokenType.EndArray) break;");
        sb.AppendLine($"                {element.LocalTypeName} item = {ReadValueExpression(element)};");
        sb.AppendLine("                items.Add(item);");
        sb.AppendLine("            }");
        sb.AppendLine("            return items;");
        sb.AppendLine("        }");
    }

    private static void AppendWriteValue(StringBuilder sb, string indent, OutboxValueModel value, string valueExpr)
    {
        if (value.IsNullableValueType)
        {
            sb.AppendLine($"{indent}if (({valueExpr}).HasValue)");
            sb.AppendLine($"{indent}{{");
            AppendWriteNonNullValue(sb, indent + "    ", value, $"({valueExpr}).Value");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}else");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    writer.WriteNullValue();");
            sb.AppendLine($"{indent}}}");
            return;
        }

        AppendWriteNonNullValue(sb, indent, value, valueExpr);
    }

    private static void AppendWriteNonNullValue(StringBuilder sb, string indent, OutboxValueModel value, string valueExpr)
    {
        switch (value.Kind)
        {
            case OutboxValueKind.Scalar:
                sb.AppendLine($"{indent}{ScalarWriteStatement(value.ScalarKind, valueExpr)}");
                return;
            case OutboxValueKind.Enum:
                sb.AppendLine($"{indent}writer.WriteNumberValue(({value.EnumUnderlyingTypeName}){valueExpr});");
                return;
            case OutboxValueKind.Object:
                if (value.IsReferenceType)
                {
                    sb.AppendLine($"{indent}if ({valueExpr} is null) writer.WriteNullValue();");
                    sb.AppendLine($"{indent}else WriteObj_{value.ObjectModel!.HelperId}(writer, {valueExpr});");
                }
                else
                {
                    sb.AppendLine($"{indent}WriteObj_{value.ObjectModel!.HelperId}(writer, {valueExpr});");
                }

                return;
            case OutboxValueKind.Collection:
                sb.AppendLine($"{indent}if ({valueExpr} is null) writer.WriteNullValue();");
                sb.AppendLine($"{indent}else WriteColl_{CollectionHelperId(value.Element!)}(writer, {valueExpr});");
                return;
        }
    }

    private static string ScalarWriteStatement(OutboxScalarKind kind, string valueExpr) =>
        kind switch
        {
            OutboxScalarKind.String => $"writer.WriteStringValue({valueExpr});",
            OutboxScalarKind.Guid => $"writer.WriteStringValue({valueExpr});",
            OutboxScalarKind.DateTime => $"writer.WriteStringValue({valueExpr});",
            OutboxScalarKind.DateTimeOffset => $"writer.WriteStringValue({valueExpr});",
            OutboxScalarKind.TimeSpan => $"writer.WriteStringValue({valueExpr}.ToString(\"c\", System.Globalization.CultureInfo.InvariantCulture));",
            OutboxScalarKind.Boolean => $"writer.WriteBooleanValue({valueExpr});",
            _ => $"writer.WriteNumberValue({valueExpr});"
        };

    private static string DefaultExpression(OutboxValueModel value)
    {
        if (value.Kind == OutboxValueKind.Scalar && value.ScalarKind == OutboxScalarKind.String)
            return value.IsNullableReferenceType ? "null" : "string.Empty";

        return $"default({value.LocalTypeName})";
    }

    private static string ReadValueExpression(OutboxValueModel value)
    {
        var read = NonNullReadExpression(value);
        return $"reader.TokenType == JsonTokenType.Null ? {DefaultExpression(value)} : {read}";
    }

    private static string NonNullReadExpression(OutboxValueModel value)
    {
        switch (value.Kind)
        {
            case OutboxValueKind.Scalar:
                if (value.ScalarKind == OutboxScalarKind.String)
                    return value.IsNullableReferenceType ? "reader.GetString()" : "(reader.GetString() ?? string.Empty)";
                if (value.ScalarKind == OutboxScalarKind.TimeSpan)
                    return "System.TimeSpan.ParseExact(reader.GetString() ?? \"00:00:00\", \"c\", System.Globalization.CultureInfo.InvariantCulture)";
                return ScalarReadExpression(value.ScalarKind);
            case OutboxValueKind.Enum:
                return $"({value.NonNullableTypeName})reader.{EnumReaderMethod(value.EnumUnderlyingTypeName)}()";
            case OutboxValueKind.Object:
                return $"ReadObj_{value.ObjectModel!.HelperId}(ref reader)";
            case OutboxValueKind.Collection:
                var read = $"ReadColl_{CollectionHelperId(value.Element!)}(ref reader)";
                return value.CollectionIsArray ? read + ".ToArray()" : read;
            default:
                return "default";
        }
    }

    private static string ScalarReadExpression(OutboxScalarKind kind) =>
        kind switch
        {
            OutboxScalarKind.Guid => "reader.GetGuid()",
            OutboxScalarKind.DateTime => "reader.GetDateTime()",
            OutboxScalarKind.DateTimeOffset => "reader.GetDateTimeOffset()",
            OutboxScalarKind.Boolean => "reader.GetBoolean()",
            OutboxScalarKind.Byte => "reader.GetByte()",
            OutboxScalarKind.SByte => "reader.GetSByte()",
            OutboxScalarKind.Int16 => "reader.GetInt16()",
            OutboxScalarKind.UInt16 => "reader.GetUInt16()",
            OutboxScalarKind.Int32 => "reader.GetInt32()",
            OutboxScalarKind.UInt32 => "reader.GetUInt32()",
            OutboxScalarKind.Int64 => "reader.GetInt64()",
            OutboxScalarKind.UInt64 => "reader.GetUInt64()",
            OutboxScalarKind.Single => "reader.GetSingle()",
            OutboxScalarKind.Double => "reader.GetDouble()",
            OutboxScalarKind.Decimal => "reader.GetDecimal()",
            _ => "reader.GetInt32()"
        };

    private static string EnumReaderMethod(string? enumUnderlyingTypeName) =>
        enumUnderlyingTypeName switch
        {
            "global::System.Byte" => "GetByte",
            "global::System.SByte" => "GetSByte",
            "global::System.Int16" => "GetInt16",
            "global::System.UInt16" => "GetUInt16",
            "global::System.Int32" => "GetInt32",
            "global::System.UInt32" => "GetUInt32",
            "global::System.Int64" => "GetInt64",
            "global::System.UInt64" => "GetUInt64",
            _ => "GetInt32"
        };
}
