using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    // CQRGEN006 (F71): a concrete handler that is too inaccessible for generated registration is silently dropped,
    // which surfaces only as a confusing "no handler" at the call site. Flag it at the declaration instead.
    private static readonly DiagnosticDescriptor HandlerNotAccessibleDiagnostic = new(
        "CQRGEN006",
        "Handler is not accessible to generated registration",
        "'{0}' implements a CQRSharp handler interface but is less accessible than internal, so it is skipped by generated registration. Make it public or internal (and not nested in a less-accessible type), or register it manually.",
        "CQRSharp.Generators",
        DiagnosticSeverity.Warning,
        true);

    /// <summary>
    ///     Emits one assembly-level marker attribute per handled request and per handled notification, so the CQRSharp
    ///     analyzers can discover handlers across referenced assemblies (not just the current compilation).
    /// </summary>
    private static string GenerateAssemblyMarkers(ImmutableArray<CandidateModel> candidates, KnownSnapshot known, bool hasModule)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // The module marker: lets a composition root in a referencing assembly discover and wire this assembly's
        // generated module at compile time. Emitted whenever this assembly contributes a module.
        if (hasModule)
            sb.AppendLine(
                $"[assembly: global::CQRSharp.Abstractions.Attributes.SourceGeneration.CqrsGeneratedModule(typeof(global::{known.ModuleNamespace}.CqrsModuleRegistrar))]");

        var handledRequests = candidates
            .SelectMany(c => c.Handlers)
            .Select(h => h.RequestTypeName)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(t => t, StringComparer.Ordinal);

        foreach (var request in handledRequests)
            sb.AppendLine($"[assembly: global::CQRSharp.Abstractions.Attributes.SourceGeneration.CqrsHandledRequest(typeof({request}))]");

        var handledNotifications = candidates
            .SelectMany(c => c.HandledNotifications)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(t => t, StringComparer.Ordinal);

        foreach (var notification in handledNotifications)
            sb.AppendLine($"[assembly: global::CQRSharp.Abstractions.Attributes.SourceGeneration.CqrsHandledNotification(typeof({notification}))]");

        // One marker per context type that has a discovered IRequestContextFactory, so CQRA011 can see factories
        // declared in referenced assemblies (the current compilation's factories are found by scanning its own source).
        var registeredContextFactories = candidates
            .SelectMany(c => c.ContextFactories)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(t => t, StringComparer.Ordinal);

        foreach (var contextType in registeredContextFactories)
            sb.AppendLine($"[assembly: global::CQRSharp.Abstractions.Attributes.SourceGeneration.CqrsRegisteredContextFactory(typeof({contextType}))]");

        return sb.ToString();
    }
}
