using System.Text;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    private static string GenerateBootstrap(KnownSnapshot known)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using CQRSharp.Core.Options;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Extensions");
        sb.AppendLine("{");
        EmitSummary(sb, "    ", "One-call source-generated bootstrap that registers CQRSharp and its generated handlers and dispatchers together.");
        sb.AppendLine("    public static class CqrsGeneratedBootstrap");
        sb.AppendLine("    {");
        EmitSummary(sb, "        ", "Registers CQRSharp (<c>AddCqrs</c>) and the source-generated handlers and dispatchers (<c>AddGenerated</c>) in a single call, optionally configuring the background queue, outbox, dispatcher, and startup validation.");
        sb.AppendLine(
            "        public static IServiceCollection AddCqrsGenerated(this IServiceCollection services, Action<BackgroundTaskQueueOptions>? configureQueue = null, Action<OutboxOptions>? configureOutbox = null, Action<DispatcherOptions>? configureDispatcher = null, Action<CqrsStartupValidationOptions>? configureValidation = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(services);");
        sb.AppendLine();
        sb.AppendLine("            services.AddCqrs(configureQueue, configureOutbox, configureDispatcher, configureValidation);");
        sb.AppendLine("            services.AddGenerated();");
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");

        // Bridge overload: only emit when the consumer references CQRSharp.Pipelines (so its ICqrsBuilder type is
        // resolvable). Core does not reference Pipelines, but the consumer assembly — where this code is emitted —
        // references both, so a generated overload can legally bridge them. Core-only/abstractions-only consumers,
        // where ICqrsBuilder is absent, simply do not get this overload and still compile.
        if (known.HasPipelinesBuilder)
        {
            sb.AppendLine();
            EmitSummary(sb, "        ", "Registers CQRSharp and the source-generated handlers and dispatchers, configuring the pipeline through the fluent <c>ICqrsBuilder</c> (verb order does not matter).");
            sb.AppendLine(
                "        public static IServiceCollection AddCqrsGenerated(this IServiceCollection services, System.Action<global::CQRSharp.Pipelines.Extensions.ICqrsBuilder> configure)");
            sb.AppendLine("        {");
            sb.AppendLine("            ArgumentNullException.ThrowIfNull(services);");
            sb.AppendLine("            ArgumentNullException.ThrowIfNull(configure);");
            sb.AppendLine();
            sb.AppendLine("            // useGenerated forced on: this entry point owns the generated registrations.");
            sb.AppendLine(
                "            var builder = new global::CQRSharp.Pipelines.Extensions.CqrsBuilder(services, useGenerated: true);");
            sb.AppendLine("            configure(builder);");
            sb.AppendLine();
            sb.AppendLine("            // Build() runs the canonical AddCqrs(...)/pack sequence (order-insensitive). Apply the");
            sb.AppendLine("            // generated registrations after so their RemoveAll-authoritative dispatchers win, leaving a");
            sb.AppendLine("            // fully-working ICqrsDispatcher resolvable regardless of the verb order the consumer used.");
            sb.AppendLine("            builder.Build();");
            sb.AppendLine("            services.AddGenerated();");
            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
