using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    // Emits GeneratedCqrsNotificationRegistry: the compile-time notification surface used by configuration
    // inspection. HandledNotificationTypes is every concrete notification (a class implementing INotification);
    // HasStableName is a typeof()==typeof() chain over the stable-named ones (same set the outbox serializer
    // recognizes). Always emitted, even with zero notifications, so DI always has an implementation to inject.
    private static string GenerateNotificationRegistry(
        ImmutableArray<CandidateModel> candidates,
        IReadOnlyList<NotificationModel> stableNotifications)
    {
        var notificationTypeNames = candidates
            .Where(c => c.Notification is not null)
            .Select(c => c.Notification!.TypeName)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using CQRSharp.Core.Diagnostics;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Diagnostics.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class GeneratedCqrsNotificationRegistry : ICqrsNotificationRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly Type[] _handled = new Type[]");
        sb.AppendLine("        {");
        foreach (var typeName in notificationTypeNames)
            sb.AppendLine($"            typeof({typeName}),");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public IReadOnlyList<Type> HandledNotificationTypes => _handled;");
        sb.AppendLine();
        sb.AppendLine("        public bool HasStableName(Type notificationType)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(notificationType);");
        foreach (var notification in stableNotifications)
            sb.AppendLine($"            if (notificationType == typeof({notification.TypeName})) return true;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
