using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Shared;
using Microsoft.CodeAnalysis;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    // CQRGEN006 (F71): a concrete handler that is too inaccessible for generated registration is silently dropped,
    // which surfaces only as a confusing "no handler" at the call site. Flag it at the declaration instead.
    private static readonly DiagnosticDescriptor HandlerNotAccessibleDiagnostic = new(
        "CQRGEN006",
        "Handler is not accessible to generated registration",
        "'{0}' implements a CQRSharp handler interface but is less accessible than internal, so it is skipped by generated registration. Make it public or internal (and not nested in a less-accessible type), or register it manually.",
        "CQRSharp.Generators",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    /// <summary>
    ///     Emits one assembly-level marker attribute per handled request and per handled notification, so the CQRSharp
    ///     analyzers can discover handlers across referenced assemblies (not just the current compilation).
    /// </summary>
    private static string GenerateAssemblyMarkers(Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var bindings = CollectHandlerBindings(compilation, candidateClasses);
        var handledRequests = bindings.Values
            .Where(list => list.Count > 0)
            .Select(list => SelectDeterministicBinding(list).RequestType)
            .Where(IsAccessibleFromGeneratedCode)
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<ITypeSymbol>()
            .OrderBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal);

        foreach (var request in handledRequests)
        {
            var name = request.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"[assembly: global::CQRSharp.Abstractions.Attributes.SourceGeneration.CqrsHandledRequest(typeof({name}))]");
        }

        var notificationHandlerDef = CqrsKnownSymbols.For(compilation).INotificationHandler;
        if (notificationHandlerDef is not null)
        {
            var handledNotifications = candidateClasses
                .Where(c => c is { IsAbstract: false, IsGenericType: false } && IsAccessibleFromGeneratedCode(c))
                .SelectMany(GetInterfacesAndBaseInterfaces)
                .Where(i => i is { IsGenericType: true, TypeArguments.Length: 1 } &&
                            SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, notificationHandlerDef))
                .Select(i => i.TypeArguments[0])
                .Where(t => t is not null && IsAccessibleFromGeneratedCode(t))
                .Select(t => t!)
                .Distinct(SymbolEqualityComparer.Default)
                .Cast<ITypeSymbol>()
                .OrderBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal);

            foreach (var notification in handledNotifications)
            {
                var name = notification.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"[assembly: global::CQRSharp.Abstractions.Attributes.SourceGeneration.CqrsHandledNotification(typeof({name}))]");
            }
        }

        return sb.ToString();
    }

    /// <summary>
    ///     Reports CQRGEN006 for each concrete handler implementation that is dropped from generated registration
    ///     solely because it (or a containing type) is less accessible than <c>internal</c>.
    /// </summary>
    private static void ReportInaccessibleHandlers(
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> candidateClasses,
        SourceProductionContext context)
    {
        var knownHandlers = GetAllKnownHandlerSymbols(compilation)
            .Select(s => s!.OriginalDefinition)
            .ToArray();
        if (knownHandlers.Length == 0) return;

        foreach (var candidate in candidateClasses)
        {
            if (candidate is not { IsAbstract: false, IsGenericType: false }) continue;
            if (IsAccessibleFromGeneratedCode(candidate)) continue;

            var implementsHandler = GetInterfacesAndBaseInterfaces(candidate)
                .Any(iface => iface.IsGenericType &&
                              knownHandlers.Contains(iface.OriginalDefinition, SymbolEqualityComparer.Default));
            if (!implementsHandler) continue;

            var location = candidate.Locations.FirstOrDefault(l => l.IsInSource) ?? Location.None;
            context.ReportDiagnostic(Diagnostic.Create(
                HandlerNotAccessibleDiagnostic,
                location,
                candidate.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
        }
    }
}
