using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    private static string GenerateNotificationDispatcher(ImmutableArray<CandidateModel> candidates)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Notifications;");
        sb.AppendLine("using CQRSharp.Core.Notifications;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Notifications.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class GeneratedDirectNotificationDispatcher(IServiceProvider services) : DirectNotificationDispatcher(services)");
        sb.AppendLine("    {");
        sb.AppendLine("        public override Task Publish(INotification notification, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(notification);");
        sb.AppendLine("            return notification switch");
        sb.AppendLine("            {");

        var notificationTypes = candidates
            .SelectMany(c => c.HandledNotifications)
            .Distinct(System.StringComparer.Ordinal)
            .OrderBy(t => t)
            .ToArray();

        foreach (var typeName in notificationTypes)
            sb.AppendLine($"                {typeName} n => Publish(n, cancellationToken),");

        sb.AppendLine("                _ => Task.CompletedTask");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
