using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Shared;
using Microsoft.CodeAnalysis;

namespace CQRSharp.Generators.CqrsSourceGenerator;

public sealed partial class CqrsSourceGenerator
{
    private static readonly SymbolDisplayFormat FullyQualifiedNullableTypeFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly DiagnosticDescriptor MissingRequestHandlerDiagnostic = new(
        "CQRGEN003",
        "No handler found for request",
        "No handler found for request '{0}'. Add exactly one handler or suppress this warning if the handler is in another assembly.",
        "CQRSharp.Generators",
        DiagnosticSeverity.Warning,
        true);

    private static readonly DiagnosticDescriptor MultipleRequestHandlersDiagnostic = new(
        "CQRGEN004",
        "Multiple handlers found for request",
        "Multiple handlers found for request '{0}': {1}. CQRSharp requires exactly one handler per request.",
        "CQRSharp.Generators",
        DiagnosticSeverity.Error,
        true);

    private static string GenerateRegistrations(
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> candidateClasses,
        StableNotificationInfo[] stableNotifications,
        SourceProductionContext context,
        GeneratorConfig config)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Notifications;");
        sb.AppendLine("using CQRSharp.Abstractions.Models.Requests;");
        sb.AppendLine("using CQRSharp.Core.Caching.Requests;");
        sb.AppendLine("using CQRSharp.Core.Caching.Handlers;");
        sb.AppendLine("using CQRSharp.Core.Caching.Contexts;");
        sb.AppendLine("using CQRSharp.Core.Factories;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Extensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static class CqrsGeneratedRegistrations");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddGenerated(this IServiceCollection services)");
        sb.AppendLine("        {");

        var handlerBindingsByRequest = CollectHandlerBindings(compilation, candidateClasses);

        GenerateHandlerServices(sb, compilation, candidateClasses);
        GenerateRequestRegistry(sb, compilation, candidateClasses, context, handlerBindingsByRequest, config);
        GenerateHandlerRegistry(sb, handlerBindingsByRequest);
        GenerateContextFactoryRegistry(sb, compilation, candidateClasses);
        GenerateRequestExceptionHookRegistry(sb, compilation, candidateClasses);

        sb.AppendLine();
        sb.AppendLine("            // Registering the generated dispatchers. RemoveAll first so the generated implementations");
        sb.AppendLine("            // are authoritative regardless of AddCqrs/AddGenerated ordering, and so re-invoking");
        sb.AppendLine("            // AddGenerated is idempotent rather than stacking duplicate registrations.");
        sb.AppendLine(
            "            services.RemoveAll<global::CQRSharp.Core.Diagnostics.ICqrsDiagnostics>();");
        sb.AppendLine(
            "            services.AddScoped<global::CQRSharp.Core.Diagnostics.ICqrsDiagnostics, global::CQRSharp.Core.Diagnostics.Generated.GeneratedCqrsDiagnostics>();");
        sb.AppendLine(
            "            services.RemoveAll<global::CQRSharp.Core.Notifications.IDirectNotificationDispatcher>();");
        sb.AppendLine(
            "            services.AddScoped<global::CQRSharp.Core.Notifications.IDirectNotificationDispatcher, global::CQRSharp.Core.Notifications.Generated.GeneratedDirectNotificationDispatcher>();");
        sb.AppendLine(
            "            services.RemoveAll<global::CQRSharp.Core.Pipelines.IRequestDispatcher>();");
        sb.AppendLine(
            "            services.AddScoped<global::CQRSharp.Core.Pipelines.IRequestDispatcher, global::CQRSharp.Core.Requests.Generated.GeneratedRequestDispatcher>();");
        sb.AppendLine(
            "            services.RemoveAll<global::CQRSharp.Core.Pipelines.IStreamRequestDispatcher>();");
        sb.AppendLine(
            "            services.AddScoped<global::CQRSharp.Core.Pipelines.IStreamRequestDispatcher, global::CQRSharp.Core.Streams.Generated.GeneratedStreamRequestDispatcher>();");

        if (stableNotifications.Length > 0)
        {
            sb.AppendLine();
            sb.AppendLine("            // Register the generated outbox notification serializer.");
            sb.AppendLine(
                "            services.TryAddSingleton<global::CQRSharp.Abstractions.Interfaces.Notifications.INotificationSerializer, global::CQRSharp.Core.Serialization.Generated.GeneratedOutboxNotificationSerializer>();");
            sb.AppendLine(
                "            services.TryAddSingleton<global::CQRSharp.Abstractions.Interfaces.Notifications.IStableNotificationNameProvider, global::CQRSharp.Core.Serialization.Generated.GeneratedOutboxNotificationSerializer>();");
        }

        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateRequestExceptionHookRegistry(
        StringBuilder sb,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Request Exception Hook Registry");
        sb.AppendLine(
            "            var exceptionHookMappings = new ConcurrentDictionary<Type, global::CQRSharp.Core.Exceptions.RequestExceptionHookInvoker>();");

        var exceptionActionDef =
            CqrsKnownSymbols.For(compilation).IRequestExceptionAction2;
        var exceptionHandlerDef =
            CqrsKnownSymbols.For(compilation).IRequestExceptionHandler3;
        var commandSymbol = CqrsKnownSymbols.For(compilation).ICommand;
        var querySymbol = CqrsKnownSymbols.For(compilation).IQuery;
        var streamRequestSymbol = CqrsKnownSymbols.For(compilation).IStreamRequest;
        var asyncEnumerableSymbol = compilation.GetTypeByMetadataName("System.Collections.Generic.IAsyncEnumerable`1");
        var commandResultSymbol = CqrsKnownSymbols.For(compilation).CommandResult;
        var systemExceptionSymbol = compilation.GetTypeByMetadataName("System.Exception");

        if (exceptionActionDef is null ||
            exceptionHandlerDef is null ||
            commandSymbol is null ||
            querySymbol is null ||
            commandResultSymbol is null ||
            systemExceptionSymbol is null)
        {
            sb.AppendLine(
                "            services.AddSingleton<global::CQRSharp.Core.Exceptions.IRequestExceptionHookRegistry, global::CQRSharp.Core.Exceptions.RequestExceptionHookRegistry>();");
            return;
        }

        var hooksByRequest =
            new Dictionary<ITypeSymbol, Dictionary<ITypeSymbol, ExceptionHookKind>>(SymbolEqualityComparer.Default);

        void RecordHook(ITypeSymbol requestType, ITypeSymbol exceptionType, ExceptionHookKind kind)
        {
            if (!hooksByRequest.TryGetValue(requestType, out var byException))
            {
                byException = new Dictionary<ITypeSymbol, ExceptionHookKind>(SymbolEqualityComparer.Default);
                hooksByRequest.Add(requestType, byException);
            }

            byException.TryGetValue(exceptionType, out var existing);
            byException[exceptionType] = existing | kind;
        }

        static bool IsConcrete(INamedTypeSymbol type) => type is { IsAbstract: false, IsGenericType: false };

        static bool IsExceptionType(ITypeSymbol exceptionType, INamedTypeSymbol systemExceptionSymbol)
        {
            for (var current = exceptionType; current is not null; current = current.BaseType)
                if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, systemExceptionSymbol.OriginalDefinition))
                    return true;

            return false;
        }

        foreach (var implementation in candidateClasses.Where(c => IsConcrete(c) && IsAccessibleFromGeneratedCode(c)))
        foreach (var iface in GetInterfacesAndBaseInterfaces(implementation))
        {
            if (!iface.IsGenericType) continue;

            if (SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, exceptionActionDef))
            {
                if (iface.TypeArguments.Length < 2) continue;
                var requestType = iface.TypeArguments[0];
                var exceptionType = iface.TypeArguments[1];

                if (!IsAccessibleFromGeneratedCode(requestType) ||
                    !IsAccessibleFromGeneratedCode(exceptionType) ||
                    !IsExceptionType(exceptionType, systemExceptionSymbol))
                    continue;

                RecordHook(requestType, exceptionType, ExceptionHookKind.Action);
            }
            else if (SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, exceptionHandlerDef))
            {
                if (iface.TypeArguments.Length < 3) continue;
                var requestType = iface.TypeArguments[0];
                var exceptionType = iface.TypeArguments[2];

                if (!IsAccessibleFromGeneratedCode(requestType) ||
                    !IsAccessibleFromGeneratedCode(exceptionType) ||
                    !IsExceptionType(exceptionType, systemExceptionSymbol))
                    continue;

                RecordHook(requestType, exceptionType, ExceptionHookKind.Handler);
            }
        }

        static int GetInheritanceDepth(ITypeSymbol type)
        {
            var depth = 0;
            for (var current = type.BaseType; current is not null; current = current.BaseType)
                depth++;
            return depth;
        }

        foreach (var requestEntry in hooksByRequest
                     .OrderBy(k => k.Key.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal))
        {
            if (requestEntry.Key is not INamedTypeSymbol requestSymbol) continue;

            var isCommand = requestSymbol.AllInterfaces.Contains(commandSymbol, SymbolEqualityComparer.Default);
            var queryInterface = requestSymbol.AllInterfaces
                .FirstOrDefault(i => i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, querySymbol));

            var streamInterface = streamRequestSymbol is null
                ? null
                : requestSymbol.AllInterfaces.FirstOrDefault(i =>
                    i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, streamRequestSymbol));

            if (!isCommand && queryInterface is null && streamInterface is null) continue;

            ITypeSymbol resultType;
            if (streamInterface is not null)
            {
                if (asyncEnumerableSymbol is null) continue;
                resultType = asyncEnumerableSymbol.Construct(streamInterface.TypeArguments[0]);
            }
            else
            {
                resultType = (ITypeSymbol)(queryInterface?.TypeArguments[0] ?? commandResultSymbol);
            }

            if (!IsAccessibleFromGeneratedCode(resultType)) continue;

            var requestTypeName = requestSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var resultTypeName = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine($"            exceptionHookMappings.TryAdd(typeof({requestTypeName}), async (sp, request, exception, ct) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var typedRequest = ({requestTypeName})request;");

            foreach (var exceptionEntry in requestEntry.Value
                         .OrderByDescending(e => GetInheritanceDepth(e.Key))
                         .ThenBy(e => e.Key.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal))
            {
                if (exceptionEntry.Key is not INamedTypeSymbol exceptionSymbol) continue;

                var exceptionTypeName = exceptionSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var kind = exceptionEntry.Value;

                sb.AppendLine("                {");
                sb.AppendLine($"                    if (exception is {exceptionTypeName} typedException)");
                sb.AppendLine("                    {");

                if ((kind & ExceptionHookKind.Action) != 0)
                {
                    sb.AppendLine(
                        $"                        var actions = sp.GetServices<global::CQRSharp.Abstractions.Interfaces.Exceptions.IRequestExceptionAction<{requestTypeName}, {exceptionTypeName}>>();");
                    sb.AppendLine("                        foreach (var action in actions)");
                    sb.AppendLine("                            await action.Execute(typedRequest, typedException, ct).ConfigureAwait(false);");
                }

                if ((kind & ExceptionHookKind.Handler) != 0)
                {
                    sb.AppendLine(
                        $"                        var handlers = sp.GetServices<global::CQRSharp.Abstractions.Interfaces.Exceptions.IRequestExceptionHandler<{requestTypeName}, {resultTypeName}, {exceptionTypeName}>>();");
                    sb.AppendLine(
                        $"                        var state = new global::CQRSharp.Abstractions.Models.Exceptions.RequestExceptionHandlerState<{resultTypeName}>();");
                    sb.AppendLine("                        foreach (var handler in handlers)");
                    sb.AppendLine("                        {");
                    sb.AppendLine("                            await handler.Handle(typedRequest, typedException, state, ct).ConfigureAwait(false);");
                    sb.AppendLine("                            if (!state.Handled) continue;");
                    sb.AppendLine(
                        "                            return global::CQRSharp.Core.Exceptions.RequestExceptionHandlingOutcome.HandledWith(state.Response);");
                    sb.AppendLine("                        }");
                }

                sb.AppendLine("                    }");
                sb.AppendLine("                }");
            }

            sb.AppendLine("                return global::CQRSharp.Core.Exceptions.RequestExceptionHandlingOutcome.NotHandled;");
            sb.AppendLine("            });");
        }

        sb.AppendLine(
            "            services.RemoveAll<global::CQRSharp.Core.Exceptions.IRequestExceptionHookRegistry>();");
        sb.AppendLine(
            "            services.AddSingleton<global::CQRSharp.Core.Exceptions.IRequestExceptionHookRegistry>(new global::CQRSharp.Core.Exceptions.RequestExceptionHookRegistry(exceptionHookMappings));");
    }

    private static Dictionary<string, List<HandlerBinding>> CollectHandlerBindings(
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        var commandHandlerDef = CqrsKnownSymbols.For(compilation).ICommandHandler2;
        var queryHandlerDef = CqrsKnownSymbols.For(compilation).IQueryHandler3;
        var streamHandlerDef = CqrsKnownSymbols.For(compilation).IStreamRequestHandler3;
        var asyncEnumerableDef = compilation.GetTypeByMetadataName("System.Collections.Generic.IAsyncEnumerable`1");

        var bindingsByRequest = new Dictionary<string, List<HandlerBinding>>(StringComparer.Ordinal);
        if (commandHandlerDef is null || queryHandlerDef is null) return bindingsByRequest;

        foreach (var handlerImplementation in candidateClasses
                     .Where(c => c is { IsAbstract: false, IsGenericType: false } && IsAccessibleFromGeneratedCode(c)))
        foreach (var iface in GetInterfacesAndBaseInterfaces(handlerImplementation))
        {
            if (!iface.IsGenericType) continue;

            if (SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, commandHandlerDef))
            {
                if (iface.TypeArguments.Length < 2) continue;
                var requestType = iface.TypeArguments[0];
                var contextType = iface.TypeArguments[1];

                if (!IsAccessibleFromGeneratedCode(requestType) || !IsAccessibleFromGeneratedCode(contextType))
                    continue;

                AddHandlerBinding(
                    bindingsByRequest,
                    requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    new HandlerBinding(handlerImplementation, iface, requestType, null, false));
            }
            else if (SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, queryHandlerDef))
            {
                if (iface.TypeArguments.Length < 3) continue;
                var requestType = iface.TypeArguments[0];
                var resultType = iface.TypeArguments[1];
                var contextType = iface.TypeArguments[2];

                if (!IsAccessibleFromGeneratedCode(requestType) ||
                    !IsAccessibleFromGeneratedCode(resultType) ||
                    !IsAccessibleFromGeneratedCode(contextType))
                    continue;

                AddHandlerBinding(
                    bindingsByRequest,
                    requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    new HandlerBinding(handlerImplementation, iface, requestType, resultType, false));
            }
            else if (streamHandlerDef is not null &&
                     asyncEnumerableDef is not null &&
                     SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, streamHandlerDef))
            {
                if (iface.TypeArguments.Length < 3) continue;
                var requestType = iface.TypeArguments[0];
                var itemType = iface.TypeArguments[1];
                var contextType = iface.TypeArguments[2];

                if (!IsAccessibleFromGeneratedCode(requestType) ||
                    !IsAccessibleFromGeneratedCode(itemType) ||
                    !IsAccessibleFromGeneratedCode(contextType))
                    continue;

                var streamResultType = asyncEnumerableDef.Construct(itemType);

                AddHandlerBinding(
                    bindingsByRequest,
                    requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    new HandlerBinding(handlerImplementation, iface, requestType, streamResultType, true));
            }
        }

        return bindingsByRequest;
    }

    private static void AddHandlerBinding(
        Dictionary<string, List<HandlerBinding>> bindingsByRequest,
        string requestKey,
        HandlerBinding binding)
    {
        if (!bindingsByRequest.TryGetValue(requestKey, out var bindings))
        {
            bindings = new List<HandlerBinding>();
            bindingsByRequest.Add(requestKey, bindings);
        }

        bindings.Add(binding);
    }

    private static HandlerBinding SelectDeterministicBinding(List<HandlerBinding> bindings)
    {
        return bindings
            .OrderBy(b => b.HandlerImplementation.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
            .ThenBy(b => b.HandlerInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
            .First();
    }

    private static void GenerateHandlerServices(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Handler Services by Interface Implementation.");
        sb.AppendLine("            // The concrete handler is what dispatch resolves (via the request registry); the interface");
        sb.AppendLine("            // forwarders below are kept so consumers can also resolve a handler by its interface directly.");

        var allKnownHandlers = GetAllKnownHandlerSymbols(compilation)
            .Select(s => s!.OriginalDefinition)
            .ToArray();

        if (!allKnownHandlers.Any()) return;

        var handlerImplementations = candidateClasses
            .Where(c => c is { IsAbstract: false, IsGenericType: false } &&
                        IsAccessibleFromGeneratedCode(c) &&
                        GetInterfacesAndBaseInterfaces(c).Any(iface => iface.IsGenericType && allKnownHandlers.Contains(iface.OriginalDefinition, SymbolEqualityComparer.Default)))
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>();

        foreach (var implementationSymbol in handlerImplementations)
        {
            var implementationTypeName = implementationSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            services.AddTransient(typeof({implementationTypeName}));");

            var implementedInterfaces = GetInterfacesAndBaseInterfaces(implementationSymbol)
                .Where(iface => iface.IsGenericType && allKnownHandlers.Contains(iface.OriginalDefinition, SymbolEqualityComparer.Default));

            foreach (var iface in implementedInterfaces)
            {
                var interfaceTypeName = iface.ToDisplayString(FullyQualifiedNullableTypeFormat);
                sb.AppendLine($"            services.AddTransient(typeof({interfaceTypeName}), sp => sp.GetRequiredService<{implementationTypeName}>());");
            }
        }
    }

    private static void GenerateRequestRegistry(
        StringBuilder sb,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> candidateClasses,
        SourceProductionContext context,
        Dictionary<string, List<HandlerBinding>> handlerBindingsByRequest,
        GeneratorConfig config)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Request Registry");
        sb.AppendLine("            var requestMetadataMappings = new ConcurrentDictionary<Type, RequestMetadata>();");

        var preHandlerInterfaceSymbol = CqrsKnownSymbols.For(compilation).IPreHandlerAttribute;
        var postHandlerInterfaceSymbol = CqrsKnownSymbols.For(compilation).IPostHandlerAttribute;
        var pipelineExemptionAttributeSymbol = CqrsKnownSymbols.For(compilation).PipelineExemptionAttribute;

        if (preHandlerInterfaceSymbol is null || postHandlerInterfaceSymbol is null || pipelineExemptionAttributeSymbol is null)
            return;

        // Diagnostics: request types declared in this compilation should have exactly one handler.
        var commandSymbol = CqrsKnownSymbols.For(compilation).ICommand;
        var querySymbol = CqrsKnownSymbols.For(compilation).IQuery;
        var streamRequestSymbol = CqrsKnownSymbols.For(compilation).IStreamRequest;
        if (!config.SuppressMissingRequestHandlerDiagnostics &&
            commandSymbol is not null && querySymbol is not null)
        {
            var declaredRequestTypes = candidateClasses
                .Where(c => c is { IsAbstract: false, IsGenericType: false } &&
                            IsAccessibleFromGeneratedCode(c) &&
                            (c.AllInterfaces.Contains(commandSymbol, SymbolEqualityComparer.Default) ||
                             c.AllInterfaces.Any(i => i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, querySymbol)) ||
                             (streamRequestSymbol is not null &&
                              c.AllInterfaces.Any(i => i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, streamRequestSymbol)))))
                .ToArray();

            foreach (var requestType in declaredRequestTypes)
            {
                var requestKey = requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (handlerBindingsByRequest.ContainsKey(requestKey)) continue;

                var location = requestType.Locations.FirstOrDefault(l => l.IsInSource) ?? Location.None;
                context.ReportDiagnostic(Diagnostic.Create(MissingRequestHandlerDiagnostic, location, requestKey));
            }
        }

        foreach (var kvp in handlerBindingsByRequest.OrderBy(pair => pair.Key, StringComparer.Ordinal))
        {
            var requestKey = kvp.Key;
            var bindings = kvp.Value;
            if (bindings.Count == 0) continue;

            var selected = SelectDeterministicBinding(bindings);

            if (bindings.Count > 1)
            {
                var descriptions = string.Join(
                    ", ",
                    bindings
                        .OrderBy(b => b.HandlerImplementation.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
                        .ThenBy(b => b.HandlerInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
                        .Select(b =>
                            $"{b.HandlerImplementation.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} ({b.HandlerInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})"));

                var location = selected.HandlerImplementation.Locations.FirstOrDefault(l => l.IsInSource) ?? Location.None;
                context.ReportDiagnostic(Diagnostic.Create(MultipleRequestHandlersDiagnostic, location, requestKey, descriptions));
            }

            var handlerImplementationName = selected.HandlerImplementation.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var requestTypeSymbol = selected.RequestType;
            var requestTypeName = requestTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var preHandlersCode = GenerateAttributeArrayCode(requestTypeSymbol, preHandlerInterfaceSymbol,
                preHandlerInterfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            var postHandlersCode = GenerateAttributeArrayCode(requestTypeSymbol, postHandlerInterfaceSymbol,
                postHandlerInterfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            var pipelineExemptionsCode = GenerateAttributeArrayCode(requestTypeSymbol, pipelineExemptionAttributeSymbol,
                pipelineExemptionAttributeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));

            var resultTypeCode = selected.ResultType is not null
                ? $"typeof({selected.ResultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})"
                : "null";

            var defaultContextType = CqrsKnownSymbols.For(compilation).RequestContextBase;
            var contextTypeSymbol = GetRequestContextType(requestTypeSymbol, compilation) ?? defaultContextType;
            if (contextTypeSymbol is null || !IsAccessibleFromGeneratedCode(contextTypeSymbol))
                contextTypeSymbol = defaultContextType;

            var contextTypeName = contextTypeSymbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "global::System.Object";

            sb.AppendLine(
                $"            requestMetadataMappings.TryAdd(typeof({requestTypeName}), new RequestMetadata(typeof({requestTypeName}), typeof({handlerImplementationName}), {preHandlersCode}, {postHandlersCode}, {pipelineExemptionsCode}, {resultTypeCode}, typeof({contextTypeName})));");
        }

        sb.AppendLine("            services.AddSingleton<IRequestRegistry>(new RequestRegistry(requestMetadataMappings));");
    }

    private static void GenerateHandlerRegistry(StringBuilder sb, Dictionary<string, List<HandlerBinding>> handlerBindingsByRequest)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Handler Registry");
        sb.AppendLine("            var handlerInvokerMappings = new ConcurrentDictionary<Type, HandlerInvokerDelegate>();");

        foreach (var kvp in handlerBindingsByRequest.OrderBy(pair => pair.Key, StringComparer.Ordinal))
        {
            var bindings = kvp.Value;
            if (bindings.Count == 0) continue;
            var selected = SelectDeterministicBinding(bindings);

            var requestType = selected.RequestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var handlerInterface = selected.HandlerInterface.ToDisplayString(FullyQualifiedNullableTypeFormat);
            var invokerLambda = selected.IsStream
                ? $"(handler, request, ct) => global::System.Threading.Tasks.Task.FromResult((object?)(({handlerInterface})handler).Handle(({requestType})request, ct))"
                : $"async (handler, request, ct) => (object?)await (({handlerInterface})handler).Handle(({requestType})request, ct).ConfigureAwait(false)";
            sb.AppendLine($"            handlerInvokerMappings.TryAdd(typeof({requestType}), {invokerLambda});");
        }

        sb.AppendLine("            services.AddSingleton<IHandlerRegistry>(new HandlerRegistry(handlerInvokerMappings));");
    }

    private static void GenerateContextFactoryRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Context Factory Registry");
        sb.AppendLine("            var factoryMappings = new ConcurrentDictionary<Type, Func<System.IServiceProvider, object?>>();");

        var factoryInterfaceSymbol = CqrsKnownSymbols.For(compilation).IRequestContextFactory;
        if (factoryInterfaceSymbol is null) return;

        var contextTypes = candidateClasses
            .Where(c => c is { IsAbstract: false } && IsAccessibleFromGeneratedCode(c))
            .SelectMany(c => GetInterfacesAndBaseInterfaces(c).Where(i => i.OriginalDefinition.Equals(factoryInterfaceSymbol.OriginalDefinition, SymbolEqualityComparer.Default)))
            .Select(i => i.TypeArguments.FirstOrDefault())
            .Where(t => t is not null && IsAccessibleFromGeneratedCode(t))
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<ITypeSymbol>();

        foreach (var tContext in contextTypes)
        {
            var contextTypeName = tContext.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            factoryMappings.TryAdd(typeof({contextTypeName}), sp => sp.GetService<IRequestContextFactory<{contextTypeName}>>());");
        }

        // Always register the default RequestContextBase factory (provided by CQRSharp.Core).
        sb.AppendLine(
            $"            factoryMappings.TryAdd(typeof({CqrsKnownSymbols.For(compilation).RequestContextBase!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}), sp => sp.GetService<global::CQRSharp.Core.Factories.IRequestContextFactory>());");

        sb.AppendLine("            services.AddSingleton<IContextFactoryRegistry>(new ContextFactoryRegistry(factoryMappings));");
    }

    private static string GenerateDispatcher(Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Markers.Request;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine("using CQRSharp.Core.Requests;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Requests.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class GeneratedRequestDispatcher(IPipelineExecutor pipelineExecutor) : IRequestDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine("        public Task<TResponse> ExecuteAsync<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            return request switch");
        sb.AppendLine("            {");

        var commandSymbol = CqrsKnownSymbols.For(compilation).ICommand;
        var querySymbol = CqrsKnownSymbols.For(compilation).IQuery;
        var typeFormat = SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

        if (commandSymbol is not null && querySymbol is not null)
        {
            var requestSymbols = candidateClasses
                .Where(c => c is { IsAbstract: false, IsGenericType: false } &&
                            IsAccessibleFromGeneratedCode(c) &&
                            c.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, commandSymbol) ||
                                                     (i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, querySymbol))))
                .ToList();

            foreach (var request in requestSymbols)
            {
                var requestName = request.ToDisplayString(typeFormat);
                var queryInterface = request.AllInterfaces.FirstOrDefault(i => i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, querySymbol));

                if (queryInterface is not null) // It's a query
                {
                    var resultName = queryInterface.TypeArguments[0].ToDisplayString(typeFormat);
                    sb.AppendLine(
                        $"                {requestName} q => (Task<TResponse>)(object)pipelineExecutor.ExecuteQueryAsync<{requestName}, {resultName}>(q, cancellationToken),");
                }
                else // It's a command
                {
                    sb.AppendLine($"                {requestName} c => (Task<TResponse>)(object)pipelineExecutor.ExecuteCommandAsync(c, cancellationToken),");
                }
            }
        }

        sb.AppendLine(
            "                _ => throw new System.InvalidOperationException($\"No handler or pipeline found for request type '{request.GetType().FullName}'. Ensure it's public or internal and has a corresponding handler.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public async Task<object?> ExecuteAsync(IRequest request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            return request switch");
        sb.AppendLine("            {");

        if (commandSymbol is not null && querySymbol is not null)
        {
            var requestSymbols = candidateClasses
                .Where(c => c is { IsAbstract: false, IsGenericType: false } &&
                            IsAccessibleFromGeneratedCode(c) &&
                            c.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, commandSymbol) ||
                                                     (i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, querySymbol))))
                .ToList();

            foreach (var request in requestSymbols)
            {
                var requestName = request.ToDisplayString(typeFormat);
                var queryInterface = request.AllInterfaces.FirstOrDefault(i => i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, querySymbol));

                if (queryInterface is not null) // It's a query
                {
                    var resultName = queryInterface.TypeArguments[0].ToDisplayString(typeFormat);
                    sb.AppendLine(
                        $"                {requestName} q => await pipelineExecutor.ExecuteQueryAsync<{requestName}, {resultName}>(q, cancellationToken),");
                }
                else // It's a command
                {
                    sb.AppendLine($"                {requestName} c => await pipelineExecutor.ExecuteCommandAsync(c, cancellationToken),");
                }
            }
        }

        sb.AppendLine(
            "                _ => throw new System.InvalidOperationException($\"No handler or pipeline found for request type '{request.GetType().FullName}'. Ensure it's public or internal and has a corresponding handler.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateStreamDispatcher(Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using CQRSharp.Abstractions.Interfaces.Markers.Stream;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Streams.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class GeneratedStreamRequestDispatcher(IPipelineExecutor pipelineExecutor) : IStreamRequestDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        public IAsyncEnumerable<TItem> ExecuteAsync<TItem>(IStreamRequest<TItem> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine("            return request switch");
        sb.AppendLine("            {");

        var streamRequestSymbol = CqrsKnownSymbols.For(compilation).IStreamRequest;
        var typeFormat = SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

        if (streamRequestSymbol is not null)
        {
            var requestSymbols = candidateClasses
                .Where(c => c is { IsAbstract: false, IsGenericType: false } &&
                            IsAccessibleFromGeneratedCode(c) &&
                            c.AllInterfaces.Any(i => i.IsGenericType &&
                                                     SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, streamRequestSymbol)))
                .ToList();

            foreach (var request in requestSymbols)
            {
                var requestName = request.ToDisplayString(typeFormat);
                var streamInterface = request.AllInterfaces.First(i =>
                    i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, streamRequestSymbol));
                var itemTypeName = streamInterface.TypeArguments[0].ToDisplayString(typeFormat);

                sb.AppendLine(
                    $"                {requestName} r => (global::System.Collections.Generic.IAsyncEnumerable<TItem>)(object)pipelineExecutor.ExecuteStreamAsync<{requestName}, {itemTypeName}>(r, cancellationToken),");
            }
        }

        sb.AppendLine(
            "                _ => throw new InvalidOperationException($\"No stream handler or pipeline found for request type '{request.GetType().FullName}'. Ensure it's public or internal and has a corresponding handler.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public IAsyncEnumerable<object?> ExecuteAsync(IStreamRequest request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine("            return request switch");
        sb.AppendLine("            {");

        if (streamRequestSymbol is not null)
        {
            var requestSymbols = candidateClasses
                .Where(c => c is { IsAbstract: false, IsGenericType: false } &&
                            IsAccessibleFromGeneratedCode(c) &&
                            c.AllInterfaces.Any(i => i.IsGenericType &&
                                                     SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, streamRequestSymbol)))
                .ToList();

            foreach (var request in requestSymbols)
            {
                var requestName = request.ToDisplayString(typeFormat);
                var streamInterface = request.AllInterfaces.First(i =>
                    i.IsGenericType && SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, streamRequestSymbol));
                var itemTypeName = streamInterface.TypeArguments[0].ToDisplayString(typeFormat);

                sb.AppendLine(
                    $"                {requestName} r => Box(pipelineExecutor.ExecuteStreamAsync<{requestName}, {itemTypeName}>(r, cancellationToken), cancellationToken),");
            }
        }

        sb.AppendLine(
            "                _ => throw new InvalidOperationException($\"No stream handler or pipeline found for request type '{request.GetType().FullName}'. Ensure it's public or internal and has a corresponding handler.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine(
            "        private static async IAsyncEnumerable<object?> Box<T>(IAsyncEnumerable<T> source, [EnumeratorCancellation] CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            await foreach (var item in source.WithCancellation(cancellationToken).ConfigureAwait(false))");
        sb.AppendLine("                yield return item;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class HandlerBinding
    {
        public HandlerBinding(
            INamedTypeSymbol handlerImplementation,
            INamedTypeSymbol handlerInterface,
            ITypeSymbol requestType,
            ITypeSymbol? resultType,
            bool isStream)
        {
            HandlerImplementation = handlerImplementation;
            HandlerInterface = handlerInterface;
            RequestType = requestType;
            ResultType = resultType;
            IsStream = isStream;
        }

        public INamedTypeSymbol HandlerImplementation { get; }
        public INamedTypeSymbol HandlerInterface { get; }
        public ITypeSymbol RequestType { get; }
        public ITypeSymbol? ResultType { get; }
        public bool IsStream { get; }
    }

    [Flags]
    private enum ExceptionHookKind
    {
        None = 0,
        Action = 1,
        Handler = 2
    }
}