<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace>CQRSharp.Generators</RootNamespace>

        <IsRoslynComponent>true</IsRoslynComponent>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>CQRSharp.Generators</PackageId>
        <Version>2.2.7</Version>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        
        <PackageOutputPath>$(MSBuildThisFileDirectory)..\.nupkgs</PackageOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
        <None Include="$(MSBuildThisFileDirectory)..\CQRSharp.Abstractions\bin\$(Configuration)\netstandard2.0\CQRSharp.Abstractions.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CQRSharp.Abstractions\CQRSharp.Abstractions.csproj" />
    </ItemGroup>

</Project>