<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <!-- Target and Language Settings -->
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>

        <!-- Roslyn Component Settings -->
        <IsRoslynComponent>true</IsRoslynComponent>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <RootNamespace>CQRSharp.Generators</RootNamespace>
        <PackageId>CQRSharp.Generators</PackageId>
        <EnforceExtendedAnalyzers>true</EnforceExtendedAnalyzers>

        <!-- Packaging Settings -->
        <IsPackable>true</IsPackable>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageOutputPath>..\NuGetPackages</PackageOutputPath>

        <!-- Ensure analyzer dependencies are available -->
        <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
    </PropertyGroup>

    <!-- NuGet Package Metadata -->
    <PropertyGroup>
        <PackageId>CQRSharp.Generators</PackageId>
        <Version>2.2.6</Version>
        <Title>CQRSharp Source Generators</Title>
        <Authors>BisocM</Authors>
        <Description>A set of Roslyn source code generators that allow Native AoT compatibility for the CQRSharp Library.</Description>
        <PackageProjectUrl>cqrsharp.bisocm.org</PackageProjectUrl>
        <RepositoryUrl>https://github.com/BisocM/CQRSharp</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageIcon>CQRSharp_Icon.png</PackageIcon>
        <PackageTags>Roslyn;Source Generator</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReleaseNotes>
            🚀 Release Notes for 2.2.5

            🔧 Changes
            - Added multi-context support per application. Now, you can register multiple IRequestContextFactory that can handle any given context generation, with automatic mapping by the Dispatcher!
            - Additional configurability for the BackgroundTaskQueue. You can now add callback handling if the system is overloaded, configure the system limits, and so on!
            - Additional bottleneck optimizations for BackgroundTaskQueue.

            📂 Breaking Changes?
            - Complete restructure of CQRSharp.Shared - if any types/interfaces/classes were used directly, this will break.
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <!-- Analyzer Package References -->
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0"/>
        <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.13.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <!-- Project Reference to the Shared Library -->
        <ProjectReference Include="..\CQRSharp.Shared\CQRSharp.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\CQRSharp_Icon.png">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
            <Link>CQRSharp_Icon.png</Link>
        </None>
        <None Include="..\LICENSE">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
            <Link>LICENSE</Link>
        </None>
    </ItemGroup>

    <!-- Custom target to supply analyzer dependencies -->
    <Target Name="GetDependencyTargetPaths">
        <ItemGroup>
            <!-- This packs the generator DLL itself in analyzers/dotnet/cs -->
            <None
                    Include="$(OutputPath)\$(AssemblyName).dll"
                    Pack="true"
                    PackagePath="analyzers/dotnet/cs"
                    Visible="false"/>

            <!-- This explicitly packs the Shared DLL -->
            <None
                    Include="..\CQRSharp.Shared\bin\$(Configuration)\$(TargetFramework)\CQRSharp.Shared.dll"
                    Pack="true"
                    PackagePath="analyzers/dotnet/cs"
                    Visible="false"/>
        </ItemGroup>
    </Target>
</Project>