// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;
using CQRSharp.Shared.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CQRSharp.Generators
{
    [Generator]
    public class HandlerRegistrationGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource("HandlerBuilder_Init.g.cs", SourceText.From("//<auto-generated/> //HandlerBuilder initialized", Encoding.UTF8));
            });
            
            // Discover candidate class/record declarations.
            var candidateClasses = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax || node is RecordDeclarationSyntax,
                transform: static (ctx, _) => GetNamedTypeSymbol(ctx))
                .Where(symbol => symbol != null);

            // Combine discovered types with the overall compilation.
            var compilationAndClasses = context.CompilationProvider.Combine(candidateClasses.Collect());
            
            context.RegisterSourceOutput(compilationAndClasses, (spc, source) =>
            {
                try
                {
                    var (compilation, types) = source;
                    
                    // Diagnostic: how many candidate types were discovered?
                    var candidateDiagnostic = new DiagnosticDescriptor(
                        id: "CQRGEN002",
                        title: "Candidate Types Discovered",
                        messageFormat: $"HandlerRegistrationGenerator found {types.Length} candidate types.",
                        category: "SourceGenerator",
                        defaultSeverity: DiagnosticSeverity.Info,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(candidateDiagnostic, Location.None));

                    // Process handler registrations.
                    var registrations = ProcessHandlerRegistrations(compilation, types);
                    // Process request metadata.
                    var metadataEntries = ProcessRequestMetadata(compilation, types);

                    // Filter out duplicates (e.g., same TCommand but both single-param and two-param ICommandHandler).
                    var filteredRegistrations = FilterDuplicateRequestRegistrations(registrations);

                    // Diagnostic: processing results
                    var processDiagnostic = new DiagnosticDescriptor(
                        id: "CQRGEN003",
                        title: "Processing Complete",
                        messageFormat: $"Processed {filteredRegistrations.Length} registrations and {metadataEntries.Length} metadata entries.",
                        category: "SourceGenerator",
                        defaultSeverity: DiagnosticSeverity.Info,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(processDiagnostic, Location.None));

                    // Correlate metadata with registrations so the handler type is populated.
                    var correlatedMetadataEntries = metadataEntries.Select(meta =>
                    {
                        var metaKeyNormalized = NormalizeKey(meta.RequestTypeName);
                        var reg = filteredRegistrations.FirstOrDefault(r => NormalizeKey(r.RequestTypeName) == metaKeyNormalized);
                        var handlerInterface = reg != null ? reg.HandlerInterfaceName : null;
                        return new MetadataEntry(
                            meta.RequestTypeName,
                            handlerInterface,
                            meta.PreHandlerAttributes,
                            meta.PostHandlerAttributes,
                            meta.PipelineExemptions,
                            meta.SensitiveProperties,
                            meta.ResultType);
                    }).ToImmutableArray();

                    // Generate output source.
                    var sourceCode = GenerateSource(filteredRegistrations, correlatedMetadataEntries);
                    spc.AddSource("HandlerRegistration.g.cs", SourceText.From(sourceCode, Encoding.UTF8));

                    // Diagnostic: generation complete
                    var completeDiagnostic = new DiagnosticDescriptor(
                        id: "CQRGEN004",
                        title: "Generation Complete",
                        messageFormat: $"HandlerRegistration.g.cs generated successfully.",
                        category: "SourceGenerator",
                        defaultSeverity: DiagnosticSeverity.Info,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(completeDiagnostic, Location.None));
                }
                catch (Exception ex)
                {
                    // Diagnostic: error if something goes wrong
                    var errorDiagnostic = new DiagnosticDescriptor(
                        id: "CQRGEN999",
                        title: "Generator Exception",
                        messageFormat: $"HandlerRegistrationGenerator encountered an exception: {ex.Message}",
                        category: "SourceGenerator",
                        defaultSeverity: DiagnosticSeverity.Error,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(errorDiagnostic, Location.None));

                    throw;
                }
            });
        }

        #region Processing Handlers

        private static ImmutableArray<Registration> ProcessHandlerRegistrations(Compilation compilation, ImmutableArray<INamedTypeSymbol> types)
        {
            var builder = ImmutableArray.CreateBuilder<Registration>();

            // Because you introduced two-argument versions of ICommandHandler and IQueryHandler,
            // we now look for each arity specifically:
            var iCommandHandler1 = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Handlers.ICommandHandler`1");
            var iCommandHandler2 = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Handlers.ICommandHandler`2");

            var iQueryHandler2 = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Handlers.IQueryHandler`2");
            var iQueryHandler3 = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Handlers.IQueryHandler`3");

            var iNotificationHandler = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Notifications.INotificationHandler`1");
            var iPipelineBehavior = compilation.GetTypeByMetadataName("CQRSharp.Core.Pipelines.IPipelineBehavior`2");

            foreach (var type in types)
            {
                if (type == null)
                    continue;
                // Consider only classes/structs.
                if (type.TypeKind != TypeKind.Class && type.TypeKind != TypeKind.Struct)
                    continue;

                foreach (var iface in type.AllInterfaces)
                {
                    // e.g., ICommandHandler<TCommand, TContext>
                    if (iCommandHandler2 != null &&
                        iface.OriginalDefinition.Equals(iCommandHandler2, SymbolEqualityComparer.Default))
                    {
                        var requestType = iface.TypeArguments[0].ToDisplayString(Format);
                        builder.Add(new Registration(
                            requestType,
                            iface.ToDisplayString(Format),
                            type.ToDisplayString(Format),
                            "CommandHandler"));
                    }
                    // e.g., ICommandHandler<TCommand> (one generic argument)
                    else if (iCommandHandler1 != null &&
                             iface.OriginalDefinition.Equals(iCommandHandler1, SymbolEqualityComparer.Default))
                    {
                        var requestType = iface.TypeArguments[0].ToDisplayString(Format);
                        builder.Add(new Registration(
                            requestType,
                            iface.ToDisplayString(Format),
                            type.ToDisplayString(Format),
                            "CommandHandler"));
                    }
                    // e.g., IQueryHandler<TQuery, TResult, TContext>
                    else if (iQueryHandler3 != null &&
                             iface.OriginalDefinition.Equals(iQueryHandler3, SymbolEqualityComparer.Default))
                    {
                        var requestType = iface.TypeArguments[0].ToDisplayString(Format);
                        builder.Add(new Registration(
                            requestType,
                            iface.ToDisplayString(Format),
                            type.ToDisplayString(Format),
                            "QueryHandler"));
                    }
                    // e.g., IQueryHandler<TQuery, TResult> (two generic arguments)
                    else if (iQueryHandler2 != null &&
                             iface.OriginalDefinition.Equals(iQueryHandler2, SymbolEqualityComparer.Default))
                    {
                        var requestType = iface.TypeArguments[0].ToDisplayString(Format);
                        builder.Add(new Registration(
                            requestType,
                            iface.ToDisplayString(Format),
                            type.ToDisplayString(Format),
                            "QueryHandler"));
                    }
                    // e.g., INotificationHandler<TNotification>
                    else if (iNotificationHandler != null &&
                             iface.OriginalDefinition.Equals(iNotificationHandler, SymbolEqualityComparer.Default))
                    {
                        var requestType = iface.TypeArguments[0].ToDisplayString(Format);
                        builder.Add(new Registration(
                            requestType,
                            iface.ToDisplayString(Format),
                            type.ToDisplayString(Format),
                            "NotificationHandler"));
                    }
                    // e.g., IPipelineBehavior<TRequest, TResponse>
                    else if (iPipelineBehavior != null &&
                             iface.OriginalDefinition.Equals(iPipelineBehavior, SymbolEqualityComparer.Default))
                    {
                        var requestType = iface.TypeArguments[0].ToDisplayString(Format);
                        builder.Add(new Registration(
                            requestType,
                            iface.ToDisplayString(Format),
                            type.ToDisplayString(Format),
                            "PipelineBehavior"));
                    }
                }
            }
            return builder.ToImmutable();
        }

        /// <summary>
        /// If a type implements *both* a single-arity and multi-arity handler interface for the
        /// same TCommand or TQuery, we prefer the more specialized version. This prevents the
        /// dictionary from having duplicates for the same request type.
        /// 
        /// For example, if we see both ICommandHandler&lt;DeleteUserCommand&gt; (1 param) and
        /// ICommandHandler&lt;DeleteUserCommand, RequestContextBase&gt; (2 param), we'll keep the 2-param entry.
        /// </summary>
        private static ImmutableArray<Registration> FilterDuplicateRequestRegistrations(ImmutableArray<Registration> rawRegistrations)
        {
            // Group by (requestTypeName, registrationKind). 
            // We only need one entry per (request, kind). If there's a tie, pick the one with more generic parameters in the handler interface.
            var result = rawRegistrations
                .GroupBy(r => (r.RequestTypeName, r.RegistrationKind))
                .Select(grp =>
                {
                    // If only one item, return it
                    if (grp.Count() == 1) 
                        return grp.First();

                    // If multiple items, pick the one whose HandlerInterfaceName has the greatest arity
                    // e.g., "ICommandHandler`2" beats "ICommandHandler`1".
                    // We'll parse out the backtick in the interface name: e.g. "global::CQRSharp.Interfaces.Handlers.ICommandHandler`2[[..."
                    // or we can do a simpler check with the symbol if we had it, but let's parse the string carefully:
                    var best = grp
                        .OrderByDescending(r => GetGenericArity(r.HandlerInterfaceName))
                        .First();

                    return best;
                })
                .ToImmutableArray();

            return result;
        }

        /// <summary>
        /// Naive string-based parser to check how many generic arguments are in the interface name.
        /// Example: "global::CQRSharp.Interfaces.Handlers.ICommandHandler`2[[..."
        /// We'll just look for a backtick and parse out the digit after it. Fallback to 0 if not found.
        /// </summary>
        private static int GetGenericArity(string handlerInterfaceName)
        {
            // For example, "global::CQRSharp.Interfaces.Handlers.ICommandHandler`2[[global::..."
            // We'll look for '`', then parse the number right after.
            var backtickIndex = handlerInterfaceName.IndexOf('`');
            if (backtickIndex < 0) 
                return 0;

            var next = backtickIndex + 1;
            // gather digits after the backtick
            var digitString = "";
            while (next < handlerInterfaceName.Length && char.IsDigit(handlerInterfaceName[next]))
            {
                digitString += handlerInterfaceName[next];
                next++;
            }
            if (int.TryParse(digitString, out var n))
                return n;
            return 0;
        }

        #endregion

        #region Processing Request Metadata

        private static ImmutableArray<MetadataEntry> ProcessRequestMetadata(Compilation compilation, ImmutableArray<INamedTypeSymbol> types)
        {
            var builder = ImmutableArray.CreateBuilder<MetadataEntry>();

            var iRequestSymbol = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Markers.Request.IRequest");
            var iQuerySymbol   = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Markers.Query.IQuery`1");
            var iCommandSymbol = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Markers.Command.ICommand");

            var preHandlerAttrSymbol      = compilation.GetTypeByMetadataName("CQRSharp.Core.Pipelines.Attributes.IPreHandlerAttribute");
            var postHandlerAttrSymbol     = compilation.GetTypeByMetadataName("CQRSharp.Core.Pipelines.Attributes.IPostHandlerAttribute");
            var pipelineExemptionSymbol   = compilation.GetTypeByMetadataName("CQRSharp.Core.Pipelines.Attributes.Markers.PipelineExemptionAttribute");
            var sensitiveDataSymbol       = compilation.GetTypeByMetadataName("CQRSharp.Core.Pipelines.Attributes.Markers.SensitiveDataAttribute");

            foreach (var type in types)
            {
                if (type == null || iRequestSymbol == null)
                    continue;

                var requestTypeKey = type.ToDisplayString(Format);

                // Only care if this type implements IRequest
                if (!type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iRequestSymbol)))
                    continue;

                // Gather PreHandler attributes.
                string[] preHandlers = type.GetAttributes()
                    .Where(a => preHandlerAttrSymbol != null &&
                                a.AttributeClass.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, preHandlerAttrSymbol)))
                    .Select(GenerateAttributeInstantiationCode)
                    .ToArray();

                // Gather PostHandler attributes.
                string[] postHandlers = type.GetAttributes()
                    .Where(a => postHandlerAttrSymbol != null &&
                                a.AttributeClass.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, postHandlerAttrSymbol)))
                    .Select(GenerateAttributeInstantiationCode)
                    .ToArray();

                // Gather PipelineExemption attributes.
                string[] pipelineExemptions = type.GetAttributes()
                    .Where(a => pipelineExemptionSymbol != null &&
                                SymbolEqualityComparer.Default.Equals(a.AttributeClass.OriginalDefinition, pipelineExemptionSymbol))
                    .Select(GenerateAttributeInstantiationCode)
                    .ToArray();

                // Process sensitive properties.
                var sensitiveProps = type.GetMembers()
                    .OfType<IPropertySymbol>()
                    .Where(p => p.GetAttributes().Any(a => sensitiveDataSymbol != null && SymbolEqualityComparer.Default.Equals(a.AttributeClass, sensitiveDataSymbol)))
                    .Select(p => new Tuple<string, bool>(p.Name, true))
                    .ToArray();

                // Determine the result type from IQuery<T>, or set it to CommandResult if it is ICommand
                string resultType = null;
                var queryInterface = type.AllInterfaces.FirstOrDefault(i =>
                    i.OriginalDefinition.Equals(iQuerySymbol, SymbolEqualityComparer.Default));
                if (queryInterface != null)
                {
                    resultType = queryInterface.TypeArguments[0].ToDisplayString(Format);
                }
                else if (type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iCommandSymbol)))
                {
                    resultType = "CQRSharp.Data.Commands.CommandResult";
                }

                // We'll fill in the final HandlerInterfaceName after correlation
                builder.Add(new MetadataEntry(
                    requestTypeKey,
                    handlerInterfaceName: "",
                    preHandlerAttributes: preHandlers,
                    postHandlerAttributes: postHandlers,
                    pipelineExemptions: pipelineExemptions,
                    sensitiveProperties: sensitiveProps,
                    resultType: resultType
                ));
            }
            return builder.ToImmutable();
        }

        /// <summary>
        /// Generates the instantiation code for an attribute, including constructor arguments.
        /// e.g. "new CQRSharp.Core.Pipelines.Attributes.Markers.PipelineExemptionAttribute(typeof(...))"
        /// </summary>
        private static string GenerateAttributeInstantiationCode(AttributeData attr)
        {
            var attrClass = attr.AttributeClass.ToDisplayString(Format);
            string args = "";
            if (attr.ConstructorArguments.Length > 0)
            {
                var arg = attr.ConstructorArguments[0];
                if (arg.Kind == TypedConstantKind.Type && arg.Value is ITypeSymbol typeSymbol)
                    args = "typeof(" + typeSymbol.ToDisplayString(Format) + ")";
                else if (arg.Kind == TypedConstantKind.Primitive && arg.Value != null)
                    args = arg.Value is string ? $"\"{arg.Value}\"" : arg.Value.ToString();
            }
            return "new " + attrClass + "(" + args + ")";
        }

        #endregion

        #region Generating Source

        private static string GenerateSource(
            ImmutableArray<Registration> registrations,
            ImmutableArray<MetadataEntry> metadataEntries)
        {
            var sb = new StringBuilder();
            sb.AppendLine("//<auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using CQRSharp.Core.Caching.Requests;");
            sb.AppendLine("using CQRSharp.Core.Pipelines.Attributes;");
            sb.AppendLine("using CQRSharp.Core.Pipelines.Attributes.Markers;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();
            sb.AppendLine("namespace " + SourceGeneratorConstants.GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class " + SourceGeneratorConstants.HandlerRegistryClassName);
            sb.AppendLine("    {");
            // Registration method
            sb.AppendLine($"        public static void {SourceGeneratorConstants.HandleRegistrationMethodName}(IServiceCollection services)");
            sb.AppendLine("        {");
            foreach (var reg in registrations)
            {
                sb.AppendLine($"            services.AddTransient(typeof({reg.HandlerInterfaceName}), typeof({reg.HandlerTypeName})); // {reg.RegistrationKind}");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // RegistrationMap dictionary
            sb.AppendLine("        public static IReadOnlyDictionary<Type, (Type HandlerInterface, string RegistrationKind)> RegistrationMap { get; } = new Dictionary<Type, (Type, string)>");
            sb.AppendLine("        {");
            foreach (var reg in registrations)
            {
                sb.AppendLine($"            {{ typeof({reg.RequestTypeName}), (typeof({reg.HandlerInterfaceName}), \"{reg.RegistrationKind}\") }},");
            }
            sb.AppendLine("        };");
            sb.AppendLine();

            // MetadataMap dictionary
            sb.AppendLine("        public static IReadOnlyDictionary<Type, RequestMetadata> MetadataMap { get; } = new Dictionary<Type, RequestMetadata>");
            sb.AppendLine("        {");
            foreach (var meta in metadataEntries)
            {
                sb.AppendLine($"            {{ typeof({meta.RequestTypeName}), new RequestMetadata(");
                sb.AppendLine($"                typeof({meta.RequestTypeName}),");
                if (!string.IsNullOrEmpty(meta.HandlerInterfaceName))
                    sb.AppendLine($"                typeof({meta.HandlerInterfaceName}),");
                else
                    sb.AppendLine("                null,");
                
                // Pre-handler attributes
                if (meta.PreHandlerAttributes.Length > 0)
                {
                    sb.Append("                new IPreHandlerAttribute[] { ");
                    sb.Append(string.Join(", ", meta.PreHandlerAttributes));
                    sb.AppendLine(" },");
                }
                else
                {
                    sb.AppendLine("                Array.Empty<IPreHandlerAttribute>(),");
                }

                // Post-handler attributes
                if (meta.PostHandlerAttributes.Length > 0)
                {
                    sb.Append("                new IPostHandlerAttribute[] { ");
                    sb.Append(string.Join(", ", meta.PostHandlerAttributes));
                    sb.AppendLine(" },");
                }
                else
                {
                    sb.AppendLine("                Array.Empty<IPostHandlerAttribute>(),");
                }

                // Pipeline exemptions
                if (meta.PipelineExemptions.Length > 0)
                {
                    sb.Append("                new PipelineExemptionAttribute[] { ");
                    sb.Append(string.Join(", ", meta.PipelineExemptions));
                    sb.AppendLine(" },");
                }
                else
                {
                    sb.AppendLine("                null,");
                }

                // Sensitive properties
                if (meta.SensitiveProperties.Length > 0)
                {
                    sb.Append("                new PropertySensitivity[] { ");
                    sb.Append(
                        string.Join(", ",
                            meta.SensitiveProperties.Select(
                                p => $"new PropertySensitivity(\"{p.Item1}\", {p.Item2.ToString().ToLower()})")));
                    sb.AppendLine(" },");
                }
                else
                {
                    sb.AppendLine("                Array.Empty<PropertySensitivity>(),");
                }

                if (!string.IsNullOrEmpty(meta.ResultType))
                    sb.AppendLine($"                typeof({meta.ResultType})");
                else
                    sb.AppendLine("                null");

                sb.AppendLine("            ) },");
            }
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        #endregion

        #region Helpers

        // Symbol display format for fully-qualified type names
        private static readonly SymbolDisplayFormat Format = SymbolDisplayFormat.FullyQualifiedFormat;

        private static INamedTypeSymbol GetNamedTypeSymbol(GeneratorSyntaxContext context)
            => context.SemanticModel.GetDeclaredSymbol(context.Node) as INamedTypeSymbol;

        private static string NormalizeKey(string key)
            => key?.Replace("global::", "").Trim();

        #endregion
    }

    // Using classes instead of records for broader compatibility.
    internal class Registration
    {
        public string RequestTypeName { get; }
        public string HandlerInterfaceName { get; }
        public string HandlerTypeName { get; }
        public string RegistrationKind { get; }

        public Registration(string requestTypeName, string handlerInterfaceName, string handlerTypeName, string registrationKind)
        {
            RequestTypeName = requestTypeName;
            HandlerInterfaceName = handlerInterfaceName;
            HandlerTypeName = handlerTypeName;
            RegistrationKind = registrationKind;
        }
    }

    internal class MetadataEntry
    {
        public string RequestTypeName { get; }
        public string HandlerInterfaceName { get; }
        public string[] PreHandlerAttributes { get; }
        public string[] PostHandlerAttributes { get; }
        public string[] PipelineExemptions { get; }
        public Tuple<string, bool>[] SensitiveProperties { get; }
        public string ResultType { get; }

        public MetadataEntry(
            string requestTypeName,
            string handlerInterfaceName,
            string[] preHandlerAttributes,
            string[] postHandlerAttributes,
            string[] pipelineExemptions,
            Tuple<string, bool>[] sensitiveProperties,
            string resultType)
        {
            RequestTypeName = requestTypeName;
            HandlerInterfaceName = handlerInterfaceName;
            PreHandlerAttributes = preHandlerAttributes;
            PostHandlerAttributes = postHandlerAttributes;
            PipelineExemptions = pipelineExemptions;
            SensitiveProperties = sensitiveProperties;
            ResultType = resultType;
        }
    }
}