using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Shared.Attributes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CQRSharp.Generators
{
    [Generator]
    public sealed class PipelineBuilderGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            //Identify candidate classes/records
            var candidateClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                    transform: static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol
                )
                .Where(symbol => symbol is not null);

            // Combine with the compilation
            var compilationAndTypes = context.CompilationProvider.Combine(candidateClasses.Collect());

            //Register source output
            context.RegisterSourceOutput(compilationAndTypes, (spc, source) =>
            {
                var (compilation, types) = source;

                try
                {
                    //Minimizing string-literal usage:
                    var fullyQualifiedMetadataName = typeof(RequestMarkerAttribute).FullName;
                    if (fullyQualifiedMetadataName == null) return;
                    
                    var requestMarkerAttrSymbol = compilation.GetTypeByMetadataName(fullyQualifiedMetadataName);
                    if (requestMarkerAttrSymbol is null)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(
                            Diagnostics.MissingRequestMarkerAttribute,
                            location: null
                        ));
                        return;
                    }

                    var pipelineEntries = ImmutableArray.CreateBuilder<(string RequestType, string ResultType)>();

                    foreach (var typeSymbol in types)
                    {
                        //We want to see if this type implements an interface that is annotated with [RequestMarkerAttribute].
                        bool isRequest = typeSymbol != null && typeSymbol.AllInterfaces.Any(iface =>
                            iface.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, requestMarkerAttrSymbol)));

                        if (!isRequest)
                            continue;

                        //If it's a recognized request, figure out the final TRequest type name and
                        //a suitable result type (based on whether it's a command, query, etc.)
                        if (typeSymbol == null) continue;
                        
                        var requestFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        var resultFullName = InferResultType(typeSymbol);

                        pipelineEntries.Add((requestFullName, resultFullName));
                    }

                    if (pipelineEntries.Count == 0)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(
                            Diagnostics.NoRequestsFound,
                            location: null
                        ));
                    }

                    // Generate the pipeline code
                    var sourceCode = GeneratePipelineSource(pipelineEntries.ToImmutable());
                    spc.AddSource("PipelineBuilders.g.cs", SourceText.From(sourceCode, Encoding.UTF8));

                    spc.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.PipelineBuilderSuccess,
                        location: null,
                        messageArgs: [pipelineEntries.Count]
                    ));
                }
                catch (Exception ex)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.PipelineBuilderException,
                        location: null,
                        messageArgs: [ex.Message]
                    ));
                }
            });
        }

        /// <summary>
        /// Generates a source file containing:
        /// 1) A delegate "PipelineBuilderDelegate" 
        /// 2) A static "PipelineRegistry" class with a "PipelineMap" dictionary
        ///    mapping request Type -> PipelineBuilderDelegate
        /// </summary>
        private static string GeneratePipelineSource(ImmutableArray<(string RequestType, string ResultType)> entries)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();
            sb.AppendLine("namespace CQRSharp.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// A delegate that, given a request object, final handler, etc.,");
            sb.AppendLine("    /// constructs and invokes a pipeline of behaviors returning a Task<object>.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public delegate Task<object> PipelineBuilderDelegate(");
            sb.AppendLine("        IServiceProvider services,");
            sb.AppendLine("        object request,");
            sb.AppendLine("        Func<CancellationToken, Task<object>> finalHandler,");
            sb.AppendLine("        CancellationToken cancellationToken");
            sb.AppendLine("    );");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Automatically generated pipeline registry.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class PipelineRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Maps each request type to a PipelineBuilderDelegate.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static IReadOnlyDictionary<Type, PipelineBuilderDelegate> PipelineMap { get; }");
            sb.AppendLine("            = new Dictionary<Type, PipelineBuilderDelegate>");
            sb.AppendLine("            {");

            foreach (var (requestType, resultType) in entries.Distinct())
            {
                sb.AppendLine("                {");
                sb.AppendLine($"                    typeof({requestType}),");
                sb.AppendLine("                    (services, requestObj, finalHandler, ct) =>");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        //Gather all pipeline behaviors for {requestType} -> {resultType}");
                sb.AppendLine($"                        var behaviors = services.GetServices(typeof(IPipelineBehavior<{requestType}, {resultType}>))");
                sb.AppendLine($"                            .Cast<IPipelineBehavior<{requestType}, {resultType}>>()");
                sb.AppendLine("                            .ToArray();");
                sb.AppendLine();
                sb.AppendLine($"                        //The final delegate calls 'finalHandler', converting the result to '{resultType}'");
                sb.AppendLine($"                        Func<{requestType}, CancellationToken, Task<{resultType}>> pipeline = async (req, token) =>");
                sb.AppendLine("                        {");
                sb.AppendLine("                            var raw = await finalHandler(token);");
                sb.AppendLine($"                            return ({resultType}) raw;");
                sb.AppendLine("                        };");
                sb.AppendLine();
                sb.AppendLine("                        //Compose behaviors in reverse order so that we wrap from last to first");
                sb.AppendLine("                        for (int i = behaviors.Length - 1; i >= 0; i--)");
                sb.AppendLine("                        {");
                sb.AppendLine("                            var next = pipeline;");
                sb.AppendLine("                            var behavior = behaviors[i];");
                sb.AppendLine("                            pipeline = (req, token) => behavior.Handle(req, x => next(req, x), token);");
                sb.AppendLine("                        }");
                sb.AppendLine();
                sb.AppendLine("                        //Return a Task<object>");
                sb.AppendLine($"                        return pipeline(({requestType})requestObj, ct).ContinueWith(t => (object)t.Result, ct);");
                sb.AppendLine("                    }");
                sb.AppendLine("                },");
            }

            sb.AppendLine("            };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>
        /// Examines the type to see if it implements IQuery, ICommand, etc. 
        /// Then returns the result type:
        ///  - If IQuery&lt;T&gt;, returns T
        ///  - If ICommand, returns CommandResult
        ///  - Otherwise System.Object
        /// </summary>
        private static string InferResultType(INamedTypeSymbol requestSymbol)
        {
            //We'll attempt to find any IQuery<T> or check if it implements ICommand
            var iQuery = requestSymbol.AllInterfaces
                .FirstOrDefault(i => i.Name == "IQuery" && i.TypeArguments.Length == 1);
            if (iQuery != null)
            {
                //It's a query, so the result is T
                return iQuery.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }

            //If it implements ICommand => return CommandResult
            var iCommand = requestSymbol.AllInterfaces
                .FirstOrDefault(i => i.Name == "ICommand");
            return iCommand != null ?
                "global::CQRSharp.Data.Commands.CommandResult" :
                "global::System.Object";
        }

        /// <summary>
        /// Diagnostics descriptor container for this generator.
        /// </summary>
        private static class Diagnostics
        {
            internal static readonly DiagnosticDescriptor MissingRequestMarkerAttribute = new DiagnosticDescriptor(
                id: "CQRPIP001",
                title: "Missing RequestMarkerAttribute Symbol",
                messageFormat: "Could not find the RequestMarkerAttribute in the compilation. Make sure CQRSharp.Shared.Attributes is referenced.",
                category: "CQRSharp.Generators",
                defaultSeverity: DiagnosticSeverity.Warning,
                isEnabledByDefault: true
            );

            internal static readonly DiagnosticDescriptor NoRequestsFound = new DiagnosticDescriptor(
                id: "CQRPIP002",
                title: "No Requests Found",
                messageFormat: "No classes/records implementing a [RequestMarker] interface were discovered.",
                category: "CQRSharp.Generators",
                defaultSeverity: DiagnosticSeverity.Info,
                isEnabledByDefault: true
            );

            internal static readonly DiagnosticDescriptor PipelineBuilderSuccess = new DiagnosticDescriptor(
                id: "CQRPIP003",
                title: "Pipeline Builder Generator Succeeded",
                messageFormat: "Successfully generated pipeline builders for {0} discovered request(s).",
                category: "CQRSharp.Generators",
                defaultSeverity: DiagnosticSeverity.Info,
                isEnabledByDefault: true
            );

            internal static readonly DiagnosticDescriptor PipelineBuilderException = new DiagnosticDescriptor(
                id: "CQRPIP999",
                title: "Pipeline Builder Generator Exception",
                messageFormat: "Unhandled exception in PipelineBuilderGenerator: {0}",
                category: "CQRSharp.Generators",
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true
            );
        }
    }
}