<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>CQRSharp.Sample</RootNamespace>
        <LangVersion>default</LangVersion>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <PublishAot>true</PublishAot>
        <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
        <RunAnalyzers>true</RunAnalyzers>
    </PropertyGroup>

    <ItemGroup>
        <!-- <PackageReference Include="CQRSharp.Generators" Version="2.2.3.3"/> -->
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CQRSharp\CQRSharp.csproj"/>
        <ProjectReference Include="..\CQRSharp.Generators\CQRSharp.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all"/>
    </ItemGroup>

</Project>