using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CQRSharp.Generators.Types;

/// <summary>
///     A source generator that discovers all public, non-abstract types implementing
///     <c>IRequestContextFactory&lt;TContext&gt;</c> and generates a registrar that registers a mapping
///     from each <c>TContext</c> to a lambda that resolves the corresponding factory from the DI container.
///     The generated registrar is then bound to <c>Registrar.ContextFactoryRegistryRegistrar</c> via a module initializer.
/// </summary>
[Generator]
public sealed class ContextFactoryRegistryGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        //STEP 1: Create a syntax provider to collect all class declarations.
        var candidateClassesProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                //Predicate: Filter on all class declarations
                static (node, _) => node is ClassDeclarationSyntax,
                //Transformation: Get the declared symbol for the candidate class.
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(symbol => symbol is not null);

        //STEP 2: Combine the candidate class symbols with the current compilation.
        var compilationAndCandidates = context.CompilationProvider.Combine(candidateClassesProvider.Collect());

        //STEP 3: Register a source output that generates the registrar code.
        context.RegisterSourceOutput(compilationAndCandidates, (spc, source) =>
        {
            var (compilation, candidateClasses) = source;

            try
            {
                //Generate the source code for the registrar.
                var generatedSource = GenerateContextFactoryRegistry(spc, compilation, candidateClasses!);
                spc.AddSource("GeneratedContextFactoryRegistryRegistrar.g.cs",
                    SourceText.From(generatedSource, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.UnhandledException,
                    Location.None,
                    ex.ToString()));
            }
        });
    }

    /// <summary>
    ///     Generates the source code for the context factory registrar.
    ///     It creates a mapping between each discovered TContext and a lambda that resolves the appropriate
    ///     IRequestContextFactory&lt;TContext&gt; from the DI container.
    /// </summary>
    /// <param name="spc">The source production context for reporting diagnostics.</param>
    /// <param name="compilation">The current compilation.</param>
    /// <param name="candidateClasses">The collection of candidate class symbols.</param>
    /// <returns>The generated C# source code as a string.</returns>
    private static string GenerateContextFactoryRegistry(
        SourceProductionContext spc,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol?> candidateClasses)
    {
        var sb = new StringBuilder();

        //Write the auto-generated header.
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using CQRSharp.Core.Factories;"); //Contains IRequestContextFactory<TContext>
        sb.AppendLine("using CQRSharp.Core.SourceGeneration;"); //Contains IDataRegistrar and Registrar
        sb.AppendLine(
            "using CQRSharp.Core.Caching.Contexts;"); //Contains the ContextFactoryRegistry and IContextFactoryRegistry
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// A generated registrar that maps context types to their corresponding request context factories.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class GeneratedContextFactoryRegistryRegistrar : IDataRegistrar");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public void RegisterData(IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine(
            "            //Create a mapping of context type to a lambda that resolves the corresponding factory.");
        sb.AppendLine(
            "            var factoryMappings = new Dictionary<Type, Func<IServiceProvider, object>>();");
        sb.AppendLine();

        //Get the generic interface symbol for IRequestContextFactory<TContext>
        var factoryInterfaceSymbol =
            compilation.GetTypeByMetadataName("CQRSharp.Core.Factories.IRequestContextFactory`1");
        if (factoryInterfaceSymbol == null)
        {
            //If the interface is missing, generate an error message in the code.
            sb.AppendLine(
                "            throw new InvalidOperationException(\"IRequestContextFactory<TContext> interface not found.\");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        //Build a set of all discovered TContext types by scanning candidate classes.
        //We only consider candidates that are public and non-abstract.
        var contextTypes = candidateClasses
            .Where(candidate => candidate is { DeclaredAccessibility: Accessibility.Public, IsAbstract: false })
            .SelectMany(candidate =>
                candidate!.AllInterfaces
                    .Where(i => i.OriginalDefinition.Equals(factoryInterfaceSymbol, SymbolEqualityComparer.Default))
                    //The candidate implements IRequestContextFactory<TContext>; extract TContext.
                    .Select(i => i.TypeArguments.FirstOrDefault()))
            .Where(t => t is not null)
            .Distinct(SymbolEqualityComparer.Default)
            .ToList();

        //Sort the discovered context types by their fully qualified name for determinism.
        contextTypes.Sort((x, y) =>
            string.Compare(x!.ToDisplayString(), y!.ToDisplayString(), StringComparison.Ordinal));

        //If no context factories were discovered, generate an empty registration mapping.
        if (contextTypes.Count == 0)
            sb.AppendLine(
                "            //No IRequestContextFactory<TContext> implementations discovered; registering an empty mapping.");
        else
            //For each discovered TContext, emit a mapping entry.
            foreach (var contextType in contextTypes)
            {
                var tContext = contextType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            //Register factory for context type {tContext}");
                sb.AppendLine(
                    $"            factoryMappings[typeof({tContext})] = sp => sp.GetRequiredService<IRequestContextFactory<{tContext}>>());");
                sb.AppendLine();
            }

        //At runtime, the constructed mapping is used to create an instance of IContextFactoryRegistry.
        //You are expected to implement IContextFactoryRegistry and ContextFactoryRegistry similar to RequestRegistry.
        sb.AppendLine("            //Register the factory registry as a singleton with the DI container.");
        sb.AppendLine(
            "            services.AddSingleton<IContextFactoryRegistry>(new ContextFactoryRegistry(factoryMappings));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// A module initializer that assigns the generated context factory registrar to the global Registrar.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class GeneratedContextFactoryRegistryRegistrarInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        public static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                Registrar.ContextFactoryRegistryRegistrar = new GeneratedContextFactoryRegistryRegistrar();");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                throw new InvalidOperationException(\"Failed to initialize GeneratedContextFactoryRegistryRegistrar.\", ex);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    ///     A helper class for reporting unhandled exceptions as diagnostics.
    /// </summary>
    private static class DiagnosticDescriptors
    {
        public static readonly DiagnosticDescriptor UnhandledException = new(
            "CQRCTXF999",
            "Unhandled Exception in ContextFactoryRegistryGenerator",
            "Unhandled exception: {0}",
            "CQRSharp.Generators",
            DiagnosticSeverity.Error,
            true);
    }
}