using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Abstractions.SourceGeneration;

namespace CQRSharp.Generators.Types;

public sealed partial class CqrsSourceGenerator
{
    private static string GenerateDispatcher(Compilation compilation, ImmutableArray<INamedTypeSymbol> candidates)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CQRSharp.Abstractions.Data.Interfaces.Markers.Command;");
        sb.AppendLine("using CQRSharp.Abstractions.Data.Interfaces.Markers.Query;");
        sb.AppendLine("using CQRSharp.Abstractions.Data.Interfaces.Markers.Request;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine("using CQRSharp.Core.Requests;");
        sb.AppendLine();

        var iCommandSymbol = compilation.GetTypeByMetadataName(TypeStrings.ICommand);
        var iQuerySymbol = compilation.GetTypeByMetadataName(TypeStrings.IQuery);

        if (iCommandSymbol is null || iQuerySymbol is null)
        {
            return "// CQRSharp.Abstractions not found, dispatcher not generated.";
        }

        var commandTypes = candidates
            .Where(t => t.TypeKind == TypeKind.Class && !t.IsAbstract && t.AllInterfaces.Contains(iCommandSymbol, SymbolEqualityComparer.Default))
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .ToList();

        var queryTypes = candidates
            .Where(t => t.TypeKind == TypeKind.Class && !t.IsAbstract && t.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, iQuerySymbol)))
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .ToList();

        var caseStatements = (from commandType in commandTypes
            where !commandType.IsUnboundGenericType
            let commandTypeName = commandType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            select $"{commandTypeName} c => await _executor.ExecuteCommandPipelineAsync<{commandTypeName}>(c, cancellationToken)").ToList();

        caseStatements.AddRange(from queryType in queryTypes
            where !queryType.IsUnboundGenericType
            let queryTypeName = queryType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            let queryInterface = queryType.AllInterfaces.First(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, iQuerySymbol))
            let resultTypeName = queryInterface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            select $"{queryTypeName} q => await _executor.ExecuteQueryPipelineAsync<{queryTypeName}, {resultTypeName}>(q, cancellationToken)");

        sb.AppendLine("namespace CQRSharp.Core.Requests.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class GeneratedRequestDispatcher : IRequestDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly PipelineExecutor _executor;");
        sb.AppendLine();
        sb.AppendLine("        public GeneratedRequestDispatcher(PipelineExecutor executor)");
        sb.AppendLine("        {");
        sb.AppendLine("            _executor = executor;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public async Task<object?> ExecuteAsync(IRequest request, CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            return request switch");
        sb.AppendLine("            {");

        if (caseStatements.Any())
        {
            sb.AppendLine("                " + string.Join(",\n                ", caseStatements) + ",");
        }

        sb.AppendLine("                _ => throw new InvalidOperationException($\"No handler found for request type {request.GetType().FullName}.\")");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}