using CQRSharp.Abstractions.SourceGeneration;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace CQRSharp.Generators.Types;

/// <summary>
/// A source generator that creates hints for the Native AOT compiler.
/// It scans the compilation for all request and open generic behavior/handler types
/// and generates explicit `typeof()` references for every possible generic instantiation.
/// This prevents the AOT compiler from trimming code that is only referenced dynamically
/// via dependency injection, which would otherwise cause runtime errors.
/// </summary>
[Generator]
public sealed class CqrsAotHintGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Discover all class symbols in the compilation.
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(symbol => symbol is not null);

        // Combine the compilation with the collected symbols.
        var compilationAndTypes = context.CompilationProvider.Combine(provider.Collect());

        // Register the source output step.
        context.RegisterSourceOutput(compilationAndTypes, (spc, source) =>
        {
            var (compilation, types) = source;
            var sourceCode = GenerateAotHints(compilation, types!);
            spc.AddSource("CqrsAotHints.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        });
    }

    /// <summary>
    /// Generates the source code containing the AOT hints.
    /// </summary>
    /// <param name="compilation">The current Roslyn compilation.</param>
    /// <param name="types">All class symbols discovered in the compilation.</param>
    /// <returns>A string containing the generated C# code.</returns>
    private string GenerateAotHints(Compilation compilation, ImmutableArray<INamedTypeSymbol> types)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This file is generated to provide hints to the AOT compiler. Do not edit manually.");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.AotHints");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class AotHintProvider");
        sb.AppendLine("    {");
        sb.AppendLine("        // This method is never called. Its purpose is to create static references");
        sb.AppendLine("        // to all possible generic instantiations of pipeline behaviors and handlers,");
        sb.AppendLine("        // preventing the AOT compiler from trimming them.");
        sb.AppendLine("        private static void PreserveGenericTypes()");
        sb.AppendLine("        {");

        // --- Get all necessary CQRS type symbols from the compilation ---
        var iCommandSymbol = compilation.GetTypeByMetadataName(TypeStrings.ICommand);
        var iQuerySymbol = compilation.GetTypeByMetadataName(TypeStrings.IQuery);
        var pipelineBehaviorSymbol = compilation.GetTypeByMetadataName(TypeStrings.IPipelineBehavior);
        var commandResultSymbol = compilation.GetTypeByMetadataName(TypeStrings.CommandResult);

        // If core types aren't available, we can't generate hints.
        if (iCommandSymbol is null || iQuerySymbol is null || pipelineBehaviorSymbol is null || commandResultSymbol is null)
        {
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // --- Find all concrete ICommand and IQuery implementations ---
        var requestSymbols = types
            .Where(c => c is { IsAbstract: false, IsGenericType: false } &&
                        (c.AllInterfaces.Contains(iCommandSymbol, SymbolEqualityComparer.Default) ||
                         c.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, iQuerySymbol))))
            .ToList();

        // --- Find all open generic pipeline behaviors ---
        var openGenericBehaviors = types
            .Where(c => c is { IsAbstract: false, IsGenericType: true } &&
                        c.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, pipelineBehaviorSymbol)))
            .ToList();

        // --- Generate typeof() for each Request <> Behavior combination ---
        sb.AppendLine("            // Preserving Pipeline Behavior instantiations:");
        foreach (var request in requestSymbols)
        {
            var requestName = request.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var queryInterface = request.AllInterfaces.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, iQuerySymbol));
            var resultName = (queryInterface?.TypeArguments[0] ?? commandResultSymbol).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            foreach (var behaviorName in openGenericBehaviors.Select(behavior => behavior.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Split('<')[0]))
                sb.AppendLine($"            _ = typeof({behaviorName}<{requestName}, {resultName}>);");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}