using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Shared.Data.Attributes.Pipelines;
using CQRSharp.Shared.Data.Models.Commands;
using CQRSharp.Shared.Data.Models.Requests;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CQRSharp.Generators.Types;

/// <summary>
///     An incremental source generator that scans the compilation for CQRSharp-related types
///     (like commands, queries, and handlers) and generates the necessary dependency injection
///     and registry registrations.
/// </summary>
[Generator]
public sealed class CqrsSourceGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     The entry point for the source generator. This method sets up the generation pipeline.
    /// </summary>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all class and record declarations that could potentially be part of the CQRS system.
        var candidateClassesProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(symbol => symbol is not null);

        // Combine the compilation with the collected candidate classes.
        var compilationAndCandidates = context.CompilationProvider.Combine(candidateClassesProvider.Collect());

        // Register the primary source output action.
        context.RegisterSourceOutput(compilationAndCandidates, (spc, source) =>
        {
            var (compilation, candidateClasses) = source;

            try
            {
                var sourceCode = GenerateRegistrations(compilation, candidateClasses!);
                spc.AddSource("CqrsGeneratedRegistrar.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                // Report any unhandled exceptions during generation as a diagnostic error.
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("CQRGEN999", "Unhandled Exception in CqrsSourceGenerator",
                        "Unhandled exception: {0}", "CQRSharp.Generators", DiagnosticSeverity.Error, true),
                    Location.None, ex.ToString()));
            }
        });
    }

    /// <summary>
    ///     Orchestrates the generation of the entire CqrsGeneratedRegistrar.g.cs file.
    /// </summary>
    /// <param name="compilation">The compilation object representing the user's project.</param>
    /// <param name="candidateClasses">A collection of all type symbols to be analyzed.</param>
    /// <returns>A string containing the complete generated source code.</returns>
    private static string GenerateRegistrations(Compilation compilation,
        ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using CQRSharp.Core.Caching.Contexts;");
        sb.AppendLine("using CQRSharp.Core.Caching.Handlers;");
        sb.AppendLine("using CQRSharp.Core.Caching.Pipelines;");
        sb.AppendLine("using CQRSharp.Core.Caching.Requests;");
        sb.AppendLine("using CQRSharp.Core.Factories;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");
        sb.AppendLine("using CQRSharp.Shared.Data.Attributes.Pipelines;");
        sb.AppendLine("using CQRSharp.Shared.Data.Models.Commands;");
        sb.AppendLine("using CQRSharp.Shared.Data.Models.Requests;");
        sb.AppendLine();

        sb.AppendLine("namespace CQRSharp.Core.Extensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static class CqrsGeneratedRegistrations");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddGenerated(this IServiceCollection services)");
        sb.AppendLine("        {");

        GenerateHandlerServices(sb, compilation, candidateClasses);
        GenerateRequestRegistry(sb, compilation, candidateClasses);
        GenerateHandlerRegistry(sb, compilation, candidateClasses);
        GenerateContextFactoryRegistry(sb, compilation, candidateClasses);
        GeneratePipelineRegistry(sb, compilation, candidateClasses);

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    ///     Generates DI registrations for all concrete command and query handlers.
    ///     It finds classes that implement an interface marked with [HandlerType]
    ///     and registers them as transient services.
    /// </summary>
    private static void GenerateHandlerServices(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Handler Services");

        var handlerTypeAttributeSymbol = compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Attributes.Requests.HandlerTypeAttribute");
        if (handlerTypeAttributeSymbol is null) return;

        var registrations = new List<(string InterfaceType, string ImplementationType)>();
        foreach (var classSymbol in candidateClasses.Where(c => c is { IsAbstract: false, IsGenericType: false }))
        foreach (var iface in classSymbol.AllInterfaces)
            if (iface.GetAttributes().Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, handlerTypeAttributeSymbol)))
            {
                var interfaceType = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var implementationType = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                registrations.Add((interfaceType, implementationType));
                break;
            }

        foreach (var reg in registrations.Distinct()) sb.AppendLine($"            services.AddTransient(typeof({reg.InterfaceType}), typeof({reg.ImplementationType}));");
    }

    /// <summary>
    ///     Generates the registration for the <see cref="IRequestRegistry" />.
    ///     This registry holds metadata for each request type, including associated handlers, attributes,
    ///     result types, and context types.
    /// </summary>
    private static void GenerateRequestRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Request Registry");
        sb.AppendLine("            var requestMetadataMappings = new ConcurrentDictionary<Type, RequestMetadata>();");

        var handlerTypeAttributeSymbol = compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Attributes.Requests.HandlerTypeAttribute");
        var preHandlerInterfaceSymbol = compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Attributes.Pipelines.IPreHandlerAttribute");
        var postHandlerInterfaceSymbol = compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Attributes.Pipelines.IPostHandlerAttribute");
        var pipelineExemptionAttributeSymbol = compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Attributes.Pipelines.PipelineExemptionAttribute");
        if (handlerTypeAttributeSymbol is null || preHandlerInterfaceSymbol is null || postHandlerInterfaceSymbol is null || pipelineExemptionAttributeSymbol is null) return;

        foreach (var candidate in candidateClasses.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
        {
            if (candidate.IsAbstract) continue;
            foreach (var iface in candidate.AllInterfaces.Where(i =>
                         i.GetAttributes().Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, handlerTypeAttributeSymbol))))
            {
                if (iface.TypeArguments.Length == 0) continue;

                var requestTypeSymbol = iface.TypeArguments[0];
                var requestTypeName = requestTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var handlerInterfaceName = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                var preHandlersCode = GenerateAttributeArrayCode(requestTypeSymbol, preHandlerInterfaceSymbol,
                    "global::CQRSharp.Shared.Data.Attributes.Pipelines.IPreHandlerAttribute");
                var postHandlersCode = GenerateAttributeArrayCode(requestTypeSymbol, postHandlerInterfaceSymbol,
                    "global::CQRSharp.Shared.Data.Attributes.Pipelines.IPostHandlerAttribute");
                var pipelineExemptionsCode = GenerateAttributeArrayCode(requestTypeSymbol, pipelineExemptionAttributeSymbol,
                    "global::CQRSharp.Shared.Data.Attributes.Pipelines.PipelineExemptionAttribute");
                var sensitivePropertiesCode = GenerateSensitivePropertiesCode(requestTypeSymbol);

                var isQuery = iface.Name.StartsWith("IQueryHandler", StringComparison.Ordinal);
                var resultTypeCode = isQuery && iface.TypeArguments.Length > 1
                    ? $"typeof({iface.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})"
                    : "null";

                var contextTypeSymbol = GetRequestContextType(requestTypeSymbol) ?? compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Interfaces.Context.RequestContextBase");
                var contextTypeName = contextTypeSymbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "object";

                sb.AppendLine($"            requestMetadataMappings.TryAdd(typeof({requestTypeName}),");
                sb.AppendLine("                new RequestMetadata(");
                sb.AppendLine($"                    RequestType: typeof({requestTypeName}),");
                sb.AppendLine($"                    HandlerType: typeof({handlerInterfaceName}),");
                sb.AppendLine($"                    PreHandlers: {preHandlersCode},");
                sb.AppendLine($"                    PostHandlers: {postHandlersCode},");
                sb.AppendLine($"                    PipelineExemptions: {pipelineExemptionsCode},");
                sb.AppendLine($"                    SensitiveProperties: {sensitivePropertiesCode},");
                sb.AppendLine($"                    ResultType: {resultTypeCode},");
                sb.AppendLine($"                    ContextType: typeof({contextTypeName})");
                sb.AppendLine("                ));");
            }
        }

        sb.AppendLine("            services.AddSingleton<IRequestRegistry>(new RequestRegistry(requestMetadataMappings));");
    }

    /// <summary>
    ///     Generates the registration for the <see cref="IHandlerRegistry" />.
    ///     This registry maps each request type to a compiled delegate that can invoke the
    ///     corresponding handler's 'Handle' method, avoiding runtime reflection.
    /// </summary>
    private static void GenerateHandlerRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Handler Registry");
        sb.AppendLine("            var handlerInvokerMappings = new ConcurrentDictionary<Type, HandlerInvokerDelegate>();");

        var handlerTypeAttributeSymbol = compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Attributes.Requests.HandlerTypeAttribute");
        if (handlerTypeAttributeSymbol is null) return;

        foreach (var iface in candidateClasses.SelectMany(c => c.AllInterfaces)
                     .Where(i => i.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, handlerTypeAttributeSymbol)))
                     .Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
        {
            var genericArgs = iface.TypeArguments.Select(ta => ta.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).ToArray();
            if (iface.TypeArguments.Length == 0) continue;

            string requestType;
            string handlerInterface;

            if (iface.Name.StartsWith("ICommandHandler", StringComparison.Ordinal))
            {
                requestType = genericArgs[0];
                handlerInterface = $"global::CQRSharp.Shared.Data.Interfaces.Handlers.ICommandHandler<{string.Join(", ", genericArgs)}>";
                sb.AppendLine(
                    $"            handlerInvokerMappings.TryAdd(typeof({requestType}), (handler, request, ct) => (({handlerInterface})handler).Handle(({requestType})request, ct).ContinueWith(t => (object)t.Result, TaskContinuationOptions.ExecuteSynchronously));");
            }
            else if (iface.Name.StartsWith("IQueryHandler", StringComparison.Ordinal) && genericArgs.Length >= 2)
            {
                requestType = genericArgs[0];
                handlerInterface = $"global::CQRSharp.Shared.Data.Interfaces.Handlers.IQueryHandler<{string.Join(", ", genericArgs)}>";
                sb.AppendLine(
                    $"            handlerInvokerMappings.TryAdd(typeof({requestType}), (handler, request, ct) => (({handlerInterface})handler).Handle(({requestType})request, ct).ContinueWith(t => (object)t.Result, TaskContinuationOptions.ExecuteSynchronously));");
            }
        }

        sb.AppendLine("            services.AddSingleton<IHandlerRegistry>(new HandlerRegistry(handlerInvokerMappings));");
    }

    /// <summary>
    ///     Generates the registration for the <see cref="IContextFactoryRegistry" />.
    ///     This registry maps a context type to its corresponding factory, allowing the system
    ///     to create specialized request contexts.
    /// </summary>
    private static void GenerateContextFactoryRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Context Factory Registry");
        sb.AppendLine("            var factoryMappings = new ConcurrentDictionary<Type, Func<IServiceProvider, object>>();");

        var factoryInterfaceSymbol = compilation.GetTypeByMetadataName("CQRSharp.Core.Factories.IRequestContextFactory`1");
        if (factoryInterfaceSymbol is null) return;

        var contextTypes = candidateClasses
            .Where(candidate => candidate is { DeclaredAccessibility: Accessibility.Public, IsAbstract: false })
            .SelectMany(candidate => candidate.AllInterfaces
                .Where(i => i.OriginalDefinition.Equals(factoryInterfaceSymbol, SymbolEqualityComparer.Default))
                .Select(i => i.TypeArguments.FirstOrDefault()))
            .Where(t => t is not null)
            .Distinct(SymbolEqualityComparer.Default)
            .ToList();

        contextTypes.Sort((x, y) => string.Compare(x!.ToDisplayString(), y!.ToDisplayString(), StringComparison.Ordinal));

        foreach (var contextType in contextTypes)
        {
            var tContext = contextType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            factoryMappings.TryAdd(typeof({tContext}), sp => sp.GetRequiredService<IRequestContextFactory<{tContext}>>());");
        }

        sb.AppendLine("            services.AddSingleton<IContextFactoryRegistry>(new ContextFactoryRegistry(factoryMappings));");
    }

    /// <summary>
    ///     Generates the registration for the <see cref="IPipelineRegistry" />.
    ///     This registry maps each request type to a compiled delegate that constructs and executes
    ///     its pipeline of behaviors, sorted by priority.
    /// </summary>
    private static void GeneratePipelineRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Pipeline Registry");
        sb.AppendLine("            var pipelineMap = new ConcurrentDictionary<Type, PipelineBuilderDelegate>();");

        var iCommandSymbol = compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Interfaces.Markers.Command.ICommand");
        var iQuerySymbol = compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Interfaces.Markers.Query.IQuery`1");
        var pipelineBehaviorSymbol = compilation.GetTypeByMetadataName("CQRSharp.Core.Pipelines.IPipelineBehavior`2");
        var priorityAttrSymbol = compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Attributes.Pipelines.PipelinePriorityAttribute");

        if (iCommandSymbol is null || iQuerySymbol is null || pipelineBehaviorSymbol is null || priorityAttrSymbol is null) return;

        var defaultPriority = PipelinePriorityAttribute.DefaultPriority;

        var requests = candidateClasses
            .Where(rs => !rs.IsAbstract && (InheritsOrImplements(rs, iCommandSymbol) || InheritsOrImplements(rs, iQuerySymbol)))
            .ToList();

        foreach (var requestSymbol in requests)
        {
            var resultTypeSymbol = InferResultTypeSymbol(compilation, requestSymbol);
            var requestFullName = requestSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var resultFullName = resultTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var matchedBehaviors = new List<(INamedTypeSymbol Symbol, int Priority)>();
            foreach (var behaviorSymbol in candidateClasses.Where(c => !c.IsAbstract))
                if (behaviorSymbol.AllInterfaces.Any(i =>
                        SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, pipelineBehaviorSymbol) &&
                        i.TypeArguments.Length == 2 &&
                        SymbolEqualityComparer.Default.Equals(i.TypeArguments[0], requestSymbol) &&
                        SymbolEqualityComparer.Default.Equals(i.TypeArguments[1], resultTypeSymbol)))
                {
                    var priority = defaultPriority;
                    var attrData = behaviorSymbol.GetAttributes().FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, priorityAttrSymbol));
                    if (attrData?.ConstructorArguments.Length == 1 && attrData.ConstructorArguments[0].Value is int p) priority = p;

                    matchedBehaviors.Add((behaviorSymbol, priority));
                }

            var sortedBehaviorFullNames = matchedBehaviors
                .OrderBy(x => x.Priority)
                .Select(x => x.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .ToImmutableArray();

            sb.AppendLine($"            pipelineMap.TryAdd(typeof({requestFullName}), (services, requestObj, finalHandler, ct) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var behaviors = new IPipelineBehavior<{requestFullName}, {resultFullName}>[]");
            sb.AppendLine("                {");
            foreach (var behavior in sortedBehaviorFullNames) sb.AppendLine($"                    services.GetRequiredService<{behavior}>(),");

            sb.AppendLine("                };");
            sb.AppendLine($"                Func<{requestFullName}, CancellationToken, Task<{resultFullName}>> pipeline = async (req, token) =>");
            sb.AppendLine("                {");
            sb.AppendLine("                    var rawResult = await finalHandler(token).ConfigureAwait(false);");
            sb.AppendLine($"                    return ({resultFullName})rawResult;");
            sb.AppendLine("                };");
            sb.AppendLine("                for (int i = behaviors.Length - 1; i >= 0; i--)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var next = pipeline;");
            sb.AppendLine("                    var behavior = behaviors[i];");
            sb.AppendLine("                    pipeline = (req, token) => behavior.Handle(req, x => next(req, x), token);");
            sb.AppendLine("                }");
            sb.AppendLine(
                $"                return pipeline((requestObj as {requestFullName})!, ct).ContinueWith(t => (object)t.Result!, TaskContinuationOptions.ExecuteSynchronously);");
            sb.AppendLine("            });");
        }

        sb.AppendLine("            services.AddSingleton<IPipelineRegistry>(new PipelineRegistry(pipelineMap));");
    }

    /// <summary>
    ///     Infers the result type for a given request. Returns <see cref="CommandResult" /> for commands,
    ///     and TResult for queries implementing <see cref="Core.Shared.Data.Interfaces.Markers.Query.IQuery{TResult}" />.
    /// </summary>
    private static ITypeSymbol InferResultTypeSymbol(Compilation compilation, INamedTypeSymbol requestSymbol)
    {
        var iQuerySymbol = compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Interfaces.Markers.Query.IQuery`1");
        var iQuery = requestSymbol.AllInterfaces.FirstOrDefault(i => i.OriginalDefinition.Equals(iQuerySymbol, SymbolEqualityComparer.Default));
        if (iQuery != null) return iQuery.TypeArguments[0];

        return compilation.GetTypeByMetadataName("CQRSharp.Shared.Data.Models.Commands.CommandResult")!;
    }

    /// <summary>
    ///     Traverses the inheritance hierarchy of a request type to find the TContext
    ///     generic argument from <see cref="Core.Shared.Data.Interfaces.Markers.Request.RequestBase{TContext}" />.
    /// </summary>
    private static ITypeSymbol? GetRequestContextType(ITypeSymbol requestTypeSymbol)
    {
        var current = requestTypeSymbol.BaseType;
        while (current != null)
        {
            if (current.IsGenericType && current.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                "global::CQRSharp.Shared.Data.Interfaces.Markers.Request.RequestBase<TContext>")
                return current.TypeArguments[0];

            current = current.BaseType;
        }

        return null;
    }

    /// <summary>
    ///     Generates a C# code string representing an array literal of attributes
    ///     that are found on a given type symbol.
    /// </summary>
    private static string GenerateAttributeArrayCode(ITypeSymbol requestTypeSymbol, INamedTypeSymbol attributeInterfaceSymbol, string fullyQualifiedInterfaceName)
    {
        var attributeInstances = requestTypeSymbol.GetAttributes()
            .Where(attr => attr.AttributeClass != null && InheritsOrImplements(attr.AttributeClass, attributeInterfaceSymbol))
            .ToList();

        if (!attributeInstances.Any()) return $"Array.Empty<{fullyQualifiedInterfaceName}>()";

        var instancesCode = attributeInstances.Select(attr =>
        {
            var attrClassName = attr.AttributeClass!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var args = string.Join(", ", attr.ConstructorArguments.Select(GenerateTypedConstant));
            return $"new {attrClassName}({args})";
        });

        return $"new {fullyQualifiedInterfaceName}[] {{ {string.Join(", ", instancesCode)} }}";
    }

    /// <summary>
    ///     Scans a request type for properties marked with the [SensitiveData] attribute and
    ///     generates a C# code string for an array of <see cref="PropertySensitivity" /> records.
    /// </summary>
    private static string GenerateSensitivePropertiesCode(ITypeSymbol requestTypeSymbol)
    {
        var propertySensitivityFullyQualifiedName = "global::CQRSharp.Shared.Data.Models.Requests.PropertySensitivity";
        var sensitiveProps = requestTypeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(prop => prop.GetAttributes().Any(attr => attr.AttributeClass?.Name == nameof(SensitiveDataAttribute)))
            .Select(prop => $"new {propertySensitivityFullyQualifiedName}(\"{prop.Name}\", true)")
            .ToList();

        return !sensitiveProps.Any()
            ? $"Array.Empty<{propertySensitivityFullyQualifiedName}>()"
            : $"new {propertySensitivityFullyQualifiedName}[] {{ {string.Join(", ", sensitiveProps)} }}";
    }

    /// <summary>
    ///     Converts a <see cref="TypedConstant" /> from the Roslyn semantic model into a C# source code literal.
    ///     Handles primitives, enums, and types.
    /// </summary>
    private static string GenerateTypedConstant(TypedConstant constant)
    {
        if (constant.IsNull) return "null";

        var value = constant.Value;
        switch (constant.Kind)
        {
            case TypedConstantKind.Primitive:
                return value is string s ? $"\"{s.Replace("\"", "\\\"")}\""
                    : value is bool b ? b.ToString().ToLowerInvariant()
                    : value?.ToString() ?? "null";

            case TypedConstantKind.Enum:
                if (constant.Type is not INamedTypeSymbol enumType) return $"({constant.Type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}){value}";

                var member = enumType.GetMembers()
                    .OfType<IFieldSymbol>()
                    .FirstOrDefault(f => f.ConstantValue is not null && f.ConstantValue.Equals(value));
                return member is not null
                    ? $"{enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.{member.Name}"
                    : $"({enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}){value}";

            case TypedConstantKind.Type:
                return $"typeof({((ITypeSymbol)value!).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})";

            default:
                return "null";
        }
    }

    /// <summary>
    ///     A utility method to check if a type symbol inherits from a base type or implements an interface,
    ///     correctly handling original definitions for generic types.
    /// </summary>
    private static bool InheritsOrImplements(ITypeSymbol type, ITypeSymbol baseType)
    {
        if (SymbolEqualityComparer.Default.Equals(type, baseType)) return true;

        if (baseType.TypeKind == TypeKind.Interface)
            if (type.AllInterfaces.Any(iface => SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, baseType.OriginalDefinition)))
                return true;

        var current = type.BaseType;
        while (current != null)
        {
            if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, baseType.OriginalDefinition)) return true;
            current = current.BaseType;
        }

        return false;
    }
}