using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Abstractions.Data.Attributes.Pipelines;
using CQRSharp.Abstractions.SourceGeneration;

namespace CQRSharp.Generators.Types;

public sealed partial class CqrsSourceGenerator
{
    private static string GenerateRegistrations(Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using CQRSharp.Abstractions.Data.Interfaces.Notifications;");
        sb.AppendLine("using CQRSharp.Abstractions.Data.Models.Requests;");
        sb.AppendLine("using CQRSharp.Core.Caching.Requests;");
        sb.AppendLine("using CQRSharp.Core.Caching.Handlers;");
        sb.AppendLine("using CQRSharp.Core.Caching.Pipelines;");
        sb.AppendLine("using CQRSharp.Core.Caching.Contexts;");
        sb.AppendLine("using CQRSharp.Core.Factories;");
        sb.AppendLine("using CQRSharp.Core.Pipelines;");

        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Extensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static class CqrsGeneratedRegistrations");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddGenerated(this IServiceCollection services)");
        sb.AppendLine("        {");

        GenerateHandlerServices(sb, compilation, candidateClasses);
        GenerateRequestRegistry(sb, compilation, candidateClasses);
        GenerateHandlerRegistry(sb, compilation, candidateClasses);
        GenerateContextFactoryRegistry(sb, compilation, candidateClasses);
        GeneratePipelineRegistry(sb, compilation, candidateClasses);
        GenerateNotificationServices(sb, compilation, candidateClasses);

        sb.AppendLine();
        sb.AppendLine("            // Registering the core executor and the generated dispatcher.");
        sb.AppendLine("            services.AddSingleton<PipelineExecutor>();");
        sb.AppendLine(
            "            services.AddSingleton<global::CQRSharp.Core.Requests.IRequestDispatcher, global::CQRSharp.Core.Requests.Generated.GeneratedRequestDispatcher>();");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateHandlerServices(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Handler Services by Interface Implementation");

        var commandHandlerSymbols = new[]
        {
            compilation.GetTypeByMetadataName(TypeStrings.ICommandHandler1),
            compilation.GetTypeByMetadataName(TypeStrings.ICommandHandler2)
        }.Where(s => s is not null);

        var queryHandlerSymbols = new[]
        {
            compilation.GetTypeByMetadataName(TypeStrings.IQueryHandler2),
            compilation.GetTypeByMetadataName(TypeStrings.IQueryHandler3)
        }.Where(s => s is not null);

        var notificationHandlerSymbol = compilation.GetTypeByMetadataName(TypeStrings.INotificationHandler);
        var pipelineBehaviorSymbol = compilation.GetTypeByMetadataName(TypeStrings.IPipelineBehavior);

        var allKnownHandlers = commandHandlerSymbols
            .Concat(queryHandlerSymbols)
            .Concat([notificationHandlerSymbol, pipelineBehaviorSymbol])
            .Where(s => s is not null)
            .Select(s => s.OriginalDefinition)
            .ToArray();

        if (!allKnownHandlers.Any())
            return;

        var registrations = candidateClasses
            .Where(c => c is { IsAbstract: false, IsGenericType: false })
            .SelectMany(classSymbol => classSymbol.AllInterfaces
                .Where(iface => iface.IsGenericType && allKnownHandlers.Contains(iface.OriginalDefinition, SymbolEqualityComparer.Default))
                .Select(iface => (
                    InterfaceType: iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    ImplementationType: classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                ))
            )
            .Distinct();

        foreach (var reg in registrations)
        {
            sb.AppendLine($"            services.AddTransient(typeof({reg.InterfaceType}), typeof({reg.ImplementationType}));");
        }
    }

    private static void GenerateRequestRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Request Registry");
        sb.AppendLine("            var requestMetadataMappings = new ConcurrentDictionary<Type, RequestMetadata>();");

        var commandHandlerDef = compilation.GetTypeByMetadataName(TypeStrings.ICommandHandler2)?.OriginalDefinition;
        var queryHandlerDef = compilation.GetTypeByMetadataName(TypeStrings.IQueryHandler3)?.OriginalDefinition;
        var preHandlerInterfaceSymbol = compilation.GetTypeByMetadataName(TypeStrings.IPreHandlerAttribute);
        var postHandlerInterfaceSymbol = compilation.GetTypeByMetadataName(TypeStrings.IPostHandlerAttribute);
        var pipelineExemptionAttributeSymbol = compilation.GetTypeByMetadataName(TypeStrings.PipelineExemptionAttribute);

        if (commandHandlerDef is null || queryHandlerDef is null || preHandlerInterfaceSymbol is null || postHandlerInterfaceSymbol is null ||
            pipelineExemptionAttributeSymbol is null) return;

        var handlerInterfaces = candidateClasses
            .Where(c => c is { IsAbstract: false, IsGenericType: false })
            .SelectMany(c => c.AllInterfaces)
            .Where(i => i.IsGenericType && (SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, commandHandlerDef) ||
                                            SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, queryHandlerDef)))
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .ToList();

        foreach (var handlerInterface in handlerInterfaces)
        {
            var requestTypeSymbol = handlerInterface.TypeArguments[0];
            var handlerInterfaceName = handlerInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var requestTypeName = requestTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var preHandlersCode = GenerateAttributeArrayCode(requestTypeSymbol, preHandlerInterfaceSymbol, $"global::{TypeStrings.IPreHandlerAttribute}");
            var postHandlersCode = GenerateAttributeArrayCode(requestTypeSymbol, postHandlerInterfaceSymbol, $"global::{TypeStrings.IPostHandlerAttribute}");
            var pipelineExemptionsCode = GenerateAttributeArrayCode(requestTypeSymbol, pipelineExemptionAttributeSymbol, $"global::{TypeStrings.PipelineExemptionAttribute}");
            var sensitivePropertiesCode = GenerateSensitivePropertiesCode(requestTypeSymbol);

            var isQuery = SymbolEqualityComparer.Default.Equals(handlerInterface.OriginalDefinition, queryHandlerDef);
            var resultTypeCode = isQuery ? $"typeof({handlerInterface.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})" : "null";

            var contextTypeSymbol = GetRequestContextType(requestTypeSymbol, compilation) ?? compilation.GetTypeByMetadataName(TypeStrings.RequestContextBase);
            var contextTypeName = contextTypeSymbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "object";

            sb.AppendLine(
                $"            requestMetadataMappings.TryAdd(typeof({requestTypeName}), new RequestMetadata(typeof({requestTypeName}), typeof({handlerInterfaceName}), {preHandlersCode}, {postHandlersCode}, {pipelineExemptionsCode}, {sensitivePropertiesCode}, {resultTypeCode}, typeof({contextTypeName})));");
        }

        sb.AppendLine("            services.AddSingleton<IRequestRegistry>(new RequestRegistry(requestMetadataMappings));");
    }

    private static void GenerateHandlerRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Handler Registry");
        sb.AppendLine("            var handlerInvokerMappings = new ConcurrentDictionary<Type, HandlerInvokerDelegate>();");

        var commandHandlerDef = compilation.GetTypeByMetadataName(TypeStrings.ICommandHandler2)?.OriginalDefinition;
        var queryHandlerDef = compilation.GetTypeByMetadataName(TypeStrings.IQueryHandler3)?.OriginalDefinition;

        if (commandHandlerDef is null || queryHandlerDef is null) return;

        var handlerInterfaces = candidateClasses
            .Where(c => c is { IsAbstract: false, IsGenericType: false })
            .SelectMany(c => c.AllInterfaces)
            .Where(i => i.IsGenericType && (SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, commandHandlerDef) ||
                                            SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, queryHandlerDef)))
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .ToList();

        foreach (var iface in handlerInterfaces)
        {
            var requestType = iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var handlerInterface = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var invokerLambda = $"async (handler, request, ct) => (object)await (({handlerInterface})handler).Handle(({requestType})request, ct).ConfigureAwait(false)";

            sb.AppendLine($"            handlerInvokerMappings.TryAdd(typeof({requestType}), {invokerLambda});");
        }

        sb.AppendLine("            services.AddSingleton<IHandlerRegistry>(new HandlerRegistry(handlerInvokerMappings));");
    }

    private static void GenerateContextFactoryRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Context Factory Registry");
        sb.AppendLine("            var factoryMappings = new ConcurrentDictionary<Type, Func<System.IServiceProvider, object>>();");

        var factoryInterfaceSymbol = compilation.GetTypeByMetadataName(TypeStrings.IRequestContextFactory);
        if (factoryInterfaceSymbol is null) return;

        var contextTypes = candidateClasses
            .Where(c => c is { DeclaredAccessibility: Accessibility.Public, IsAbstract: false })
            .SelectMany(c => c.AllInterfaces.Where(i => i.OriginalDefinition.Equals(factoryInterfaceSymbol.OriginalDefinition, SymbolEqualityComparer.Default)))
            .Select(i => i.TypeArguments.FirstOrDefault())
            .Where(t => t is not null)
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<ITypeSymbol>()
            .Select(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .OrderBy(s => s, System.StringComparer.Ordinal);

        foreach (var tContext in contextTypes)
        {
            sb.AppendLine($"            factoryMappings.TryAdd(typeof({tContext}), sp => sp.GetRequiredService<IRequestContextFactory<{tContext}>>());");
        }

        sb.AppendLine("            services.AddSingleton<IContextFactoryRegistry>(new ContextFactoryRegistry(factoryMappings));");
    }

    private static void GeneratePipelineRegistry(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("            // Registering Pipeline Registry");
        sb.AppendLine("            var pipelineMap = new ConcurrentDictionary<Type, PipelineBuilderDelegate>();");

        var iCommandSymbol = compilation.GetTypeByMetadataName(TypeStrings.ICommand);
        var iQuerySymbol = compilation.GetTypeByMetadataName(TypeStrings.IQuery);
        var pipelineBehaviorSymbol = compilation.GetTypeByMetadataName(TypeStrings.IPipelineBehavior);
        var priorityAttrSymbol = compilation.GetTypeByMetadataName(TypeStrings.PipelinePriorityAttribute);
        if (iCommandSymbol is null || iQuerySymbol is null || pipelineBehaviorSymbol is null || priorityAttrSymbol is null) return;

        var requests = candidateClasses.Where(rs => !rs.IsAbstract && (InheritsOrImplements(rs, iCommandSymbol) || InheritsOrImplements(rs, iQuerySymbol)));

        foreach (var requestSymbol in requests)
        {
            var resultTypeSymbol = InferResultTypeSymbol(compilation, requestSymbol);
            var requestFullName = requestSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var resultFullName = resultTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var matchedBehaviors = candidateClasses
                .Where(c => !c.IsAbstract && c.AllInterfaces.Any(i =>
                    SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, pipelineBehaviorSymbol.OriginalDefinition) &&
                    i.TypeArguments.Length == 2 &&
                    SymbolEqualityComparer.Default.Equals(i.TypeArguments[0], requestSymbol) &&
                    SymbolEqualityComparer.Default.Equals(i.TypeArguments[1], resultTypeSymbol)))
                .Select(behaviorSymbol =>
                {
                    var attrData = behaviorSymbol.GetAttributes().FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, priorityAttrSymbol));
                    var priority = (attrData?.ConstructorArguments.Length == 1 && attrData.ConstructorArguments[0].Value is int p) ? p : PipelinePriorityAttribute.DefaultPriority;
                    return (Symbol: behaviorSymbol, Priority: priority);
                })
                .OrderBy(x => x.Priority)
                .Select(x => x.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .ToImmutableArray();

            sb.AppendLine($"            pipelineMap.TryAdd(typeof({requestFullName}), (services, requestObj, finalHandler, ct) =>");
            sb.AppendLine("            {");

            sb.AppendLine(
                $"                Func<System.Threading.CancellationToken, System.Threading.Tasks.Task<{resultFullName}>> nextDelegate = async (token) => ({resultFullName})await finalHandler(token).ConfigureAwait(false);");

            sb.Append($"                var behaviors = new IPipelineBehavior<{requestFullName}, {resultFullName}>[] {{ ");
            sb.Append(string.Join(", ", matchedBehaviors.Select(b => $"services.GetRequiredService<{b}>()")));
            sb.AppendLine(" };");

            sb.AppendLine("                for (int i = behaviors.Length - 1; i >= 0; i--)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var currentNext = nextDelegate;");
            sb.AppendLine("                    var behavior = behaviors[i];");
            sb.AppendLine($"                    nextDelegate = (token) => behavior.Handle(({requestFullName})requestObj, currentNext, token);");
            sb.AppendLine("                }");

            sb.AppendLine($"                var resultTask = nextDelegate(ct);");
            sb.AppendLine(
                $"                return resultTask.ContinueWith(t => (object)t.Result!, System.Threading.Tasks.TaskContinuationOptions.ExecuteSynchronously);");

            sb.AppendLine("            });");
        }

        sb.AppendLine("            services.AddSingleton<IPipelineRegistry>(new PipelineRegistry(pipelineMap));");
    }

    private static void GenerateNotificationServices(StringBuilder sb, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidateClasses)
    {
        sb.AppendLine();
        sb.AppendLine("           // Registering Notification Serialization Services");

        var notificationInterfaceSymbol = compilation.GetTypeByMetadataName(TypeStrings.INotification);
        var notificationNameAttributeSymbol = compilation.GetTypeByMetadataName(TypeStrings.NotificationNameAttribute);

        if (notificationInterfaceSymbol is null || notificationNameAttributeSymbol is null) return;

        var notificationTypes = candidateClasses
            .Where(c => !c.IsAbstract && c.AllInterfaces.Contains(notificationInterfaceSymbol, SymbolEqualityComparer.Default))
            .Select(c => new { Type = c, Attr = c.GetAttributes().FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, notificationNameAttributeSymbol)) })
            .Where(x => x.Attr is not null && x.Attr.ConstructorArguments.Any())
            .ToList();

        sb.AppendLine("           var nameToTypeMap = new System.Collections.Generic.Dictionary<string, Type>();");
        sb.AppendLine("           var typeToNameMap = new System.Collections.Generic.Dictionary<Type, string>();");

        foreach (var n in notificationTypes)
        {
            var typeName = n.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var attrName = n.Attr!.ConstructorArguments[0].Value as string;
            if (string.IsNullOrEmpty(attrName)) continue;
            sb.AppendLine($"           nameToTypeMap[\"{attrName}\"] = typeof({typeName});");
            sb.AppendLine($"           typeToNameMap[typeof({typeName})] = \"{attrName}\";");
        }

        sb.AppendLine("           services.AddSingleton<IReadOnlyDictionary<string, Type>>(nameToTypeMap);");
        sb.AppendLine("           services.AddSingleton<IReadOnlyDictionary<Type, string>>(typeToNameMap);");
    }
}