using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Shared.Data.Attributes.Requests;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CQRSharp.Generators.Types;

/// <summary>
///     A source generator that discovers classes implementing interfaces decorated
///     with the <c>[HandlerType]</c> attribute and generates a registrar to register
///     them with the DI container.
/// </summary>
[Generator]
public class HandlerRegistrationGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        //Process every class declaration in the compilation.
        IncrementalValuesProvider<ClassDeclarationSyntax> candidateClasses =
            context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => (ClassDeclarationSyntax)ctx.Node
            );

        //Combine all candidate classes with the current compilation.
        IncrementalValueProvider<(ImmutableArray<ClassDeclarationSyntax> Classes, Compilation Compilation)>
            compilationAndClasses =
                candidateClasses.Collect().Combine(context.CompilationProvider);

        //Register the output generation.
        context.RegisterSourceOutput(compilationAndClasses, (spc, source) =>
        {
            spc.ReportDiagnostic(Diagnostic.Create(SDebugStartDescriptor, Location.None));

            try
            {
                var (classes, compilation) = source;
                spc.ReportDiagnostic(Diagnostic.Create(SDebugCandidateCountDescriptor, Location.None, classes.Length));

                //Look up the HandlerType attribute by its fully qualified metadata name.
                var handlerTypeAttributeSymbol =
                    compilation.GetTypeByMetadataName(typeof(HandlerTypeAttribute).FullName!);
                if (handlerTypeAttributeSymbol == null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(SMissingAttributeDescriptor, Location.None));
                    return;
                }

                //Create a list to collect registrations:
                //Each registration is a tuple (InterfaceFullName, ImplementationFullName).
                var registrations = new List<(string InterfaceType, string ImplementationType)>();

                //Loop over every class declaration in the compilation.
                foreach (var classDecl in classes)
                {
                    //Get the semantic model for this syntax tree.
                    var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
                    if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol) continue;

                    spc.ReportDiagnostic(Diagnostic.Create(SDebugProcessingClassDescriptor, Location.None,
                        classSymbol.ToDisplayString()));

                    //Check every interface that this class implements.
                    foreach (var iface in classSymbol.AllInterfaces)
                        //If the interface is decorated with [HandlerType], then register this class.
                        if (iface.GetAttributes().Any(attr =>
                                SymbolEqualityComparer.Default.Equals(attr.AttributeClass, handlerTypeAttributeSymbol)))
                        {
                            //Use fully qualified type names for safety with AOT and trimming.
                            var interfaceType = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            var implementationType =
                                classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            registrations.Add((interfaceType, implementationType));
                            spc.ReportDiagnostic(Diagnostic.Create(SDebugRegistrationAddedDescriptor, Location.None,
                                interfaceType, implementationType));
                            //Only register once per class.
                            break;
                        }
                }

                if (registrations.Count == 0)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(SNoRegistrationFoundDescriptor, Location.None));
                    return;
                }

                //Build the source code to be generated.
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("using System;");
                sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
                sb.AppendLine("using CQRSharp.Core.SourceGeneration;");
                sb.AppendLine("using System.Runtime.CompilerServices;");
                sb.AppendLine();
                sb.AppendLine("namespace CQRSharp.Generated");
                sb.AppendLine("{");
                sb.AppendLine("    /// <summary>");
                sb.AppendLine(
                    "    /// A generated data registrar that registers discovered handler types with the DI container.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public class GeneratedHandlerRegistrar : IDataRegistrar");
                sb.AppendLine("    {");
                sb.AppendLine("        /// <inheritdoc />");
                sb.AppendLine("        public void RegisterData(IServiceCollection services)");
                sb.AppendLine("        {");

                //Emit one registration per discovered handler.
                foreach (var reg in registrations.Distinct())
                    sb.AppendLine(
                        $"            services.AddTransient(typeof({reg.InterfaceType}), typeof({reg.ImplementationType}));");

                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>");
                sb.AppendLine(
                    "    /// A module initializer that wires up the generated handler registrar with the global registrar.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static class GeneratedHandlerRegistrarInitializer");
                sb.AppendLine("    {");
                sb.AppendLine("        [ModuleInitializer]");
                sb.AppendLine("        public static void Initialize()");
                sb.AppendLine("        {");
                sb.AppendLine("            try");
                sb.AppendLine("            {");
                sb.AppendLine("                //Wire the generated registrar into the global Registrar.");
                sb.AppendLine("                Registrar.HandlerRegistrar = new GeneratedHandlerRegistrar();");
                sb.AppendLine("            }");
                sb.AppendLine("            catch(Exception ex)");
                sb.AppendLine("            {");
                sb.AppendLine("                //Fail fast if the initialization does not succeed.");
                sb.AppendLine(
                    "                throw new InvalidOperationException(\"Failed to initialize GeneratedHandlerRegistrar.\", ex);");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");

                //Add the generated source to the compilation.
                spc.AddSource("GeneratedHandlerRegistrar.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
                spc.ReportDiagnostic(Diagnostic.Create(SSuccessDescriptor, Location.None, registrations.Count));
            }
            catch (Exception ex)
            {
                spc.ReportDiagnostic(Diagnostic.Create(SErrorDescriptor, Location.None, ex.ToString()));
            }
        });
    }

    #region Diagnostic Descriptors

    //When the HandlerType attribute cannot be found.
    private static readonly DiagnosticDescriptor SMissingAttributeDescriptor = new(
        "CQRHND002",
        "Missing HandlerType Attribute",
        $"The attribute {typeof(HandlerTypeAttribute).FullName} was not found. Ensure that it is defined and referenced.",
        "CQRSharp.Generators",
        DiagnosticSeverity.Error,
        true);

    //When no handler registrations are discovered.
    private static readonly DiagnosticDescriptor SNoRegistrationFoundDescriptor = new(
        "CQRHND003",
        "No Handler Registrations Found",
        "No handler registrations were discovered. Ensure that you have classes implementing interfaces decorated with [HandlerType].",
        "CQRSharp.Generators",
        DiagnosticSeverity.Error,
        true);

    //For unexpected exceptions during generation.
    private static readonly DiagnosticDescriptor SErrorDescriptor = new(
        "CQRHND001",
        "Handler Registration Generator Exception",
        "An exception occurred in the HandlerRegistrationGenerator: {0}",
        "CQRSharp.Generators",
        DiagnosticSeverity.Error,
        true);

    //On successful generation.
    private static readonly DiagnosticDescriptor SSuccessDescriptor = new(
        "CQRHND004",
        "Handler Registration Generation Successful",
        "Handler registration generation completed successfully. {0} registration(s) were generated.",
        "CQRSharp.Generators",
        DiagnosticSeverity.Info,
        true);

    //Debug diagnostics (set to Info during development; can be lowered later).
    private static readonly DiagnosticDescriptor SDebugStartDescriptor = new(
        "CQRDBG001",
        "Debug: Generation Started",
        "Starting handler registration generation",
        "CQRSharp.Generators.Debug",
        DiagnosticSeverity.Info,
        true);

    private static readonly DiagnosticDescriptor SDebugCandidateCountDescriptor = new(
        "CQRDBG002",
        "Debug: Candidate Count",
        "Found {0} candidate class declarations",
        "CQRSharp.Generators.Debug",
        DiagnosticSeverity.Info,
        true);

    private static readonly DiagnosticDescriptor SDebugProcessingClassDescriptor = new(
        "CQRDBG003",
        "Debug: Processing Class",
        "Processing class: {0}",
        "CQRSharp.Generators.Debug",
        DiagnosticSeverity.Info,
        true);

    private static readonly DiagnosticDescriptor SDebugRegistrationAddedDescriptor = new(
        "CQRDBG004",
        "Debug: Registration Added",
        "Added registration: Interface = {0}, Implementation = {1}",
        "CQRSharp.Generators.Debug",
        DiagnosticSeverity.Info,
        true);

    #endregion
}