using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Shared.Data.Attributes.Pipelines;
using CQRSharp.Shared.Data.Attributes.Requests;
using CQRSharp.Shared.Data.Models.Requests;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CQRSharp.Generators.Types;

/// <summary>
///     A source generator that builds a request registry by discovering classes implementing interfaces
///     marked with [HandlerType]. It collects additional metadata (pre/post handlers, pipeline exemptions,
///     sensitive properties, and now also the request context type) and generates a registrar that registers
///     the metadata with the DI container.
/// </summary>
[Generator]
public sealed class RequestRegistryGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        //STEP 1: Register a syntax provider that finds all class declarations.
        var candidateClassesProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol
            )
            .Where(symbol => symbol is not null);

        //STEP 2: Combine the compilation with the collected candidate classes.
        var combinedProvider = context.CompilationProvider.Combine(candidateClassesProvider.Collect());

        //STEP 3: Generate the source code.
        context.RegisterSourceOutput(combinedProvider, (spc, source) =>
        {
            var (compilation, candidateClasses) = source;

            try
            {
                var generatedSource = GenerateRequestRegistry(spc, compilation, candidateClasses);
                spc.AddSource("GeneratedRequestRegistryRegistrar.g.cs",
                    SourceText.From(generatedSource, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    RequestRegistryDiagnostics.UnhandledException,
                    Location.None,
                    ex.ToString()
                ));
            }
        });
    }

    /// <summary>
    ///     Generates the entire request registry source code after analyzing candidate classes.
    /// </summary>
    private static string GenerateRequestRegistry(
        SourceProductionContext spc,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol?> candidateClasses)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using CQRSharp.Shared.Data.Attributes.Pipelines;");
        sb.AppendLine("using CQRSharp.Shared.Data.Models.Requests;");
        sb.AppendLine("using CQRSharp.Core.SourceGeneration;  //For IDataRegistrar and Registrar.");
        sb.AppendLine("using CQRSharp.Core.Caching.Requests;  //For IDataRegistrar and Registrar.");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace CQRSharp.Core.Extensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// A generated registrar that collects request metadata and populates a shared IRequestRegistry implementation.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class GeneratedRequestRegistryRegistrar : IDataRegistrar");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        public void RegisterData(IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine("            var handlerMappings = new Dictionary<Type, RequestMetadata>();");
        sb.AppendLine();

        var handlerTypeAttributeFullName = typeof(HandlerTypeAttribute).FullName!;
        var handlerTypeAttributeSymbol = compilation.GetTypeByMetadataName(handlerTypeAttributeFullName);

        //Additional attribute types (pre/post/pipeline exemption).
        var preHandlerInterfaceSymbol =
            compilation.GetTypeByMetadataName(typeof(IPreHandlerAttribute).FullName!);
        var postHandlerInterfaceSymbol =
            compilation.GetTypeByMetadataName(typeof(IPostHandlerAttribute).FullName!);
        var pipelineExemptionAttributeSymbol =
            compilation.GetTypeByMetadataName(typeof(PipelineExemptionAttribute).FullName!);

        var anyRegistrationFound = false;

        //STEP 4: Iterate over candidate classes and process each implemented interface with [HandlerType].
        foreach (var candidate in candidateClasses.Distinct())
        {
            if (candidate == null)
                continue;

            foreach (var iface in candidate.AllInterfaces.Where(iface =>
                         IsHandlerInterfaceMarked(iface, handlerTypeAttributeSymbol)))
            {
                if (iface.TypeArguments.Length == 0)
                {
                    //Emit a diagnostic if the interface is missing type arguments.
                    spc.ReportDiagnostic(Diagnostic.Create(
                        RequestRegistryDiagnostics.MissingGenericArgument,
                        Location.None,
                        iface.ToDisplayString()
                    ));
                    continue;
                }

                //The request type is assumed to be the first generic argument.
                var requestTypeSymbol = iface.TypeArguments[0];
                var requestTypeName = requestTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var handlerInterfaceName = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                //Determine the registration kind from the attribute's constructor argument (if any).
                var registrationKind = ExtractRegistrationKind(iface, handlerTypeAttributeSymbol);

                //Gather pre-handlers, post-handlers, pipeline exemptions from attributes on the request type.
                var preHandlersCode = GenerateAttributeArrayCode(
                    requestTypeSymbol, preHandlerInterfaceSymbol,
                    typeof(IPreHandlerAttribute).FullName ??
                    throw new InvalidOperationException("Could not resolve IPreHandlerAttribute type name."));
                var postHandlersCode = GenerateAttributeArrayCode(
                    requestTypeSymbol, postHandlerInterfaceSymbol,
                    typeof(IPostHandlerAttribute).FullName ??
                    throw new InvalidOperationException("Could not resolve IPostHandlerAttribute type name."));
                var pipelineExemptionsCode = GenerateAttributeArrayCode(
                    requestTypeSymbol, pipelineExemptionAttributeSymbol,
                    typeof(PipelineExemptionAttribute).FullName ??
                    throw new InvalidOperationException("Could not resolve PipelineExemptionAttribute type name."));

                //Identify any sensitive properties on the request type.
                var sensitivePropertiesCode = GenerateSensitivePropertiesCode(requestTypeSymbol);

                //For demonstration, we treat "Command" kind as returning null, otherwise we default to typeof(object).
                var resultTypeCode = registrationKind == "Command" ? "null" : "typeof(object)";

                //Determine the Request Context Type
                //Attempt to extract the context type by inspecting the base classes.
                var contextTypeSymbol = GetRequestContextType(requestTypeSymbol)
                                        ?? compilation.GetTypeByMetadataName(
                                            "CQRSharp.Shared.Data.Interfaces.Context.RequestContextBase");
                var contextTypeName = contextTypeSymbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ??
                                      "object";

                //Append the registration to the mapping, including the new ContextType value.
                sb.AppendLine($"            handlerMappings[typeof({requestTypeName})] =");
                sb.AppendLine("                new RequestMetadata(");
                sb.AppendLine($"                    RequestType: typeof({requestTypeName}),");
                sb.AppendLine($"                    HandlerType: typeof({handlerInterfaceName}),");
                sb.AppendLine($"                    PreHandlers: {preHandlersCode},");
                sb.AppendLine($"                    PostHandlers: {postHandlersCode},");
                sb.AppendLine($"                    PipelineExemptions: {pipelineExemptionsCode},");
                sb.AppendLine($"                    SensitiveProperties: {sensitivePropertiesCode},");
                sb.AppendLine($"                    ResultType: {resultTypeCode},");
                sb.AppendLine($"                    ContextType: typeof({contextTypeName})");
                sb.AppendLine("                ));");
                sb.AppendLine();

                anyRegistrationFound = true;
            }
        }

        sb.AppendLine("            services.AddSingleton<IRequestRegistry>(new RequestRegistry(handlerMappings));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// A module initializer that assigns the generated request registry registrar to the global Registrar.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class GeneratedRequestRegistryRegistrarInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        public static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                Registrar.RequestRegistryRegistrar = new GeneratedRequestRegistryRegistrar();");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                throw new InvalidOperationException(\"Failed to initialize GeneratedRequestRegistryRegistrar.\", ex);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        if (!anyRegistrationFound)
            spc.ReportDiagnostic(Diagnostic.Create(
                RequestRegistryDiagnostics.NoRequestMetadataDiscovered,
                Location.None
            ));

        return sb.ToString();
    }

    /// <summary>
    ///     Attempts to extract the request context type by inspecting the base types of the given request type.
    ///     It looks for the first generic base matching RequestBase&lt;TContext&gt; and returns the TContext.
    /// </summary>
    /// <param name="requestTypeSymbol">The request type symbol to examine.</param>
    /// <returns>The extracted context type symbol if found; otherwise, null.</returns>
    private static ITypeSymbol? GetRequestContextType(ITypeSymbol requestTypeSymbol)
    {
        //Traverse the base types.
        var current = requestTypeSymbol.BaseType;
        while (current != null)
        {
            //Compare the fully qualified name of the generic definition to our known RequestBase.
            if (current.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                == "global::CQRSharp.Shared.Data.Interfaces.Markers.Request.RequestBase<TContext>")
                if (current is INamedTypeSymbol named && named.TypeArguments.Length == 1)
                    return named.TypeArguments[0];

            current = current.BaseType;
        }

        return null;
    }

    /// <summary>
    ///     Checks whether the given interface is marked with the [HandlerType] attribute.
    /// </summary>
    private static bool IsHandlerInterfaceMarked(INamedTypeSymbol iface, INamedTypeSymbol? handlerTypeAttributeSymbol)
    {
        if (handlerTypeAttributeSymbol == null)
            return false;

        return iface.GetAttributes()
            .Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, handlerTypeAttributeSymbol));
    }

    /// <summary>
    ///     Extracts the "registration kind" from the HandlerType attribute constructor argument, if present.
    /// </summary>
    private static string ExtractRegistrationKind(INamedTypeSymbol iface, INamedTypeSymbol? handlerTypeAttributeSymbol)
    {
        if (handlerTypeAttributeSymbol == null)
            return "Unknown";

        var attrData = iface.GetAttributes()
            .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, handlerTypeAttributeSymbol));

        if (attrData?.ConstructorArguments.Length > 0)
        {
            var argValue = attrData.ConstructorArguments[0].Value?.ToString();
            return argValue ?? "Unknown";
        }

        return "Unknown";
    }

    /// <summary>
    ///     Generates code to instantiate an array of attribute instances from the given request type,
    ///     considering only attributes whose classes implement the specified interface.
    /// </summary>
    private static string GenerateAttributeArrayCode(
        ITypeSymbol requestTypeSymbol,
        INamedTypeSymbol? attributeInterfaceSymbol,
        string fullyQualifiedInterfaceName)
    {
        if (attributeInterfaceSymbol is null) return $"Array.Empty<{fullyQualifiedInterfaceName}>()";

        var attributeInstances = requestTypeSymbol.GetAttributes()
            .Where(attr => attr.AttributeClass != null &&
                           InheritsOrImplements(attr.AttributeClass, attributeInterfaceSymbol))
            .ToList();

        if (!attributeInstances.Any()) return $"Array.Empty<{fullyQualifiedInterfaceName}>()";

        //Each attribute is constructed via known compile-time constants or default constructors.
        var instancesCode = attributeInstances.Select(attr =>
        {
            var attrClassName = attr.AttributeClass!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var args = string.Join(", ", attr.ConstructorArguments.Select(GenerateTypedConstant));
            return $"new {attrClassName}({args})";
        });

        return $"new {fullyQualifiedInterfaceName}[] {{ {string.Join(", ", instancesCode)} }}";
    }

    /// <summary>
    ///     Scans the request type for properties marked with [SensitiveAttribute] and generates code
    ///     to create a PropertySensitivity array describing them.
    /// </summary>
    private static string GenerateSensitivePropertiesCode(ITypeSymbol requestTypeSymbol)
    {
        var propertySensitivityFullyQualifiedName = typeof(PropertySensitivity).FullName ??
                                                    throw new InvalidOperationException(
                                                        "Could not resolve PropertySensitivity type name.");
        var sensitiveProps = requestTypeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(prop => prop.GetAttributes()
                .Any(attr => attr.AttributeClass?.Name == nameof(SensitiveDataAttribute)))
            .Select(prop => $"new {propertySensitivityFullyQualifiedName}(\"{prop.Name}\", true)")
            .ToList();

        return !sensitiveProps.Any()
            ? $"Array.Empty<{propertySensitivityFullyQualifiedName}>()"
            : $"new {propertySensitivityFullyQualifiedName}[] {{ {string.Join(", ", sensitiveProps)} }}";
    }

    /// <summary>
    ///     Converts a Roslyn TypedConstant into a string representation suitable for source generation.
    /// </summary>
    private static string GenerateTypedConstant(TypedConstant constant)
    {
        if (constant.IsNull)
            return "null";

        return constant.Kind switch
        {
            TypedConstantKind.Primitive => constant.Value is string
                ? $"\"{constant.Value}\""
                : constant.Value?.ToString() ?? "null",

            TypedConstantKind.Enum =>
                $"{constant.Type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.{constant.Value}",
            _ => "null"
        };
    }

    /// <summary>
    ///     Determines whether a type inherits from or implements the specified base type/interface.
    /// </summary>
    private static bool InheritsOrImplements(ITypeSymbol type, INamedTypeSymbol baseType)
    {
        //Check for direct interface implementation or equality.
        if (SymbolEqualityComparer.Default.Equals(type, baseType))
            return true;

        //Check all interfaces.
        if (type.AllInterfaces.Any(iface => SymbolEqualityComparer.Default.Equals(iface, baseType)))
            return true;

        //Traverse base types.
        var current = type.BaseType;
        while (current != null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
                return true;
            current = current.BaseType;
        }

        return false;
    }

    /// <summary>
    ///     Contains diagnostic descriptors used by the <see cref="RequestRegistryGenerator" />.
    /// </summary>
    private static class RequestRegistryDiagnostics
    {
        /// <summary>
        ///     Emitted when the interface is marked with [HandlerType] but has no generic arguments.
        /// </summary>
        public static readonly DiagnosticDescriptor MissingGenericArgument = new(
            "CQRMD001",
            "Handler Interface Missing Generic Argument",
            "Interface '{0}' is marked with [HandlerType] but has no generic arguments",
            "CQRSharp.Generators",
            DiagnosticSeverity.Warning,
            true
        );

        /// <summary>
        ///     Emitted when no request metadata was discovered in the process.
        /// </summary>
        public static readonly DiagnosticDescriptor NoRequestMetadataDiscovered = new(
            "CQRMD002",
            "No Request Metadata Discovered",
            "No request metadata was discovered. Ensure that your handlers implement interfaces marked with [HandlerType].",
            "CQRSharp.Generators",
            DiagnosticSeverity.Info,
            true
        );

        /// <summary>
        ///     Emitted for any unhandled exception in <see cref="RequestRegistryGenerator" />.
        /// </summary>
        public static readonly DiagnosticDescriptor UnhandledException = new(
            "CQRMD999",
            "Unhandled Exception in RequestRegistryGenerator",
            "Unhandled exception: {0}",
            "CQRSharp.Generators",
            DiagnosticSeverity.Error,
            true
        );
    }
}