<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <OutputType>Exe</OutputType>
        <PublishAot>true</PublishAot>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>CQRSharp.Generators.Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CQRSharp.Generator\CQRSharp.Generator.csproj" OutputItemType="Analyzer" />
        <ProjectReference Include="..\CQRSharp\CQRSharp.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="DDD.UbiquitousLanguageRegistry.txt"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="linker.xml" />
    </ItemGroup>
    
    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>
</Project>