<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>

        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <PackageId>CQRSharp.Generator</PackageId>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>CQRSharp Source Generators</Title>
        <Authors>BisocM</Authors>
        <Description>A set of Roslyn source code generators that allow Native AoT compatibility for the CQRSharp Library.</Description>
        <PackageIcon>CQRSharp_Icon.png</PackageIcon>
        <RepositoryUrl>https://github.com/BisocM/CQRSharp</RepositoryUrl>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CQRSharp\CQRSharp.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\CQRSharp_Icon.png">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>
    
</Project>
