// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CQRSharp.Core.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CQRSharp.Generator
{
    [Generator]
    public class HandlerRegistrationGenerator : IIncrementalGenerator
    {
        //Use a consistent display format so keys match between processing passes.
        private static readonly SymbolDisplayFormat Format = SymbolDisplayFormat.FullyQualifiedFormat;

        //Helper to normalize type keys (e.g. remove "global::" and trim whitespace).
        private static string NormalizeKey(string key) => key?.Replace("global::", "").Trim();

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            //Discover candidate class or record declarations.
            var candidateClasses = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax || node is RecordDeclarationSyntax,
                transform: static (ctx, _) => GetNamedTypeSymbol(ctx))
                .Where(symbol => symbol != null);

            //Combine discovered types with the overall compilation.
            var compilationAndClasses = context.CompilationProvider.Combine(candidateClasses.Collect());
            
            context.RegisterSourceOutput(compilationAndClasses, (spc, source) =>
            {
                try
                {
                    var (compilation, types) = source;

                    //Diagnostic: Report how many candidate types were discovered.
                    var candidateDiagnostic = new DiagnosticDescriptor(
                        id: "CQRGEN002",
                        title: "Candidate Types Discovered",
                        messageFormat: $"HandlerRegistrationGenerator found {types.Length} candidate types.",
                        category: "SourceGenerator",
                        defaultSeverity: DiagnosticSeverity.Info,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(candidateDiagnostic, Location.None));

                    //Process handler registrations.
                    var registrations = ProcessHandlerRegistrations(compilation, types);
                    //Process request metadata.
                    var metadataEntries = ProcessRequestMetadata(compilation, types);

                    //Diagnostic: Report processing results.
                    var processDiagnostic = new DiagnosticDescriptor(
                        id: "CQRGEN003",
                        title: "Processing Complete",
                        messageFormat: $"Processed {registrations.Length} registrations and {metadataEntries.Length} metadata entries.",
                        category: "SourceGenerator",
                        defaultSeverity: DiagnosticSeverity.Info,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(processDiagnostic, Location.None));

                    //Correlate metadata with registrations so that the handler type is populated.
                    var correlatedMetadataEntries = metadataEntries.Select(meta =>
                    {
                        var metaKeyNormalized = NormalizeKey(meta.RequestTypeName);
                        var reg = registrations.FirstOrDefault(r => NormalizeKey(r.RequestTypeName) == metaKeyNormalized);
                        var handlerInterface = reg != null ? reg.HandlerInterfaceName : null;
                        return new MetadataEntry(
                            meta.RequestTypeName,
                            handlerInterface,
                            meta.PreHandlerAttributes,
                            meta.PostHandlerAttributes,
                            meta.PipelineExemptions,
                            meta.SensitiveProperties,
                            meta.ResultType);
                    }).ToImmutableArray();

                    //Generate output source.
                    var sourceCode = GenerateSource(registrations, correlatedMetadataEntries);
                    spc.AddSource("HandlerRegistration.g.cs", SourceText.From(sourceCode, Encoding.UTF8));

                    //Diagnostic: Confirm generation complete.
                    var completeDiagnostic = new DiagnosticDescriptor(
                        id: "CQRGEN004",
                        title: "Generation Complete",
                        messageFormat: $"HandlerRegistration.g.cs generated successfully.",
                        category: "SourceGenerator",
                        defaultSeverity: DiagnosticSeverity.Info,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(completeDiagnostic, Location.None));
                }
                catch (Exception ex)
                {
                    //Diagnostic: Report an error if something goes wrong.
                    var errorDiagnostic = new DiagnosticDescriptor(
                        id: "CQRGEN999",
                        title: "Generator Exception",
                        messageFormat: $"HandlerRegistrationGenerator encountered an exception: {ex.Message}",
                        category: "SourceGenerator",
                        defaultSeverity: DiagnosticSeverity.Error,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(errorDiagnostic, Location.None));

                    //Optionally rethrow to fail the build if desired.
                    throw;
                }
            });
        }

        private static INamedTypeSymbol GetNamedTypeSymbol(GeneratorSyntaxContext context)
        {
            return context.SemanticModel.GetDeclaredSymbol(context.Node) as INamedTypeSymbol;
        }

        #region Processing Handlers

        private static ImmutableArray<Registration> ProcessHandlerRegistrations(Compilation compilation, ImmutableArray<INamedTypeSymbol> types)
        {
            var builder = ImmutableArray.CreateBuilder<Registration>();

            //Use string literals for type references.
            var iCommandHandlerInterface = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Handlers.ICommandHandler`1");
            var iQueryHandlerInterface = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Handlers.IQueryHandler`2");
            var iNotificationHandlerInterface = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Notifications.INotificationHandler`1");
            var iPipelineBehaviorInterface = compilation.GetTypeByMetadataName("CQRSharp.Core.Pipelines.IPipelineBehavior`2");

            foreach (var type in types)
            {
                if (type == null)
                    continue;
                //Consider only classes and structs.
                if (type.TypeKind != TypeKind.Class && type.TypeKind != TypeKind.Struct)
                    continue;

                foreach (var iface in type.AllInterfaces)
                {
                    if (iCommandHandlerInterface != null &&
                        iface.OriginalDefinition.Equals(iCommandHandlerInterface, SymbolEqualityComparer.Default))
                    {
                        var requestType = iface.TypeArguments[0].ToDisplayString(Format);
                        builder.Add(new Registration(requestType, iface.ToDisplayString(Format), type.ToDisplayString(Format), "CommandHandler"));
                    }
                    else if (iQueryHandlerInterface != null &&
                             iface.OriginalDefinition.Equals(iQueryHandlerInterface, SymbolEqualityComparer.Default))
                    {
                        var requestType = iface.TypeArguments[0].ToDisplayString(Format);
                        builder.Add(new Registration(requestType, iface.ToDisplayString(Format), type.ToDisplayString(Format), "QueryHandler"));
                    }
                    else if (iNotificationHandlerInterface != null &&
                             iface.OriginalDefinition.Equals(iNotificationHandlerInterface, SymbolEqualityComparer.Default))
                    {
                        var requestType = iface.TypeArguments[0].ToDisplayString(Format);
                        builder.Add(new Registration(requestType, iface.ToDisplayString(Format), type.ToDisplayString(Format), "NotificationHandler"));
                    }
                    else if (iPipelineBehaviorInterface != null &&
                             iface.OriginalDefinition.Equals(iPipelineBehaviorInterface, SymbolEqualityComparer.Default))
                    {
                        var requestType = iface.TypeArguments[0].ToDisplayString(Format);
                        builder.Add(new Registration(requestType, iface.ToDisplayString(Format), type.ToDisplayString(Format), "PipelineBehavior"));
                    }
                }
            }
            return builder.ToImmutable();
        }

        #endregion

        #region Processing Request Metadata

        private static ImmutableArray<MetadataEntry> ProcessRequestMetadata(Compilation compilation, ImmutableArray<INamedTypeSymbol> types)
        {
            var builder = ImmutableArray.CreateBuilder<MetadataEntry>();

            //Use string literals for type references.
            var iRequestSymbol = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Markers.Request.IRequest");
            var iQuerySymbol = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Markers.Query.IQuery`1");
            var iCommandSymbol = compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Markers.Command.ICommand");
            var preHandlerAttrSymbol = compilation.GetTypeByMetadataName("CQRSharp.Core.Pipelines.Attributes.IPreHandlerAttribute");
            var postHandlerAttrSymbol = compilation.GetTypeByMetadataName("CQRSharp.Core.Pipelines.Attributes.IPostHandlerAttribute");
            var pipelineExemptionSymbol = compilation.GetTypeByMetadataName("CQRSharp.Core.Pipelines.Attributes.Markers.PipelineExemptionAttribute");
            var sensitiveDataSymbol = compilation.GetTypeByMetadataName("CQRSharp.Core.Pipelines.Attributes.Markers.SensitiveDataAttribute");

            foreach (var type in types)
            {
                if (type == null)
                    continue;
                if (iRequestSymbol == null)
                    continue;
                var requestTypeKey = type.ToDisplayString(Format);
                if (!type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iRequestSymbol)))
                    continue;

                //Gather PreHandler attributes.
                string[] preHandlers = type.GetAttributes()
                    .Where(a => preHandlerAttrSymbol != null &&
                                a.AttributeClass.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, preHandlerAttrSymbol)))
                    .Select(a => GenerateAttributeInstantiationCode(a))
                    .ToArray();

                //Gather PostHandler attributes.
                string[] postHandlers = type.GetAttributes()
                    .Where(a => postHandlerAttrSymbol != null &&
                                a.AttributeClass.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, postHandlerAttrSymbol)))
                    .Select(a => GenerateAttributeInstantiationCode(a))
                    .ToArray();

                //Gather PipelineExemption attributes.
                string[] pipelineExemptions = type.GetAttributes()
                    .Where(a => pipelineExemptionSymbol != null &&
                                SymbolEqualityComparer.Default.Equals(a.AttributeClass.OriginalDefinition, pipelineExemptionSymbol))
                    .Select(a => GenerateAttributeInstantiationCode(a))
                    .ToArray();

                //Process sensitive properties.
                var sensitiveProps = type.GetMembers()
                    .OfType<IPropertySymbol>()
                    .Where(p => p.GetAttributes().Any(a => sensitiveDataSymbol != null && SymbolEqualityComparer.Default.Equals(a.AttributeClass, sensitiveDataSymbol)))
                    .Select(p => new Tuple<string, bool>(p.Name, true))
                    .ToArray();

                //Determine the result type.
                string resultType = null;
                var queryInterface = type.AllInterfaces.FirstOrDefault(i =>
                    i.OriginalDefinition.Equals(iQuerySymbol, SymbolEqualityComparer.Default));
                if (queryInterface != null)
                {
                    resultType = queryInterface.TypeArguments[0].ToDisplayString(Format);
                }
                else if (type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iCommandSymbol)))
                {
                    resultType = "CQRSharp.Data.Commands.CommandResult";
                }
                else
                {
                    resultType = null;
                }

                //Initially, leave the handler interface empty; it will be updated during correlation.
                string handlerInterface = "";
                builder.Add(new MetadataEntry(
                    requestTypeKey,
                    handlerInterface,
                    preHandlers,
                    postHandlers,
                    pipelineExemptions,
                    sensitiveProps,
                    resultType
                ));
            }
            return builder.ToImmutable();
        }

        /// <summary>
        /// Generates the instantiation code for an attribute, including its constructor arguments.
        /// For example, for a PipelineExemptionAttribute with a Type argument, this might return:
        /// "new CQRSharp.Core.Pipelines.Attributes.Markers.PipelineExemptionAttribute(typeof(TimeoutBehavior<SampleCommand, CommandResult>))"
        /// </summary>
        private static string GenerateAttributeInstantiationCode(AttributeData attr)
        {
            var attrClass = attr.AttributeClass.ToDisplayString(Format);
            string args = "";
            if (attr.ConstructorArguments.Length > 0)
            {
                var arg = attr.ConstructorArguments[0];
                if (arg.Kind == TypedConstantKind.Type && arg.Value is ITypeSymbol typeSymbol)
                    args = "typeof(" + typeSymbol.ToDisplayString(Format) + ")";
                else if (arg.Kind == TypedConstantKind.Primitive && arg.Value != null)
                    args = arg.Value is string ? $"\"{arg.Value}\"" : arg.Value.ToString();
            }
            return "new " + attrClass + "(" + args + ")";
        }

        #endregion

        #region Generating Source

        private static string GenerateSource(ImmutableArray<Registration> registrations, ImmutableArray<MetadataEntry> metadataEntries)
        {
            var sb = new StringBuilder();
            sb.AppendLine("//<auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using CQRSharp.Core.Caching.Requests;");
            sb.AppendLine("using CQRSharp.Core.Pipelines.Attributes;");
            sb.AppendLine("using CQRSharp.Core.Pipelines.Attributes.Markers;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();
            sb.AppendLine("namespace " + SourceGeneratorConstants.GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class " + SourceGeneratorConstants.HandlerRegistryClassName);
            sb.AppendLine("    {");
            //Registration method.
            sb.AppendLine("        public static void RegisterHandlers(IServiceCollection services)");
            sb.AppendLine("        {");
            foreach (var reg in registrations)
            {
                sb.AppendLine("            services.AddTransient(typeof(" + reg.HandlerInterfaceName + "), typeof(" + reg.HandlerTypeName + ")); //" + reg.RegistrationKind);
            }
            sb.AppendLine("        }");
            sb.AppendLine();
            //RegistrationMap dictionary.
            sb.AppendLine("        public static IReadOnlyDictionary<Type, (Type HandlerInterface, string RegistrationKind)> RegistrationMap { get; } = new Dictionary<Type, (Type, string)>");
            sb.AppendLine("        {");
            foreach (var reg in registrations)
            {
                sb.AppendLine("            { typeof(" + reg.RequestTypeName + "), (typeof(" + reg.HandlerInterfaceName + "), \"" + reg.RegistrationKind + "\") },");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
            //MetadataMap dictionary.
            sb.AppendLine("        public static IReadOnlyDictionary<Type, RequestMetadata> MetadataMap { get; } = new Dictionary<Type, RequestMetadata>");
            sb.AppendLine("        {");
            foreach (var meta in metadataEntries)
            {
                sb.AppendLine("            { typeof(" + meta.RequestTypeName + "), new RequestMetadata(");
                sb.AppendLine("                typeof(" + meta.RequestTypeName + "),");
                if (!string.IsNullOrEmpty(meta.HandlerInterfaceName))
                    sb.AppendLine("                typeof(" + meta.HandlerInterfaceName + "),");
                else
                    sb.AppendLine("                null,");
                //Pre-handler attributes.
                if (meta.PreHandlerAttributes.Length > 0)
                {
                    sb.Append("                new IPreHandlerAttribute[] { ");
                    sb.Append(string.Join(", ", meta.PreHandlerAttributes));
                    sb.AppendLine(" },");
                }
                else
                {
                    sb.AppendLine("                Array.Empty<IPreHandlerAttribute>(),");
                }
                //Post-handler attributes.
                if (meta.PostHandlerAttributes.Length > 0)
                {
                    sb.Append("                new IPostHandlerAttribute[] { ");
                    sb.Append(string.Join(", ", meta.PostHandlerAttributes));
                    sb.AppendLine(" },");
                }
                else
                {
                    sb.AppendLine("                Array.Empty<IPostHandlerAttribute>(),");
                }
                //Pipeline exemptions.
                if (meta.PipelineExemptions.Length > 0)
                {
                    sb.Append("                new PipelineExemptionAttribute[] { ");
                    sb.Append(string.Join(", ", meta.PipelineExemptions));
                    sb.AppendLine(" },");
                }
                else
                {
                    sb.AppendLine("                null,");
                }
                //Sensitive properties.
                if (meta.SensitiveProperties.Length > 0)
                {
                    sb.Append("                new PropertySensitivity[] { ");
                    sb.Append(string.Join(", ", meta.SensitiveProperties.Select(p => "new PropertySensitivity(\"" + p.Item1 + "\", " + p.Item2.ToString().ToLower() + ")")));
                    sb.AppendLine(" },");
                }
                else
                {
                    sb.AppendLine("                Array.Empty<CQRSharp.Core.Caching.Requests.PropertySensitivity>(),");
                }
                if (!string.IsNullOrEmpty(meta.ResultType))
                    sb.AppendLine("                typeof(" + meta.ResultType + ")");
                else
                    sb.AppendLine("                null");
                sb.AppendLine("            ) },");
            }
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        #endregion
    }

    //Using classes instead of records for compatibility.
    internal class Registration
    {
        public string RequestTypeName { get; private set; }
        public string HandlerInterfaceName { get; private set; }
        public string HandlerTypeName { get; private set; }
        public string RegistrationKind { get; private set; }

        public Registration(string requestTypeName, string handlerInterfaceName, string handlerTypeName, string registrationKind)
        {
            RequestTypeName = requestTypeName;
            HandlerInterfaceName = handlerInterfaceName;
            HandlerTypeName = handlerTypeName;
            RegistrationKind = registrationKind;
        }
    }

    internal class MetadataEntry
    {
        public string RequestTypeName { get; private set; }
        public string HandlerInterfaceName { get; private set; }
        public string[] PreHandlerAttributes { get; private set; }
        public string[] PostHandlerAttributes { get; private set; }
        public string[] PipelineExemptions { get; private set; }
        public Tuple<string, bool>[] SensitiveProperties { get; private set; }
        public string ResultType { get; private set; }

        public MetadataEntry(
            string requestTypeName,
            string handlerInterfaceName,
            string[] preHandlerAttributes,
            string[] postHandlerAttributes,
            string[] pipelineExemptions,
            Tuple<string, bool>[] sensitiveProperties,
            string resultType)
        {
            RequestTypeName = requestTypeName;
            HandlerInterfaceName = handlerInterfaceName;
            PreHandlerAttributes = preHandlerAttributes;
            PostHandlerAttributes = postHandlerAttributes;
            PipelineExemptions = pipelineExemptions;
            SensitiveProperties = sensitiveProperties;
            ResultType = resultType;
        }
    }
}