using System;
using System.Linq;
using System.Text;
using CQRSharp.Core.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CQRSharp.Generator
{
    [Generator]
    public class PipelineBuilderGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource("PipelineBuilder_Init.g.cs", SourceText.From("//<auto-generated/> //PipelineBuilder initialized", Encoding.UTF8));
            });

            var requestSymbolsProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                    transform: static (ctx, cancellationToken) =>
                    {
                        var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, cancellationToken);
                        if (symbol is not INamedTypeSymbol namedSymbol)
                            return null;

                        var iRequest = ctx.SemanticModel.Compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Markers.Request.IRequest");
                        return iRequest != null && namedSymbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iRequest))
                            ? namedSymbol
                            : null;
                    })
                .Where(symbol => symbol is not null)
                .Collect();

            context.RegisterSourceOutput(requestSymbolsProvider, (spc, collectedSymbols) =>
            {
                try
                {
                    if (collectedSymbols.Length == 0)
                    {
                        ReportDiagnostic(spc, "CQRGEN1001", "No IRequest implementations found.", DiagnosticSeverity.Warning);
                        return;
                    }

                    var sb = new StringBuilder();
                    sb.AppendLine("//<auto-generated/>");
                    sb.AppendLine("using System;");
                    sb.AppendLine("using System.Collections.Generic;");
                    sb.AppendLine("using System.Linq;");
                    sb.AppendLine("using System.Threading;");
                    sb.AppendLine("using System.Threading.Tasks;");
                    sb.AppendLine("using CQRSharp.Core.Pipelines;");
                    sb.AppendLine("using CQRSharp.Data.Commands;");
                    sb.AppendLine("using CQRSharp.Core.Caching.Pipelines;");
                    sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
                    sb.AppendLine();
                    sb.AppendLine($"namespace {SourceGeneratorConstants.GeneratedNamespace}");
                    sb.AppendLine("{");
                    sb.AppendLine($"    public static class {SourceGeneratorConstants.PipelineRegistryClassName}");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        public static IReadOnlyDictionary<Type, PipelineBuilderDelegate> {SourceGeneratorConstants.PipelineMapPropertyName} {{ get; }} =");
                    sb.AppendLine("            new Dictionary<Type, PipelineBuilderDelegate>");
                    sb.AppendLine("            {");

                    foreach (var symbol in collectedSymbols)
                    {
                        try
                        {
                            var requestType = symbol!.ToDisplayString();
                            var iQuery = symbol.AllInterfaces.FirstOrDefault(i =>
                                i.IsGenericType &&
                                i.OriginalDefinition.ToDisplayString() == "CQRSharp.Interfaces.Markers.Query.IQuery<T>");
                            var resultType = iQuery is { TypeArguments.Length: 1 } ? iQuery.TypeArguments[0].ToDisplayString() : "CQRSharp.Data.Commands.CommandResult";

                            sb.AppendLine("                {");
                            sb.AppendLine($"                    typeof({requestType}),");
                            sb.AppendLine("                    (services, request, finalHandler, ct) =>");
                            sb.AppendLine("                    {");
                            sb.AppendLine($"                        //Resolve all pipeline behaviors for {requestType}");
                            sb.AppendLine($"                        var behaviors = services.GetServices(typeof(CQRSharp.Core.Pipelines.IPipelineBehavior<{requestType}, {resultType}>))");
                            sb.AppendLine($"                            .Cast<CQRSharp.Core.Pipelines.IPipelineBehavior<{requestType}, {resultType}>>().ToArray();");
                            sb.AppendLine();
                            sb.AppendLine($"                        Func<{requestType}, CancellationToken, Task<{resultType}>> pipeline = async (req, cancellationToken) =>");
                            sb.AppendLine("                        {");
                            sb.AppendLine("                            //Final delegate: invoke the finalHandler delegate");
                            sb.AppendLine($"                            return await Task.FromResult(({resultType})await ((Func<CancellationToken, Task<object>>)(finalHandler))(cancellationToken));");
                            sb.AppendLine("                        };");
                            sb.AppendLine();
                            sb.AppendLine("                        //Chain pipeline behaviors in reverse order");
                            sb.AppendLine("                        for (int i = behaviors.Length - 1; i >= 0; i--)");
                            sb.AppendLine("                        {");
                            sb.AppendLine("                            var behavior = behaviors[i];");
                            sb.AppendLine("                            var next = pipeline;");
                            sb.AppendLine($"                            pipeline = (req, cancellationToken) => behavior.Handle(req, ctInner => next(req, ctInner), cancellationToken);");
                            sb.AppendLine("                        }");
                            sb.AppendLine();
                            sb.AppendLine($"                        return pipeline(({requestType})request, ct).ContinueWith(t => (object)t.Result, ct);");
                            sb.AppendLine("                    }");
                            sb.AppendLine("                },");
                        }
                        catch (Exception ex)
                        {
                            ReportDiagnostic(spc, "CQRGEN1002", $"Error processing request type {symbol?.ToDisplayString()}: {ex.Message}", DiagnosticSeverity.Error);
                        }
                    }

                    sb.AppendLine("            };");
                    sb.AppendLine("    }");
                    sb.AppendLine("}");

                    spc.AddSource("PipelineBuilders.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
                    ReportDiagnostic(spc, "CQRGEN1000", "PipelineBuilderGenerator completed successfully.", DiagnosticSeverity.Info);
                }
                catch (Exception ex)
                {
                    ReportDiagnostic(spc, "CQRGEN9999", $"Fatal error in PipelineBuilderGenerator: {ex.Message}", DiagnosticSeverity.Error);
                }
            });
        }

        /// <summary>
        /// Helper method to report diagnostics.
        /// </summary>
        private static void ReportDiagnostic(SourceProductionContext spc, string id, string message, DiagnosticSeverity severity)
        {
            var descriptor = new DiagnosticDescriptor(id, "CQRSharp Generator Diagnostic", message, "SourceGenerator", severity, true);
            spc.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None));
        }
    }
}