using System.Linq;
using System.Text;
using CQRSharp.Core.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CQRSharp.Generator
{
    [Generator]
    public class PipelineBuilderGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Discover candidate request types (classes or records that implement IRequest)
            var requestSymbolsProvider = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, cancellationToken) => 
                    node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, cancellationToken) =>
                {
                    //Get the declared symbol for the node.
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, cancellationToken: cancellationToken) is not INamedTypeSymbol symbol)
                        return null;

                    //Look up the IRequest interface by metadata name.
                    var iRequest = ctx.SemanticModel.Compilation.GetTypeByMetadataName("CQRSharp.Interfaces.Markers.Request.IRequest");
                    if (iRequest != null && symbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iRequest)))
                        return symbol;
                    return null;
                })
                .Collect();

            context.RegisterSourceOutput(requestSymbolsProvider, (spc, collectedSymbols) =>
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using System.Linq;");
                sb.AppendLine("using System.Threading;");
                sb.AppendLine("using System.Threading.Tasks;");
                sb.AppendLine("using CQRSharp.Core.Pipelines;");
                sb.AppendLine("using CQRSharp.Data.Commands;");
                sb.AppendLine("using CQRSharp.Core.Caching.Pipelines;");
                sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
                sb.AppendLine();
                sb.AppendLine($"namespace {SourceGeneratorConstants.GeneratedNamespace}");
                sb.AppendLine("{");
                sb.AppendLine($"    public static class {SourceGeneratorConstants.PipelineRegistryClassName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        public static IReadOnlyDictionary<Type, PipelineBuilderDelegate> {SourceGeneratorConstants.PipelineMapPropertyName} {{ get; }} =");
                sb.AppendLine("            new Dictionary<Type, PipelineBuilderDelegate>");
                sb.AppendLine("            {");

                foreach (var symbol in collectedSymbols)
                {
                    //The filtering ensures symbol is not null.
                    var requestType = symbol!.ToDisplayString();
                    
                    //Determine the result type: if the type implements IQuery<T>, use T; otherwise, assume CommandResult.
                    var iQuery = symbol.AllInterfaces.FirstOrDefault(i =>
                        i.IsGenericType &&
                        i.OriginalDefinition.ToDisplayString() == "CQRSharp.Interfaces.Markers.Query.IQuery<T>");
                    var resultType = iQuery is { TypeArguments.Length: 1 } ? iQuery.TypeArguments[0].ToDisplayString() : "CQRSharp.Data.Commands.CommandResult";

                    sb.AppendLine("                {");
                    sb.AppendLine($"                    typeof({requestType}),");
                    sb.AppendLine("                    (services, request, finalHandler, ct) =>");
                    sb.AppendLine("                    {");
                    sb.AppendLine($"                        // Resolve all pipeline behaviors for {requestType}");
                    sb.AppendLine($"                        var behaviors = services.GetServices(typeof(CQRSharp.Core.Pipelines.IPipelineBehavior<{requestType}, {resultType}>))");
                    sb.AppendLine($"                            .Cast<CQRSharp.Core.Pipelines.IPipelineBehavior<{requestType}, {resultType}>>().ToArray();");
                    sb.AppendLine();
                    sb.AppendLine($"                        Func<{requestType}, CancellationToken, Task<{resultType}>> pipeline = async (req, cancellationToken) =>");
                    sb.AppendLine("                        {");
                    sb.AppendLine("                            // Final delegate: invoke the finalHandler delegate");
                    sb.AppendLine($"                            return await Task.FromResult(({resultType})await ((Func<CancellationToken, Task<object>>)(finalHandler))(cancellationToken));");
                    sb.AppendLine("                        };");
                    sb.AppendLine();
                    sb.AppendLine("                        // Chain pipeline behaviors in reverse order");
                    sb.AppendLine("                        for (int i = behaviors.Length - 1; i >= 0; i--)");
                    sb.AppendLine("                        {");
                    sb.AppendLine("                            var behavior = behaviors[i];");
                    sb.AppendLine("                            var next = pipeline;");
                    sb.AppendLine($"                            pipeline = (req, cancellationToken) => behavior.Handle(req, ctInner => next(req, ctInner), cancellationToken);");
                    sb.AppendLine("                        }");
                    sb.AppendLine();
                    sb.AppendLine($"                        return pipeline(({requestType})request, ct).ContinueWith(t => (object)t.Result, ct);");
                    sb.AppendLine("                    }");
                    sb.AppendLine("                },");
                }

                sb.AppendLine("            };");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                spc.AddSource("PipelineBuilders.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            });
        }
    }
}