<Project Sdk="Microsoft.NET.Sdk">

    <!-- Build Configuration -->
    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;netstandard2.0</TargetFrameworks>
        <LangVersion>default</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EnableAotAnalyzer>true</EnableAotAnalyzer>
    </PropertyGroup>

    <!-- NuGet Package Metadata -->
    <PropertyGroup>
        <Title>A lightweight, extensible, and attribute-driven CQRS framework for .NET applications (Shared Library).</Title>
        <Authors>$(AssemblyName)</Authors>
        <Company>BisocM</Company>
        <PackageProjectUrl>https://cqrsharp.bisocm.org</PackageProjectUrl>
        <PackageIcon>CQRSharp_Icon.png</PackageIcon>
        <RepositoryUrl>https://github.com/BisocM/CQRSharp</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>CQRS</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <Version>2.2.3.1</Version>
        <Description>Contains shared abstractions and common types for CQRSharp. This library underpins the rest of the CQRSharp framework.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageReleaseNotes>
            🚀 Release Notes for 2.2.3.1

            🔧 Roslyn Generators
		Implemented a hotfix for Roslyn generators that would not allow them to adequately register command return types.

            📂 Breaking Changes?
		No breaking changes.</PackageReleaseNotes>
    </PropertyGroup>

    <!-- Package Assets -->
    <ItemGroup>
        <None Include="..\CQRSharp_Icon.png">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\LICENSE">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
            <Link>LICENSE</Link>
        </None>
        <None Include="..\README.md">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

</Project>